/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        elev: "var(--elev)",
        inset: "var(--inset)",
        border: "var(--border)",
        text: "var(--text)",
        muted: "var(--muted)",
        faint: "var(--faint)",
        accent: "var(--accent)",
        "accent-bright": "var(--accent-bright)",
        "accent-dim": "var(--accent-dim)",
        ok: "var(--ok)",
        warn: "var(--warn)",
        danger: "var(--danger)",
        "bus-i2c": "var(--bus-i2c)",
        "bus-spi": "var(--bus-spi)",
        "bus-qspi": "var(--bus-qspi)",
        "bus-eth": "var(--bus-eth)",
        "bus-uart": "var(--bus-uart)",
        "bus-can": "var(--bus-can)",
        "bus-sdio": "var(--bus-sdio)",
        "bus-gpio": "var(--bus-gpio)",
        "zone-ps": "var(--zone-ps)",
        "zone-pl": "var(--zone-pl)",
        "zone-noc": "var(--zone-noc)",
        "zone-aie": "var(--zone-aie)",
        silk: "var(--silk)",
        pad: "var(--pad)",
        "chip-body": "var(--chip-body)",
        "chip-body-edge": "var(--chip-body-edge)",
      },
      fontFamily: {
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
      },
      borderColor: { DEFAULT: "var(--border)" },
      boxShadow: {
        "copper-glow": "0 0 0 1px var(--accent), 0 0 18px -2px color-mix(in srgb, var(--accent) 55%, transparent)",
        "node": "0 2px 10px -4px rgba(0, 0, 0, 0.6)",
      },
      keyframes: {
        "fade-in": { from: { opacity: "0", transform: "translateY(4px)" }, to: { opacity: "1", transform: "none" } },
        "pulse-line": { "0%,100%": { opacity: "0.4" }, "50%": { opacity: "1" } },
        "flow-dash": { to: { strokeDashoffset: "-16" } },
        "pulse-soft": { "0%,100%": { opacity: "0.55" }, "50%": { opacity: "1" } },
      },
      animation: {
        "fade-in": "fade-in 0.2s ease-out",
        "pulse-line": "pulse-line 2s ease-in-out infinite",
        "flow-dash": "flow-dash 0.9s linear infinite",
        "pulse-soft": "pulse-soft 1.6s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
