"""Shell katmani (outputs/<proje>/shell/): konsol UART komut kabugu - cit / i2c_search / sdl.

Kullanicinin kendi main'inde derlenir; ajanla ilgisi yoktur. Ureticinin cikti agaci,
platforma gore UART bayt erisimi, komut dagitimi ve GERCEK gcc round-trip (stub UART'tan
"help / sdl info / i2c_search / cit" satirlari beslenir, cikti stdout'tan okunur).
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from orchestrator import codegen, shell_layer

ROOT = Path(__file__).resolve().parent.parent
STUBS = ROOT / "tests" / "xilinx_stubs"


def _find_cc() -> str | None:
    return shutil.which("gcc") or shutil.which("cc")


def _axi_spec(name: str, transport: str = "uart") -> dict:
    base = json.loads((ROOT / "specs/samples/radar_io_board.spec.json").read_text(encoding="utf-8"))
    return {
        "schema_version": base.get("schema_version", "1.0"),
        "project": {"name": name, "platform": "microblaze_7series", "target_core": "microblaze_0",
                    "runtime": "bare_metal", "output_mode": "dropin", "testbench_transport": transport},
        "coding_standard_ref": "std/default.ruleset.json",
        "llm": {"enabled": False},
        "controllers": [
            {"id": "pl_i2c_0", "type": "i2c", "instance": "XPAR_AXI_IIC_0", "base_address": "0x40800000",
             "device_id": 0, "driver": "XIic", "source": "xparameters", "zone": "pl"},
            {"id": "pl_uart_0", "type": "uart", "instance": "XPAR_AXI_UARTLITE_0",
             "base_address": "0x40600000", "device_id": 0, "driver": "XUartLite",
             "source": "xparameters", "zone": "pl"},
        ],
        "muxes": [{"id": "u1_tca9548a", "part": "TCA9548A", "controller_id": "pl_i2c_0",
                   "i2c_address": "0x70", "channels": 8}],
        "custom_ips": [{"id": "mem_pcie_intr_0", "instance": "XPAR_MEM_PCIE_INTR_0", "ip_name": "mem_pcie_intr",
                        "base_address": "0x43C00000", "high_address": "0x43C0FFFF", "register_count": 6}],
        "devices": [
            {"id": "u3_tmp101", "part": "TMP101", "descriptor_ref": "descriptors/tmp101.yaml",
             "attach": {"controller_id": "pl_i2c_0", "i2c_address": "0x4A",
                        "via_mux": {"mux_id": "u1_tca9548a", "channel": 1}},
             "operations_requested": ["device_init", "temperature_read"], "tests_requested": ["self_test"]},
        ],
    }


def _zynqmp_spec(name: str) -> dict:
    spec = json.loads((ROOT / "specs/samples/radar_io_board.spec.json").read_text(encoding="utf-8"))
    spec["project"] = {**spec["project"], "name": name}
    return spec


def _generate(spec: dict) -> Path:
    out_dir = Path(tempfile.mkdtemp(prefix="s2c_shell_"))
    codegen.generate(spec, out_dir)
    return out_dir


def _read(out_dir: Path, rel: str) -> str:
    return (out_dir / rel).read_text(encoding="utf-8")


class ShellLayerGenerationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.out_dir = _generate(_axi_spec("unit_shell_gen"))

    @classmethod
    def tearDownClass(cls) -> None:
        shutil.rmtree(cls.out_dir, ignore_errors=True)

    def test_tree_and_no_product_names(self) -> None:
        for rel in ("shell/shell_uart.h", "shell/shell_uart.c", "shell/shell.h", "shell/shell.c", "shell/main.c"):
            self.assertTrue((self.out_dir / rel).is_file(), rel)
            text = _read(self.out_dir, rel).lower().replace("generated by spec2code", "")
            self.assertNotIn("spec2code", text, f"{rel} icinde urun adi")
            self.assertIn(b"\r\n", (self.out_dir / rel).read_bytes())

    def test_api_and_commands(self) -> None:
        header = _read(self.out_dir, "shell/shell.h")
        self.assertIn("void shellInit(SSistemCitBus* spBus, const SSistemCitLimit* spLimit, SSistemCit* spCit);", header)
        self.assertIn("void shellCheck(void);", header)
        self.assertIn("typedef void (*FShellHandler)(unsigned int uiArgc, const char* cpArrArgv[]);", header)
        self.assertIn("unsigned int shellCommandsRegister(const SShellCommand* spTable, unsigned int uiCount);", header)
        source = _read(self.out_dir, "shell/shell.c")
        # Komut tablosu (ad + isleyici + yardim); if-zinciri yok.
        self.assertNotIn("strcmp(cpLine,", source)
        # Cekirdekte komut yok; tum komutlar shell_user_commands.c'deki tek tabloda (kullanici istegi).
        self.assertNotIn("S_sArrBuiltinCommands", source)
        self.assertNotIn("sistemCitRead", source)
        self.assertIn("SSistemCitBus* shellBus(void);", header)
        self.assertIn("const SShellCommand* shellCommandGet(unsigned int uiIndex);", header)
        self.assertIn("uiArgc = shellTokenize(cpLine, cpArrArgv);", source)
        self.assertIn("spCommand->fpHandler(uiArgc, cpArrArgv);", source)
        self.assertIn('xil_printf("\\r\\nshell is initialized (type help)\\r\\n");', source)
        self.assertNotIn("kabuk", source.lower())
        # Kullanici komutlari: ayri dosya, tablo + ornek mod (string arg -> atoi, Xil_Out32).
        user = _read(self.out_dir, "shell/shell_user_commands.c")
        self.assertIn("static const SShellCommand S_sArrUserCommands[] = {", user)
        for command, handler in (("cit", "shellUserCit"), ("i2c_search", "shellUserI2cSearch"),
                                 ("i2c_read", "shellUserI2cRead"), ("i2c_write", "shellUserI2cWrite"),
                                 ("mem", "shellUserMem"), ("sdl", "shellUserSdl"), ("help", "shellUserHelp"),
                                 ("mod", "shellUserMod"), ("mem_pcie_intr_0", "shellUserMemPcieIntr0")):
            self.assertIn(f'{{"{command}", {handler}, "', user)
        self.assertIn("iResult = sistemCitRead(shellBus(), shellLimit(), shellCit());", user)
        self.assertIn("spCommand = shellCommandGet(uiIndex);", user)
        self.assertIn("iIndex = atoi(cpArrArgv[1]);", user)
        self.assertIn('strcmp(cpArrArgv[2], "open") == 0', user)
        self.assertIn("Xil_Out32((UINTPTR)uiAddress, (u32)uiValue);", user)
        # mod test: AXI INTC (XPAR_XINTC_NUM_INSTANCES ile korunur), volatile bayrak, 1 s zaman asimi, 14 durum.
        self.assertIn("static volatile unsigned int S_uiModTestDone = 0U;", user)
        self.assertIn("XIntc_Connect(&S_sModIntc, (u8)SHELL_USER_MOD_INTR_ID, shellUserModInterruptHandler, NULL)", user)
        self.assertIn("#define SHELL_USER_MOD_INTR_ID_UNSET 1", user)
        self.assertIn("#define SHELL_USER_MOD_TEST_TIMEOUT_MS 1000U", user)
        self.assertIn("#define SHELL_USER_MOD_CONNECTOR_COUNT 14U", user)
        self.assertIn('xil_printf("mod: no AXI INTC in this design', user)
        self.assertIn("0x01010101U, 0x02020202U, 0x03030303U, 0x04040404U, 0x05050505U, 0x06060606U, 0x07070707U, 0x08080808U", user)
        self.assertIn("const SShellCommand* shellUserCommandTable(void);", _read(self.out_dir, "shell/shell_user_commands.h"))
        # cit: esik ZORLANMAZ (kullanici sdl ile acar); yalniz sdl komutu dbgLevelSet cagirir.
        self.assertNotIn("dbgLevelSet(DEBUG_LEVEL_INFO)", user)
        self.assertNotIn("uiOldLevel", user)
        self.assertEqual(user.count("dbgLevelSet("), 1)
        # i2c_search: AXI IIC dinamik prob, switch adresi atlanir.
        self.assertIn("XIic_DynSend(spIic->BaseAddress, (unsigned short)uiAddress, &ucProbe, 1U, XIIC_STOP)", user)
        self.assertIn("S_uiArrSwitchAddress[] = {0x70U};", user)
        self.assertIn("shellUserI2cProbeXIic(shellBus()->sPlI2c0, uiAddress)", user)
        # ACK satiri spec'teki cihaz adiyla etiketlenir (adres -> kimlik tablosu, switch bilgisiyle).
        self.assertIn('{0x4AU, "u3_tmp101 (TMP101, switch 0x70 ch1)"}', user)
        self.assertIn('return "(not in spec)";', user)
        # Tek denetleyici: i2c_bus yok, dagitim dogrudan; okuma REPEATED_START + DynRecv.
        self.assertNotIn('"i2c_bus"', user)
        self.assertIn("XIic_DynSend(spIic->BaseAddress, (unsigned short)uiAddress, &ucRegister, 1U, XIIC_REPEATED_START)", user)
        self.assertIn("XIic_DynRecv(spIic->BaseAddress, (unsigned char)uiAddress, ucpData, (unsigned char)uiCount)", user)
        self.assertIn("Xil_In32((UINTPTR)ulAddress)", user)
        # Custom IP: XSA araligi (register_count) ile sinirli dump/read/write; base spec'ten.
        self.assertIn('shellUserCustomIp("mem_pcie_intr_0", 0x43C00000U, 6U, uiArgc, cpArrArgv);', user)
        self.assertIn("if (ulIndex >= (unsigned long)uiCount)", user)
        # sdl: adlar ve 0..5
        self.assertIn('S_cpArrLevelName[] = {"always", "error", "warning", "msg", "info", "trace"};', user)
        self.assertIn("strcmp(cpArgument, S_cpArrLevelName[uiIndex]) == 0", user)
        # satir okuma bloklamaz: while (shellUartByteRead(...))
        self.assertIn("while (shellUartByteRead(&ucByte) == TRUE)", source)
        # gecmis: ESC [ A / ESC [ B, halka, ayni komut tek kayit
        self.assertIn("static char S_cArrHistory[SHELL_HISTORY_MAX][SHELL_LINE_MAX];", source)
        self.assertIn("shellHistoryAdd(S_cArrLine);", source)
        self.assertIn("if (ucByte == (unsigned char)'A')", source)
        self.assertIn("if (ucByte == (unsigned char)'B')", source)

    def test_uart_access_follows_platform(self) -> None:
        uart = _read(self.out_dir, "shell/shell_uart.c")
        self.assertIn('#include "xuartlite_l.h"', uart)
        self.assertIn("XUartLite_IsReceiveEmpty(STDIN_BASEADDRESS)", uart)
        self.assertIn("XUartLite_RecvByte(STDIN_BASEADDRESS)", uart)
        self.assertIn("XUartLite_SendByte(STDOUT_BASEADDRESS, ucByte)", uart)

    def test_main_wires_banner_and_init_before_loop(self) -> None:
        main = _read(self.out_dir, "shell/main.c")
        self.assertTrue((self.out_dir / "shell" / "main.h").is_file())
        self.assertIn('#include "main.h"', main)
        self.assertIn("sistemCitBusVarsayilan(&S_sBus);", main)
        self.assertIn("iStatus = sistemCitInit(&S_sBus);", main)
        self.assertIn("shellInit(&S_sBus, &S_sLimit, &S_sCit);", main)
        self.assertIn("(void)shellCommandsRegister(shellUserCommandTable(), shellUserCommandCount());", main)
        self.assertNotIn("for (;;)", main)
        self.assertLess(main.index("mainBannerWrite();"), main.index("sistemCitInit("))
        self.assertLess(main.index("sistemCitInit("), main.index("while (1)"))
        self.assertIn("shellCheck();", main[main.index("while (1)"):])
        # Banner: proje adi buyuk harf Colossal; her satir xil_printf ile, ters bolu C'de kacisli.
        lines = shell_layer.banner_lines(_axi_spec("unit_shell_gen"))
        self.assertTrue(8 <= len(lines) <= 11, lines)
        self.assertTrue(any("888" in line for line in lines))
        for line in lines:
            escaped = line.replace("\\", "\\\\").replace('"', '\\"')
            self.assertIn(f'xil_printf("{escaped}\\r\\n");', main)

    def test_banner_font_renders_uppercase_and_unknown_as_space(self) -> None:
        from orchestrator import banner_font
        rows = banner_font.render_banner("ab_1")
        self.assertEqual(rows, banner_font.render_banner("AB_1"))
        self.assertTrue(all(len(r) == len(r.rstrip()) for r in rows))
        self.assertTrue(rows and rows[0].strip() and rows[-1].strip())
        self.assertEqual(len(banner_font.render_banner("")), 0)

    def test_readme_mentions_shell(self) -> None:
        readme = _read(self.out_dir, "README.md")
        self.assertIn("## Konsol shell'i (`shell/`)", readme)
        self.assertIn("`sdl <level>`", readme)
        self.assertIn("`mod <x> <y>`", readme)


class ShellLayerPlatformTests(unittest.TestCase):
    def test_zynqmp_uses_ps_uart_and_xiicps_probe(self) -> None:
        out_dir = _generate(_zynqmp_spec("unit_shell_zynqmp"))
        try:
            uart = _read(out_dir, "shell/shell_uart.c")
            self.assertIn('#include "xuartps_hw.h"', uart)
            self.assertIn("XUartPs_IsReceiveData(STDIN_BASEADDRESS) == 0U", uart)
            source = _read(out_dir, "shell/shell_user_commands.c")
            self.assertIn("XIicPs_MasterSendPolled(spIic, &ucProbe, 1, (unsigned short)uiAddress)", source)
            self.assertIn("XIicPs_BusIsBusy(spIic)", source)
            self.assertIn("XIicPs_MasterRecvPolled(spIic, ucpData, (int)uiCount, (unsigned short)uiAddress)", source)
        finally:
            shutil.rmtree(out_dir, ignore_errors=True)

    def test_console_uart_driver_prefers_non_mdm_uart(self) -> None:
        spec = _axi_spec("unit_shell_mdm", transport="mdm")
        spec["controllers"].append({"id": "pl_uart_1", "type": "uart", "instance": "XPAR_MDM_1",
                                    "base_address": "0x41400000", "device_id": 1, "driver": "XUartLite",
                                    "source": "xparameters", "zone": "pl", "subtype": "mdm"})
        self.assertEqual(shell_layer.console_uart_driver(spec), "XUartLite")
        self.assertEqual(shell_layer.console_uart_driver({"project": {"platform": "versal"}, "controllers": []}), "XUartPsv")


_HOST_XPARAMETERS = """#ifndef XPARAMETERS_H
#define XPARAMETERS_H
#define XPAR_XIIC_NUM_INSTANCES 1
#define XPAR_AXI_IIC_0_BASEADDR 0x40800000UL
#define XPAR_AXI_IIC_0_DEVICE_ID 0U
#define STDIN_BASEADDRESS 0x40600000UL
#define STDOUT_BASEADDRESS 0x40600000UL
#define XPAR_XINTC_NUM_INSTANCES 1
#define XPAR_INTC_0_DEVICE_ID 0
#endif
"""

_HOST_MAIN = r"""
#include <stdio.h>
#include <string.h>
#include "sistem_cit.h"
#include "shell.h"
#include "shell_user_commands.h"
extern const unsigned char* g_ucpStubUartIn;
extern unsigned int g_uiStubUartInLen;
extern unsigned int g_uiStubI2cAckAddress;
extern unsigned long g_uiStubIntcFireAfterUs;
extern u32 (*g_fpStubIn32)(UINTPTR Addr);
/* mod test: konnektor 1 (reg8) bit31+bit0 hatali, konnektor 14 (reg21) bit8 hatali, digerleri temiz. */
static u32 stubIn32(UINTPTR ulAddress)
{
    if (ulAddress == 0x43C00020UL) { return 0x80000001U; }
    if (ulAddress == 0x43C00054UL) { return 0x00000100U; }
    return 0U;
}
static SSistemCitBus S_sBus;
static const SSistemCitLimit S_sLimit = SISTEM_CIT_LIMIT_VARSAYILAN;
static SSistemCit S_sCit;
/* Son: yukari-yukari + Enter -> "sdl 9" yeniden kosar (xyz'den bir onceki); asagi-asagi -> bos satir. */
static const char S_cArrScript[] = "help\rsdl info\rsdl 9\rxyz\r\x1b[A\x1b[A\r\x1b[B\x1b[B\rsdl\ri2c_search\r"
                                   "mod 3 open\rmod  9  open\rmod 3 close\rmod 3 half\rmod 3\rmod 0 test\rmod 1 test\r"
                                   "i2c_read 0x4A 0x00 2\ri2c_read 0x4B 0\ri2c_read 0x4A zz\ri2c_write 0x4A 0x01 0x60\r"
                                   "i2c_write 0x4B 1\rmem 0x43C00000\rmem 0x43C00004 0x12345678\rmem 0x43C00001\r"
                                   "mem_pcie_intr_0 dump\rmem_pcie_intr_0 read 5\rmem_pcie_intr_0 read 6\r"
                                   "mem_pcie_intr_0 write 2 0xCAFE0002\rmem_pcie_intr_0 write 9 1\rmem_pcie_intr_0 flip\r"
                                   "cit\rsdl error\rcit\r";
int main(void)
{
    unsigned int uiTur;
    sistemCitBusVarsayilan(&S_sBus);
    (void)sistemCitInit(&S_sBus);
    shellInit(&S_sBus, &S_sLimit, &S_sCit);
    (void)shellCommandsRegister(shellUserCommandTable(), shellUserCommandCount());
    g_uiStubI2cAckAddress = 0x4AU; /* i2c_search: yalniz TMP101 adresi ACK */
    g_uiStubIntcFireAfterUs = 5000UL; /* ilk mod test: 5. usleep(1000)'de kesme; ikincisi zaman asimi */
    g_fpStubIn32 = stubIn32;
    g_ucpStubUartIn = (const unsigned char*)S_cArrScript;
    g_uiStubUartInLen = (unsigned int)strlen(S_cArrScript);
    for (uiTur = 0U; uiTur < 4U; uiTur++)
    {
        shellCheck(); /* tum satirlar tek cagrida islenir; ekstra turlar bloklamadigini gosterir */
    }
    printf("\nSON sayac=%u\n", S_sCit.uiSayac);
    return 0;
}
"""


@unittest.skipUnless(_find_cc(), "host C compiler required")
class ShellHostRoundTripTests(unittest.TestCase):
    """drivers + cit + sim + shell gercek derleyicide; komutlar stub UART'tan beslenir."""

    def test_commands_over_stub_console(self) -> None:
        spec = _axi_spec("unit_shell_host_rt")
        for device in spec["devices"]:
            device["simulate"] = True
        out_dir = _generate(spec)
        try:
            work = out_dir / "host"
            work.mkdir()
            (work / "xparameters.h").write_text(_HOST_XPARAMETERS, encoding="utf-8")
            (work / "main.c").write_text(_HOST_MAIN, encoding="utf-8")
            binary = work / ("shell_host.exe" if os.name == "nt" else "shell_host")
            sources = [str(work / "main.c"), str(STUBS / "xilinx_stubs.c"),
                       *[str(p) for p in (out_dir / "drivers").glob("*.c")],
                       *[str(p) for p in (out_dir / "cit").glob("*.c")],
                       *[str(p) for p in (out_dir / "shell").glob("shell*.c")],
                       *[str(p) for p in (out_dir / "tests" / "sim").glob("*.c")]]
            cmd = [_find_cc(), "-std=c99", "-Wall", "-Wextra", "-Werror",
                   "-include", "spec2code_sim_xilinx.h", "-DSHELL_USER_MOD_BASEADDR=0x43C00000U", "-DSHELL_USER_MOD_INTR_ID=3U",
                   "-I", str(work), "-I", str(STUBS), "-I", str(out_dir / "drivers"),
                   "-I", str(out_dir / "cit"), "-I", str(out_dir / "shell"), "-I", str(out_dir / "tests" / "sim"),
                   "-o", str(binary), *sources]
            build = subprocess.run(cmd, capture_output=True, text=True)
            self.assertEqual(build.returncode, 0, build.stderr)
            run = subprocess.run([str(binary)], capture_output=True, text=True)
            self.assertEqual(run.returncode, 0, run.stderr)
            out = run.stdout
        finally:
            shutil.rmtree(out_dir, ignore_errors=True)
        self.assertIn("shell is initialized (type help)", out)
        self.assertNotIn("kabuk", out)
        self.assertIn("commands:", out)                       # help
        self.assertIn("  mod          <0..7> <open|close|test>", out)  # kullanici tablosu help'te
        self.assertIn("log level: info (4)", out)             # sdl info
        self.assertEqual(out.count("sdl: invalid level '9'"), 2)  # sdl 9 + gecmisten (yukari x2) tekrar
        self.assertIn("unknown command: xyz (type help)", out)  # xyz
        self.assertIn("pl_i2c_0: scanning 0x08..0x77", out)   # i2c_search
        self.assertIn("0x70  (I2C switch, skipped)", out)
        # Stub hatta yalniz 0x4A ACK verir (g_uiStubI2cAckAddress): spec'teki ad + switch bilgisiyle etiketlenir.
        self.assertIn("0x4A  ACK  u3_tmp101 (TMP101, switch 0x70 ch1)", out)
        self.assertIn("pl_i2c_0: 1 device(s)", out)
        # mod: string argv -> atoi; fazla bosluk tokenizer'da sorun degil; open desen, close 0, hatali y/argc.
        self.assertIn("XIL_OUT32 0x43C0000C <= 0x04040404", out)   # reg3 -> (3+1) deseni
        self.assertIn("mod: reg3 @0x43C0000C <= 0x04040404 (open)", out)
        self.assertIn("mod: x must be 0..7 (got '9')", out)
        self.assertIn("XIL_OUT32 0x43C0000C <= 0x00000000", out)
        self.assertIn("mod: y must be open, close or test (got 'half')", out)
        self.assertIn("usage: mod <0..7> <open|close|test>", out)
        # mod 0 test: desen yaz, kesme 5 ms'de gelir (stub), 14 konnektor renkli, close yazilir.
        self.assertIn("mod: test 0 started (reg0 <= 0x01010101), waiting for interrupt (max 1000 ms)", out)
        self.assertIn("mod: interrupt received after 5 ms", out)
        self.assertIn("XIL_OUT32 0x43C00000 <= 0x01010101", out)
        self.assertIn("     1    8  0x43C00020  0x80000001  ", out)
        self.assertIn("    14   21  0x43C00054  0x00000100  ", out)
        self.assertIn("\x1b[31m1\x1b[32m0\x1b[32m0", out)            # bit31 kirmizi, sonrakiler yesil
        self.assertIn("\x1b[31m2 error(s)", out)                      # konnektor 1
        self.assertIn("\x1b[32m0 error(s)", out)                      # temiz konnektor
        self.assertIn("mod: gpio loopback NOK - 3 error bit(s) in 14 connectors", out)
        self.assertIn("mod: reg0 <= 0x00000000 (close)", out)
        # mod 1 test: kesme gelmez -> 1000 ms sonra TIMEOUT, durum yine basilir, close yazilir.
        self.assertIn("mod: test 1 started (reg1 <= 0x02020202)", out)
        self.assertIn("mod: TIMEOUT - no interrupt within 1000 ms", out)
        self.assertIn("mod: reg1 <= 0x00000000 (close)", out)
        self.assertEqual(out.count("mod: gpio loopback NOK"), 2)
        self.assertEqual(out.count("XIL_OUT32"), 8)  # mod open/close, mem yazma, custom IP write, 2 x (test open + close)
        # Custom IP komutu: dump 6 register (4 + 2 satir), read sinir, write + readback, hatali alt komut.
        self.assertIn("mem_pcie_intr_0: base 0x43C00000, 6 registers", out)
        self.assertIn("  reg   0 @0x43C00000: 00000000 00000000 00000000 00000000", out)
        self.assertIn("  reg   4 @0x43C00010: 00000000 00000000", out)
        self.assertIn("mem_pcie_intr_0 reg5 @0x43C00014 = 0x00000000", out)
        self.assertIn("mem_pcie_intr_0: register 6 out of range (0..5)", out)
        self.assertIn("XIL_OUT32 0x43C00008 <= 0xCAFE0002", out)
        self.assertIn("mem_pcie_intr_0 reg2 @0x43C00008 <= 0xCAFE0002, readback 0x00000000", out)
        self.assertIn("mem_pcie_intr_0: register 9 out of range (0..5)", out)
        self.assertIn("usage: mem_pcie_intr_0 dump | read <n> | write <n> <value>", out)
        # i2c_read/i2c_write: stub yalniz 0x4A'ya ACK verir; DynRecv A0, A1 doldurur.
        self.assertIn("0x4A reg 0x00: A0 A1", out)
        self.assertIn("i2c_read 0x4B: NACK / bus error", out)
        self.assertIn("usage: i2c_read <addr> <reg> [n=1..16]", out)
        self.assertIn("i2c_write 0x4A: 2 byte(s) OK", out)
        self.assertIn("i2c_write 0x4B: NACK / bus error", out)
        # mem: okuma (stub 0), yazma + geri okuma, hizasiz adres.
        self.assertIn("0x43C00000 = 0x00000000", out)
        self.assertIn("XIL_OUT32 0x43C00004 <= 0x12345678", out)
        self.assertIn("mem: address must be 4-byte aligned", out)
        self.assertIn("| CIT kosusu #1", out)                 # cit raporu: seviye info (sdl info) -> basildi
        self.assertNotIn("| CIT kosusu #2", out)              # sdl error sonrasi rapor SUSAR (esik zorlanmaz)
        self.assertEqual(out.count("cit: "), 2)               # sonuc satiri her iki kosuda
        self.assertIn("cit: ", out)
        self.assertIn("SON sayac=2", out)                     # sistemCitRead iki kez kostu
        self.assertGreaterEqual(out.count("> "), 8)          # her satirdan sonra istem


if __name__ == "__main__":
    unittest.main()
