"""Shell katmani (outputs/<proje>/shell/): konsol UART komut kabugu - cit / i2c_search / sdl.

Kullanicinin kendi main'inde derlenir; ajanla ilgisi yoktur. Ureticinin cikti agaci,
platforma gore UART bayt erisimi, komut dagitimi ve GERCEK gcc round-trip (stub UART'tan
"help / sdl info / i2c_search / cit" satirlari beslenir, cikti stdout'tan okunur).
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from orchestrator import codegen, shell_layer

ROOT = Path(__file__).resolve().parent.parent
STUBS = ROOT / "tests" / "xilinx_stubs"


def _find_cc() -> str | None:
    return shutil.which("gcc") or shutil.which("cc")


def _axi_spec(name: str, transport: str = "uart") -> dict:
    base = json.loads((ROOT / "specs/samples/radar_io_board.spec.json").read_text(encoding="utf-8"))
    return {
        "schema_version": base.get("schema_version", "1.0"),
        "project": {"name": name, "platform": "microblaze_7series", "target_core": "microblaze_0",
                    "runtime": "bare_metal", "output_mode": "dropin", "testbench_transport": transport},
        "coding_standard_ref": "std/default.ruleset.json",
        "llm": {"enabled": False},
        "controllers": [
            {"id": "pl_i2c_0", "type": "i2c", "instance": "XPAR_AXI_IIC_0", "base_address": "0x40800000",
             "device_id": 0, "driver": "XIic", "source": "xparameters", "zone": "pl"},
            {"id": "pl_uart_0", "type": "uart", "instance": "XPAR_AXI_UARTLITE_0",
             "base_address": "0x40600000", "device_id": 0, "driver": "XUartLite",
             "source": "xparameters", "zone": "pl"},
        ],
        "muxes": [{"id": "u1_tca9548a", "part": "TCA9548A", "controller_id": "pl_i2c_0",
                   "i2c_address": "0x70", "channels": 8}],
        "devices": [
            {"id": "u3_tmp101", "part": "TMP101", "descriptor_ref": "descriptors/tmp101.yaml",
             "attach": {"controller_id": "pl_i2c_0", "i2c_address": "0x4A",
                        "via_mux": {"mux_id": "u1_tca9548a", "channel": 1}},
             "operations_requested": ["device_init", "temperature_read"], "tests_requested": ["self_test"]},
        ],
    }


def _zynqmp_spec(name: str) -> dict:
    spec = json.loads((ROOT / "specs/samples/radar_io_board.spec.json").read_text(encoding="utf-8"))
    spec["project"] = {**spec["project"], "name": name}
    return spec


def _generate(spec: dict) -> Path:
    out_dir = Path(tempfile.mkdtemp(prefix="s2c_shell_"))
    codegen.generate(spec, out_dir)
    return out_dir


def _read(out_dir: Path, rel: str) -> str:
    return (out_dir / rel).read_text(encoding="utf-8")


class ShellLayerGenerationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.out_dir = _generate(_axi_spec("unit_shell_gen"))

    @classmethod
    def tearDownClass(cls) -> None:
        shutil.rmtree(cls.out_dir, ignore_errors=True)

    def test_tree_and_no_product_names(self) -> None:
        for rel in ("shell/shell_uart.h", "shell/shell_uart.c", "shell/shell.h", "shell/shell.c", "shell/main_example.c"):
            self.assertTrue((self.out_dir / rel).is_file(), rel)
            text = _read(self.out_dir, rel).lower().replace("generated by spec2code", "")
            self.assertNotIn("spec2code", text, f"{rel} icinde urun adi")
            self.assertIn(b"\r\n", (self.out_dir / rel).read_bytes())

    def test_api_and_commands(self) -> None:
        header = _read(self.out_dir, "shell/shell.h")
        self.assertIn("void shellInit(SSistemCitBus* spBus, const SSistemCitLimit* spLimit, SSistemCit* spCit);", header)
        self.assertIn("void shellCheck(void);", header)
        source = _read(self.out_dir, "shell/shell.c")
        for command in ('"cit"', '"i2c_search"', '"sdl"', '"help"'):
            self.assertIn(f"strcmp(cpLine, {command}) == 0", source)
        # cit: INFO esigi gecici acilir, sistemCitRead kosar, esik geri alinir.
        self.assertIn("iResult = sistemCitRead(S_spBus, S_spLimit, S_spCit);", source)
        self.assertIn("(void)dbgLevelSet(DEBUG_LEVEL_INFO);", source)
        self.assertIn("(void)dbgLevelSet(uiOldLevel);", source)
        # i2c_search: AXI IIC dinamik prob, switch adresi atlanir.
        self.assertIn("XIic_DynSend(spIic->BaseAddress, (unsigned short)uiAddress, &ucProbe, 1U, XIIC_STOP)", source)
        self.assertIn("S_uiArrSwitchAddress[] = {0x70U};", source)
        self.assertIn("shellI2cProbeXIic(S_spBus->sPlI2c0, uiAddress)", source)
        # sdl: adlar ve 0..5
        for level in ("error", "warning", "msg", "info", "trace"):
            self.assertIn(f'strcmp(cpArgument, "{level}") == 0', source)
        # satir okuma bloklamaz: while (shellUartByteRead(...))
        self.assertIn("while (shellUartByteRead(&ucByte) == TRUE)", source)
        # gecmis: ESC [ A / ESC [ B, halka, ayni komut tek kayit
        self.assertIn("static char S_cArrHistory[SHELL_HISTORY_MAX][SHELL_LINE_MAX];", source)
        self.assertIn("shellHistoryAdd(S_cArrLine);", source)
        self.assertIn("if (ucByte == (unsigned char)'A')", source)
        self.assertIn("if (ucByte == (unsigned char)'B')", source)

    def test_uart_access_follows_platform(self) -> None:
        uart = _read(self.out_dir, "shell/shell_uart.c")
        self.assertIn('#include "xuartlite_l.h"', uart)
        self.assertIn("XUartLite_IsReceiveEmpty(STDIN_BASEADDRESS)", uart)
        self.assertIn("XUartLite_RecvByte(STDIN_BASEADDRESS)", uart)
        self.assertIn("XUartLite_SendByte(STDOUT_BASEADDRESS, ucByte)", uart)

    def test_main_example_wires_init_before_loop(self) -> None:
        main = _read(self.out_dir, "shell/main_example.c")
        self.assertIn("sistemCitBusVarsayilan(&S_sBus);", main)
        self.assertIn("iStatus = sistemCitInit(&S_sBus);", main)
        self.assertIn("shellInit(&S_sBus, &S_sLimit, &S_sCit);", main)
        self.assertLess(main.index("sistemCitInit("), main.index("for (;;)"))
        self.assertIn("shellCheck();", main[main.index("for (;;)"):])

    def test_readme_mentions_shell(self) -> None:
        readme = _read(self.out_dir, "README.md")
        self.assertIn("## Konsol kabugu (`shell/`)", readme)
        self.assertIn("`sdl <seviye>`", readme)


class ShellLayerPlatformTests(unittest.TestCase):
    def test_zynqmp_uses_ps_uart_and_xiicps_probe(self) -> None:
        out_dir = _generate(_zynqmp_spec("unit_shell_zynqmp"))
        try:
            uart = _read(out_dir, "shell/shell_uart.c")
            self.assertIn('#include "xuartps_hw.h"', uart)
            self.assertIn("XUartPs_IsReceiveData(STDIN_BASEADDRESS) == 0U", uart)
            source = _read(out_dir, "shell/shell.c")
            self.assertIn("XIicPs_MasterSendPolled(spIic, &ucProbe, 1, (unsigned short)uiAddress)", source)
            self.assertIn("XIicPs_BusIsBusy(spIic)", source)
        finally:
            shutil.rmtree(out_dir, ignore_errors=True)

    def test_console_uart_driver_prefers_non_mdm_uart(self) -> None:
        spec = _axi_spec("unit_shell_mdm", transport="mdm")
        spec["controllers"].append({"id": "pl_uart_1", "type": "uart", "instance": "XPAR_MDM_1",
                                    "base_address": "0x41400000", "device_id": 1, "driver": "XUartLite",
                                    "source": "xparameters", "zone": "pl", "subtype": "mdm"})
        self.assertEqual(shell_layer.console_uart_driver(spec), "XUartLite")
        self.assertEqual(shell_layer.console_uart_driver({"project": {"platform": "versal"}, "controllers": []}), "XUartPsv")


_HOST_XPARAMETERS = """#ifndef XPARAMETERS_H
#define XPARAMETERS_H
#define XPAR_XIIC_NUM_INSTANCES 1
#define XPAR_AXI_IIC_0_BASEADDR 0x40800000UL
#define XPAR_AXI_IIC_0_DEVICE_ID 0U
#define STDIN_BASEADDRESS 0x40600000UL
#define STDOUT_BASEADDRESS 0x40600000UL
#endif
"""

_HOST_MAIN = r"""
#include <stdio.h>
#include <string.h>
#include "sistem_cit.h"
#include "shell.h"
extern const unsigned char* g_ucpStubUartIn;
extern unsigned int g_uiStubUartInLen;
static SSistemCitBus S_sBus;
static const SSistemCitLimit S_sLimit = SISTEM_CIT_LIMIT_VARSAYILAN;
static SSistemCit S_sCit;
/* Son: yukari-yukari + Enter -> "sdl 9" yeniden kosar (xyz'den bir onceki); asagi-asagi -> bos satir. */
static const char S_cArrScript[] = "help\rsdl info\rsdl 9\rxyz\r\x1b[A\x1b[A\r\x1b[B\x1b[B\rsdl\ri2c_search\rcit\r";
int main(void)
{
    unsigned int uiTur;
    sistemCitBusVarsayilan(&S_sBus);
    (void)sistemCitInit(&S_sBus);
    shellInit(&S_sBus, &S_sLimit, &S_sCit);
    g_ucpStubUartIn = (const unsigned char*)S_cArrScript;
    g_uiStubUartInLen = (unsigned int)strlen(S_cArrScript);
    for (uiTur = 0U; uiTur < 4U; uiTur++)
    {
        shellCheck(); /* tum satirlar tek cagrida islenir; ekstra turlar bloklamadigini gosterir */
    }
    printf("\nSON sayac=%u\n", S_sCit.uiSayac);
    return 0;
}
"""


@unittest.skipUnless(_find_cc(), "host C compiler required")
class ShellHostRoundTripTests(unittest.TestCase):
    """drivers + cit + sim + shell gercek derleyicide; komutlar stub UART'tan beslenir."""

    def test_commands_over_stub_console(self) -> None:
        spec = _axi_spec("unit_shell_host_rt")
        for device in spec["devices"]:
            device["simulate"] = True
        out_dir = _generate(spec)
        try:
            work = out_dir / "host"
            work.mkdir()
            (work / "xparameters.h").write_text(_HOST_XPARAMETERS, encoding="utf-8")
            (work / "main.c").write_text(_HOST_MAIN, encoding="utf-8")
            binary = work / ("shell_host.exe" if os.name == "nt" else "shell_host")
            sources = [str(work / "main.c"), str(STUBS / "xilinx_stubs.c"),
                       *[str(p) for p in (out_dir / "drivers").glob("*.c")],
                       *[str(p) for p in (out_dir / "cit").glob("*.c")],
                       *[str(p) for p in (out_dir / "shell").glob("shell*.c")],
                       *[str(p) for p in (out_dir / "tests" / "sim").glob("*.c")]]
            cmd = [_find_cc(), "-std=c99", "-Wall", "-Wextra", "-Werror",
                   "-include", "spec2code_sim_xilinx.h",
                   "-I", str(work), "-I", str(STUBS), "-I", str(out_dir / "drivers"),
                   "-I", str(out_dir / "cit"), "-I", str(out_dir / "shell"), "-I", str(out_dir / "tests" / "sim"),
                   "-o", str(binary), *sources]
            build = subprocess.run(cmd, capture_output=True, text=True)
            self.assertEqual(build.returncode, 0, build.stderr)
            run = subprocess.run([str(binary)], capture_output=True, text=True)
            self.assertEqual(run.returncode, 0, run.stderr)
            out = run.stdout
        finally:
            shutil.rmtree(out_dir, ignore_errors=True)
        self.assertIn("komut kabugu hazir (help)", out)
        self.assertIn("komutlar:", out)                       # help
        self.assertIn("log seviyesi: info (4)", out)          # sdl info
        self.assertEqual(out.count("sdl: gecersiz seviye '9'"), 2)  # sdl 9 + gecmisten (yukari x2) tekrar
        self.assertIn("bilinmeyen komut: xyz (help)", out)    # xyz
        self.assertIn("pl_i2c_0: tarama 0x08..0x77", out)     # i2c_search
        self.assertIn("0x70  (I2C switch, atlandi)", out)
        self.assertIn("pl_i2c_0: 0 cihaz", out)               # stub hatta ACK yok (sanal cihaz sim'de, probu gormez)
        self.assertIn("| CIT kosusu #1", out)                 # cit raporu INFO'da basildi
        self.assertIn("cit: ", out)
        self.assertIn("SON sayac=1", out)                     # sistemCitRead bir kez kostu
        self.assertGreaterEqual(out.count("> "), 8)          # her satirdan sonra istem


if __name__ == "__main__":
    unittest.main()
