"""Kart kontrol GPIO'su (``board_control``): dual-channel AXI GPIO uzerinden reset / lock pinleri.

Sirketteki kartlarda tek bir AXI GPIO'nun 1. kanali cikis (AFE reset, JESD cekirdek fiziksel resetleri,
saat/PLL resetleri, LMX/LMK kontrol), 2. kanali giris (GT PLL lock'lari, durum LED'leri) olarak kullanilir.
Bit yerlesimi karttan karta degistigi icin spec'ten (arayuzdeki tablo) gelir; kod bit ADLARIYLA uretilir.

Roller (``role``):
  afe_reset            AFE reset pini (acilista reset'te tutulur, bring-up'tan hemen once kaldirilir)
  jesd_rx_core_reset   JESD204C RX cekirdeginin fiziksel reset pini (register RESET'ten bagimsiz)
  jesd_tx_core_reset   JESD204C TX cekirdeginin fiziksel reset pini
  pll_reset            GT HSCLK/LCPLL reset pini (bu surumde yalniz pasif seviyeye yazilir)
  pll_lock             GT PLL lock girisi (LCPLL/QPLL); 1 beklenir, 0 ise akis durmaz, sonuc sozcugunde gorunur
  sysref               SYSREF darbesi cikisi (varsa jesdlink SYSREF'i buradan surer)
  generic              dokunulmaz (LMX/LMK vb.; ileride)

Uretilen dosyalar: drivers/ip/boardctl.h/.c. Kullanicilar: jesdlink (fiziksel reset, SYSREF, lock durumu),
AFE7900 surucusu (AFE reset kaldirma).
"""

from __future__ import annotations

from pathlib import Path
from typing import Callable

ROLES = ("afe_reset", "jesd_rx_core_reset", "jesd_tx_core_reset", "pll_reset", "pll_lock", "sysref", "generic")
_ROLE_ENUM = {r: "BOARDCTL_ROLE_" + r.upper() for r in ROLES}
DEFAULT_JESD_RESET_MS = 100
AFE_RESET_HOLD_MS = 10


def board_control(spec: dict) -> dict | None:
    """Spec'teki board_control'u normalize eder: {gpio_id, base, jesd_reset_ms, bits:[...]} ya da None.

    GPIO denetleyicisi controllers[] icinde bulunamazsa ya da bit listesi bossa None (modul uretilmez).
    """
    raw = spec.get("board_control") or {}
    gpio_id = str(raw.get("gpio_id") or "").strip()
    bits_raw = raw.get("bits") or []
    if not gpio_id or not bits_raw:
        return None
    base = 0
    for c in spec.get("controllers", []) or []:
        if str(c.get("id", "")) == gpio_id:
            try:
                base = int(str(c.get("base_address")), 0)
            except (TypeError, ValueError):
                base = 0
            break
    if base == 0:
        return None
    bits: list[dict] = []
    for item in bits_raw:
        role = str(item.get("role") or "generic")
        if role not in ROLES:
            role = "generic"
        try:
            bit = int(item.get("bit", 0))
            channel = int(item.get("channel", 1))
        except (TypeError, ValueError):
            continue
        if not (0 <= bit <= 31) or channel not in (1, 2):
            continue
        name = str(item.get("name") or f"{role}_{channel}_{bit}")
        bits.append({"name": name, "channel": channel, "bit": bit, "role": role,
                     "active_low": bool(item.get("active_low", False)),
                     "target": str(item.get("target") or "")})
    if not bits:
        return None
    try:
        reset_ms = int(raw.get("jesd_reset_ms", DEFAULT_JESD_RESET_MS) or DEFAULT_JESD_RESET_MS)
    except (TypeError, ValueError):
        reset_ms = DEFAULT_JESD_RESET_MS
    return {"gpio_id": gpio_id, "base": base, "jesd_reset_ms": max(1, reset_ms), "bits": bits}


def has_role(board: dict | None, role: str) -> bool:
    return bool(board) and any(b["role"] == role for b in board["bits"])


def has_jesd_reset(board: dict | None) -> bool:
    return has_role(board, "jesd_rx_core_reset") or has_role(board, "jesd_tx_core_reset")


def write_boardctl(spec: dict, out_dir: Path, write_output: Callable[[Path, str], Path],
                   style: Callable[[str], str]) -> list[str]:
    board = board_control(spec)
    if board is None:
        return []
    ip_dir = out_dir / "drivers" / "ip"
    return [str(write_output(ip_dir / "boardctl.h", style(_header(board)))),
            str(write_output(ip_dir / "boardctl.c", style(_source(board))))]


def _c_str(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _header(board: dict) -> str:
    bits = board["bits"]
    locks = [b for b in bits if b["role"] == "pll_lock"]
    lines = [
        "/**",
        " * @file boardctl.h",
        f" * @brief Kart kontrol GPIO'su ({board['gpio_id']}, dual-channel AXI GPIO): kanal 1 cikis (reset/kontrol),",
        " *        kanal 2 giris (PLL lock / durum). Bit yerlesimi spec board_control'den; adlar kartin sematigindeki adlardir.",
        " *",
        " * Acilis sirasi: boardCtlInit (AFE reset'te, digerleri pasif) -> JESD cekirdek fiziksel reset darbesi",
        " * (BOARDCTL_JESD_RESET_MS) -> AFE reset kaldirma (bring-up'tan hemen once) -> register-map JESD reset akisi",
        " * -> PLL lock kontrolu (1 beklenir; 0 akisi durdurmaz, durum sozcugunde raporlanir).",
        " *",
        " * Generated by Spec2Code.",
        " */",
        "#ifndef BOARDCTL_H",
        "#define BOARDCTL_H",
        "",
        '#include "xil_types.h"',
        "",
        f"#define BOARDCTL_GPIO_BASE 0x{board['base']:08X}U /* {board['gpio_id']} */",
        "#define BOARDCTL_OUT_CHANNEL 1U /* AXI GPIO kanal 1: DATA 0x0, TRI 0x4 */",
        "#define BOARDCTL_IN_CHANNEL 2U  /* AXI GPIO kanal 2: DATA 0x8, TRI 0xC */",
        f"#define BOARDCTL_JESD_RESET_MS {board['jesd_reset_ms']}U /* JESD cekirdek fiziksel reset darbesi */",
        f"#define BOARDCTL_AFE_RESET_HOLD_MS {AFE_RESET_HOLD_MS}U /* AFE reset kaldirmadan once en az bu kadar reset'te */",
        f"#define BOARDCTL_BIT_COUNT {len(bits)}U",
        f"#define BOARDCTL_PLL_LOCK_COUNT {len(locks)}U",
        "",
        "typedef enum",
        "{",
    ]
    for index, role in enumerate(ROLES):
        lines.append(f"    {_ROLE_ENUM[role]} = {index}," if index < len(ROLES) - 1 else f"    {_ROLE_ENUM[role]} = {index}")
    lines += [
        "} EBoardCtlRole;",
        "",
        "typedef struct",
        "{",
        "    const char* cpName;      /* sematikteki pin adi */",
        "    unsigned int uiChannel;  /* 1 cikis, 2 giris */",
        "    unsigned int uiMask;     /* 1U << bit */",
        "    EBoardCtlRole eRole;",
        "    unsigned int uiActiveLow; /* TRUE: 0 = aktif (reset verildi / lock var) */",
        "    const char* cpTarget;    /* hedef (AFE cihaz id'si ya da JESD IP id'si), bos = hepsi */",
        "} SBoardCtlBit;",
        "",
        "/* Bir kez: yonler (kanal 1 cikis, kanal 2 giris) ve acilis seviyeleri (AFE reset'te, digerleri pasif). Idempotent. */",
        "void boardCtlInit(void);",
        "/* Rol + hedef ile cikis bitlerini surer (uiAssert TRUE = aktif seviye). Hedef eslesmezse rolun tum bitleri.",
        " * Rol icin cikis biti yoksa XST_FAILURE (loglar, akis durmaz). */",
        "int boardCtlRoleWrite(EBoardCtlRole eRole, const char* cpTarget, unsigned int uiAssert);",
    ]
    if has_jesd_reset(board):
        lines.append("/* JESD RX+TX cekirdek fiziksel reset darbesi: ver -> BOARDCTL_JESD_RESET_MS -> kaldir. */")
        lines.append("int boardCtlJesdCoreResetPulse(void);")
    if has_role(board, "sysref"):
        lines.append("/* SYSREF cikis biti: 1 -> 10 us -> 0. */")
        lines.append("void boardCtlSysrefPulse(void);")
    if locks:
        lines.append("/* Giris kanalindaki PLL lock bitlerini okur, her birini loglar; hepsi lock ise TRUE. */")
        lines.append("unsigned int boardCtlPllLocksRead(void);")
    lines += ["", "#endif /* BOARDCTL_H */"]
    return "\n".join(lines) + "\n"


def _source(board: dict) -> str:
    bits = board["bits"]
    locks = [b for b in bits if b["role"] == "pll_lock"]
    lines = [
        "/**",
        " * @file boardctl.c",
        f" * @brief Kart kontrol GPIO'su ({board['gpio_id']} @0x{board['base']:08X}). Generated by Spec2Code.",
        " */",
        '#include "boardctl.h"',
        '#include "dbg_printf.h"',
        '#include "sleep.h"',
        '#include "xil_io.h"',
        '#include "xstatus.h"',
        "#include <stddef.h>",
        "#include <string.h>",
        "",
        "#define BOARDCTL_REG_OUT_DATA 0x0U",
        "#define BOARDCTL_REG_OUT_TRI 0x4U",
        "#define BOARDCTL_REG_IN_DATA 0x8U",
        "#define BOARDCTL_REG_IN_TRI 0xCU",
        "",
        "/* Bit tablosu: spec board_control (ad, kanal, maske, rol, aktif seviye, hedef). */",
        "static const SBoardCtlBit S_sArrBit[BOARDCTL_BIT_COUNT] = {",
    ]
    for b in bits:
        lines.append(f'    {{"{_c_str(b["name"])}", {b["channel"]}U, 0x{1 << b["bit"]:08X}U, {_ROLE_ENUM[b["role"]]}, '
                     f'{"TRUE" if b["active_low"] else "FALSE"}, "{_c_str(b["target"])}"}},')
    lines += [
        "};",
        "static unsigned int S_uiOutShadow = 0U; /* cikis kanalinin son yazilan degeri (bit bit surmek icin) */",
        "static unsigned int S_uiReady = FALSE;",
        "",
        "/* Rolun mantiksal durumu (aktif/pasif) -> pin seviyesi. */",
        "static unsigned int boardCtlLevel(const SBoardCtlBit* spBit, unsigned int uiAssert)",
        "{",
        "    if (uiAssert == TRUE)",
        "    {",
        "        return (spBit->uiActiveLow == TRUE) ? 0U : 1U;",
        "    }",
        "    return (spBit->uiActiveLow == TRUE) ? 1U : 0U;",
        "}",
        "",
        "static void boardCtlShadowSet(const SBoardCtlBit* spBit, unsigned int uiAssert)",
        "{",
        "    if (boardCtlLevel(spBit, uiAssert) == 1U)",
        "    {",
        "        S_uiOutShadow |= spBit->uiMask;",
        "    }",
        "    else",
        "    {",
        "        S_uiOutShadow &= ~spBit->uiMask;",
        "    }",
        "}",
        "",
        "static void boardCtlOutWrite(void)",
        "{",
        "    Xil_Out32((UINTPTR)BOARDCTL_GPIO_BASE + BOARDCTL_REG_OUT_DATA, (u32)S_uiOutShadow);",
        "}",
        "",
        "void boardCtlInit(void)",
        "{",
        "    unsigned int uiIndex;",
        "",
        "    if (S_uiReady == TRUE)",
        "    {",
        "        return;",
        "    }",
        "    S_uiReady = TRUE;",
        "    /* Giris kanali: TRI=1 (giris). Cikis kanali: once seviyeler, sonra TRI=0 (cikis) - glitch'siz. */",
        "    Xil_Out32((UINTPTR)BOARDCTL_GPIO_BASE + BOARDCTL_REG_IN_TRI, 0xFFFFFFFFU);",
        "    S_uiOutShadow = 0U;",
        "    for (uiIndex = 0U; uiIndex < BOARDCTL_BIT_COUNT; uiIndex++)",
        "    {",
        "        if (S_sArrBit[uiIndex].uiChannel == BOARDCTL_OUT_CHANNEL)",
        "        {",
        "            /* AFE acilista reset'te tutulur (bring-up'tan hemen once kaldirilir); diger roller pasif. */",
        "            boardCtlShadowSet(&S_sArrBit[uiIndex], (S_sArrBit[uiIndex].eRole == BOARDCTL_ROLE_AFE_RESET) ? TRUE : FALSE);",
        "        }",
        "    }",
        "    boardCtlOutWrite();",
        "    Xil_Out32((UINTPTR)BOARDCTL_GPIO_BASE + BOARDCTL_REG_OUT_TRI, 0U);",
        '    dbg_printf(DEBUG_LEVEL_INFO, "kart GPIO: cikislar 0x%08X (AFE reset\'te, JESD/PLL resetleri pasif)", S_uiOutShadow);',
        "}",
        "",
        "int boardCtlRoleWrite(EBoardCtlRole eRole, const char* cpTarget, unsigned int uiAssert)",
        "{",
        "    unsigned int uiIndex;",
        "    unsigned int uiExact = 0U;",
        "    unsigned int uiApplied = 0U;",
        "",
        "    boardCtlInit();",
        "    /* Hedef adi tabloda birebir varsa yalniz o bit(ler); yoksa rolun tum bitleri (tek AFE'li kartta ad farki sorun olmasin). */",
        "    for (uiIndex = 0U; uiIndex < BOARDCTL_BIT_COUNT; uiIndex++)",
        "    {",
        "        if ((S_sArrBit[uiIndex].eRole == eRole) && (cpTarget != NULL) && (strcmp(S_sArrBit[uiIndex].cpTarget, cpTarget) == 0))",
        "        {",
        "            uiExact++;",
        "        }",
        "    }",
        "    for (uiIndex = 0U; uiIndex < BOARDCTL_BIT_COUNT; uiIndex++)",
        "    {",
        "        if ((S_sArrBit[uiIndex].eRole != eRole) || (S_sArrBit[uiIndex].uiChannel != BOARDCTL_OUT_CHANNEL))",
        "        {",
        "            continue;",
        "        }",
        "        if ((uiExact != 0U) && (strcmp(S_sArrBit[uiIndex].cpTarget, cpTarget) != 0))",
        "        {",
        "            continue;",
        "        }",
        "        boardCtlShadowSet(&S_sArrBit[uiIndex], uiAssert);",
        '        dbg_printf(DEBUG_LEVEL_INFO, "kart GPIO: %s <= %s", S_sArrBit[uiIndex].cpName, (uiAssert == TRUE) ? "AKTIF" : "pasif");',
        "        uiApplied++;",
        "    }",
        "    if (uiApplied == 0U)",
        "    {",
        '        dbg_printf(DEBUG_LEVEL_ERROR, "kart GPIO: rol %u icin cikis biti tanimli degil", (unsigned int)eRole);',
        "        return XST_FAILURE;",
        "    }",
        "    boardCtlOutWrite();",
        "    return XST_SUCCESS;",
        "}",
    ]
    if has_jesd_reset(board):
        lines += [
            "",
            "int boardCtlJesdCoreResetPulse(void)",
            "{",
            "    int iRx;",
            "    int iTx;",
            "",
            "    boardCtlInit();",
            "    iRx = boardCtlRoleWrite(BOARDCTL_ROLE_JESD_RX_CORE_RESET, NULL, TRUE);",
            "    iTx = boardCtlRoleWrite(BOARDCTL_ROLE_JESD_TX_CORE_RESET, NULL, TRUE);",
            "    if ((iRx != XST_SUCCESS) && (iTx != XST_SUCCESS))",
            "    {",
            "        return XST_FAILURE;",
            "    }",
            "    usleep(BOARDCTL_JESD_RESET_MS * 1000U);",
            "    (void)boardCtlRoleWrite(BOARDCTL_ROLE_JESD_RX_CORE_RESET, NULL, FALSE);",
            "    (void)boardCtlRoleWrite(BOARDCTL_ROLE_JESD_TX_CORE_RESET, NULL, FALSE);",
            '    dbg_printf(DEBUG_LEVEL_INFO, "kart GPIO: JESD cekirdek fiziksel reset darbesi %u ms", (unsigned int)BOARDCTL_JESD_RESET_MS);',
            "    return XST_SUCCESS;",
            "}",
        ]
    if has_role(board, "sysref"):
        lines += [
            "",
            "void boardCtlSysrefPulse(void)",
            "{",
            "    (void)boardCtlRoleWrite(BOARDCTL_ROLE_SYSREF, NULL, TRUE);",
            "    usleep(10U);",
            "    (void)boardCtlRoleWrite(BOARDCTL_ROLE_SYSREF, NULL, FALSE);",
            "}",
        ]
    if locks:
        lines += [
            "",
            "unsigned int boardCtlPllLocksRead(void)",
            "{",
            "    unsigned int uiIndex;",
            "    unsigned int uiInputs;",
            "    unsigned int uiLevel;",
            "    unsigned int uiLocked = 0U;",
            "",
            "    boardCtlInit();",
            "    uiInputs = (unsigned int)Xil_In32((UINTPTR)BOARDCTL_GPIO_BASE + BOARDCTL_REG_IN_DATA);",
            "    for (uiIndex = 0U; uiIndex < BOARDCTL_BIT_COUNT; uiIndex++)",
            "    {",
            "        if ((S_sArrBit[uiIndex].eRole != BOARDCTL_ROLE_PLL_LOCK) || (S_sArrBit[uiIndex].uiChannel != BOARDCTL_IN_CHANNEL))",
            "        {",
            "            continue;",
            "        }",
            "        uiLevel = ((uiInputs & S_sArrBit[uiIndex].uiMask) != 0U) ? 1U : 0U;",
            "        if (uiLevel == boardCtlLevel(&S_sArrBit[uiIndex], TRUE))",
            "        {",
            "            uiLocked++;",
            '            dbg_printf(DEBUG_LEVEL_INFO, "kart GPIO: %s LOCK", S_sArrBit[uiIndex].cpName);',
            "        }",
            "        else",
            "        {",
            '            dbg_printf(DEBUG_LEVEL_ERROR, "kart GPIO: %s UNLOCK", S_sArrBit[uiIndex].cpName);',
            "        }",
            "    }",
            '    dbg_printf(DEBUG_LEVEL_INFO, "kart GPIO: PLL lock %u/%u (girisler 0x%08X)", uiLocked, (unsigned int)BOARDCTL_PLL_LOCK_COUNT, uiInputs);',
            "    return (uiLocked == BOARDCTL_PLL_LOCK_COUNT) ? TRUE : FALSE;",
            "}",
        ]
    return "\n".join(lines) + "\n"
