"""CIT simulasyon katmani: descriptor'dan uretilen sanal I2C cihazlari (cit/sim/).

Her I2C register cihazi icin ``<mod>_sim.h/.c`` uretilir: register dosyasi
(reset degerleri, genislik ve yazilabilirlik tablolari descriptor'dan), pointer +
otomatik artis ile bayt bayt okuma/yazma, hata enjeksiyonu (NACK, hazir biti hic
gelmez) ve entegreye ozel DAVRANIS bloklari (``_BEHAVIOR`` tablosu: LTC2991 icin
READY bit dinamigi + hedef mV/santi-C'den dönüşüm kodlari).

Sanal cihaz HAL'e ``spec2codeI2cSimEkle`` ile takilir; adres eslesirse cevabi
simulator verir, eslesmezse transfer gercek donanima gider (karisik mod).
"""

from __future__ import annotations

from typing import Callable

from orchestrator.cit_layer import _E, _ChipPlan, _hex, _pascal

SIM_HATA_YOK = "SPEC2CODE_SIM_HATA_YOK"
SIM_HATA_NACK = "SPEC2CODE_SIM_HATA_NACK"
SIM_HATA_HAZIR_YOK = "SPEC2CODE_SIM_HATA_HAZIR_YOK"


def sim_plans(plans: list[_ChipPlan]) -> list[_ChipPlan]:
    """Simulatoru uretilen cihazlar: I2C register cihazlari + SPI TICS-register cihazlari."""
    return [p for p in plans if p.transport in {"i2c", "spi"}]


def _reg_table(plan: _ChipPlan) -> tuple[int, int, list[tuple[int, int, int, int, str]]]:
    """(register sayisi, en genis bayt, [(offset, bayt, yazilabilir, reset, ad)])."""
    rows: list[tuple[int, int, int, int, str]] = []
    max_off = 0
    max_bytes = 1
    for rg in plan.descriptor.get("registers", []):
        off = int(rg.get("offset", 0))
        width = int(rg.get("width", 8) or 8)
        if width > 32 or off > 255:
            continue
        nbytes = max(1, (width + 7) // 8)
        access = str(rg.get("access", "rw")).lower()
        writable = 1 if "w" in access else 0
        reset = int(rg.get("reset", 0) or 0)
        rows.append((off, nbytes, writable, reset, str(rg.get("name", ""))))
        max_off = max(max_off, off)
        max_bytes = max(max_bytes, nbytes)
    return max_off + 1, max_bytes, rows


# --- entegreye ozel davranis bloklari -----------------------------------------------

def _ltc2991_state(e: _E) -> None:
    e.ln("    int iArrKanalMv[8];    /* hedef V1..V8 (mV; tek uclu kod uretir)        */")
    e.ln("    int iSicaklikSantiC;   /* hedef dahili sicaklik (0.01 C)                */")
    e.ln("    int iVccMv;            /* hedef VCC (mV)                                */")
    e.ln("    unsigned int uiTetik;  /* tek-atis tetik bekliyor (STATUS_HIGH yazildi) */")


def _ltc2991_api_header(e: _E, mod: str, pas: str, module: str) -> None:
    e.ln("/**")
    e.ln(" * @brief Hedef kanal gerilimi (mV); bir sonraki donusumde V kodu buna gore uretilir.")
    e.ln(" * @param spSim Simulator.")
    e.ln(" * @param ucKanal 0..7 (V1..V8).")
    e.ln(" * @param iMv Gerilim (mV, 0..4999 tek uclu araligi).")
    e.ln(" */")
    e.ln(f"void {module}SimKanalAyarla(S{pas}Sim* spSim, unsigned char ucKanal, int iMv);")
    e.blank()
    e.ln("/**")
    e.ln(" * @brief Hedef dahili sicaklik (santi-C, ornek 2537 = 25.37 C).")
    e.ln(" * @param spSim Simulator.")
    e.ln(" * @param iSantiC Sicaklik.")
    e.ln(" */")
    e.ln(f"void {module}SimSicaklikAyarla(S{pas}Sim* spSim, int iSantiC);")
    e.blank()
    e.ln("/**")
    e.ln(" * @brief Hedef VCC (mV; kod = (VCC - 2500) / 0.30518).")
    e.ln(" * @param spSim Simulator.")
    e.ln(" * @param iMv VCC.")
    e.ln(" */")
    e.ln(f"void {module}SimVccAyarla(S{pas}Sim* spSim, int iMv);")
    e.blank()
    _ = mod


def _ltc2991_behavior(e: _E, mod: str, pas: str, module: str) -> None:
    """Davranis: donusum tiki (READY kurma + kod uretimi), LSB okununca READY temizleme,
    STATUS_HIGH yaziminda salt okunur bitlerin korunmasi + tek-atis tetik."""
    e.ln(f"void {module}SimKanalAyarla(S{pas}Sim* spSim, unsigned char ucKanal, int iMv)")
    e.ln("{")
    e.ln("    if ((spSim != (S" + pas + "Sim*)0) && (ucKanal < 8U))")
    e.ln("    {")
    e.ln("        spSim->iArrKanalMv[ucKanal] = iMv;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln(f"void {module}SimSicaklikAyarla(S{pas}Sim* spSim, int iSantiC)")
    e.ln("{")
    e.ln("    if (spSim != (S" + pas + "Sim*)0)")
    e.ln("    {")
    e.ln("        spSim->iSicaklikSantiC = iSantiC;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln(f"void {module}SimVccAyarla(S{pas}Sim* spSim, int iMv)")
    e.ln("{")
    e.ln("    if (spSim != (S" + pas + "Sim*)0)")
    e.ln("    {")
    e.ln("        spSim->iVccMv = iMv;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("/* Tek uclu gerilim kodu: LSB 305.18 uV, 14 bit + isaret, DV biti MSB bit 7. */")
    e.ln(f"static void {module}SimKodYaz(S{pas}Sim* spSim, unsigned char ucMsbReg, int iKod,")
    e.ln("                             unsigned char ucMsbMaske)")
    e.ln("{")
    e.ln("    spSim->ucArrReg[ucMsbReg][0] = (unsigned char)(0x80U | (((unsigned int)iKod >> 8U) & ucMsbMaske));")
    e.ln("    spSim->ucArrReg[ucMsbReg + 1U][0] = (unsigned char)((unsigned int)iKod & 0xFFU);")
    e.ln("}")
    e.blank()
    e.ln("/* Donusum tiki: her okuma islemi oncesi. Repeated Acquisition (0x08 bit 4) ya da")
    e.ln(" * bekleyen tek-atis tetigi varsa etkin kanallarin kodlari uretilir ve READY bitleri")
    e.ln(" * kurulur (2991f: READY, ilgili veri registeri okununca temizlenir). */")
    e.ln(f"static void {module}SimOncesiOku(S{pas}Sim* spSim)")
    e.ln("{")
    e.ln("    unsigned char ucEnable = spSim->ucArrReg[0x01U][0];")
    e.ln("    unsigned int uiTekrar = ((unsigned int)spSim->ucArrReg[0x08U][0] >> 4U) & 0x1U;")
    e.ln("    unsigned char ucCift;")
    e.ln("    int iKod;")
    e.blank()
    e.ln("    if (spSim->uiHataModu == SPEC2CODE_SIM_HATA_HAZIR_YOK)")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[0x00U][0] = 0U;")
    e.ln("        spSim->ucArrReg[0x01U][0] = (unsigned char)(ucEnable & 0xF8U);")
    e.ln("        return;")
    e.ln("    }")
    e.ln("    if ((uiTekrar == 0U) && (spSim->uiTetik == 0U))")
    e.ln("    {")
    e.ln("        return;")
    e.ln("    }")
    e.ln("    spSim->uiTetik = 0U;")
    e.ln("    for (ucCift = 0U; ucCift < 4U; ucCift++)")
    e.ln("    {")
    e.ln("        if (((ucEnable >> (4U + ucCift)) & 0x1U) == 0U)")
    e.ln("        {")
    e.ln("            continue;")
    e.ln("        }")
    e.ln("        iKod = (spSim->iArrKanalMv[2U * ucCift] * 100000) / 30518;")
    e.ln("        if (iKod < 0)")
    e.ln("        {")
    e.ln("            iKod = 0;")
    e.ln("        }")
    e.ln(f"        {module}SimKodYaz(spSim, (unsigned char)(0x0AU + (4U * ucCift)), iKod, 0x3FU);")
    e.ln("        iKod = (spSim->iArrKanalMv[(2U * ucCift) + 1U] * 100000) / 30518;")
    e.ln("        if (iKod < 0)")
    e.ln("        {")
    e.ln("            iKod = 0;")
    e.ln("        }")
    e.ln(f"        {module}SimKodYaz(spSim, (unsigned char)(0x0CU + (4U * ucCift)), iKod, 0x3FU);")
    e.ln("        spSim->ucArrReg[0x00U][0] |= (unsigned char)(0x3U << (2U * ucCift));")
    e.ln("    }")
    e.ln("    if (((ucEnable >> 3U) & 0x1U) != 0U)")
    e.ln("    {")
    e.ln("        /* T_internal: LSB 0.0625 C, 13 bit ikili tumleyen (negatif -> +8192). */")
    e.ln("        iKod = (spSim->iSicaklikSantiC * 4) / 25;")
    e.ln("        if (iKod < 0)")
    e.ln("        {")
    e.ln("            iKod += 8192;")
    e.ln("        }")
    e.ln(f"        {module}SimKodYaz(spSim, 0x1AU, iKod, 0x1FU);")
    e.ln("        iKod = ((spSim->iVccMv - 2500) * 100000) / 30518;")
    e.ln("        if (iKod < 0)")
    e.ln("        {")
    e.ln("            iKod = 0;")
    e.ln("        }")
    e.ln(f"        {module}SimKodYaz(spSim, 0x1CU, iKod, 0x3FU);")
    e.ln("        spSim->ucArrReg[0x01U][0] |= 0x03U; /* VCC_READY + T_INTERNAL_READY */")
    e.ln("    }")
    e.ln("    spSim->ucArrReg[0x01U][0] &= (unsigned char)~0x04U; /* BUSY = 0 */")
    e.ln("}")
    e.blank()
    e.ln("/* Veri registerinin LSB'si okununca o kanalin READY biti temizlenir. */")
    e.ln(f"static void {module}SimSonrasiOku(S{pas}Sim* spSim, unsigned char ucReg)")
    e.ln("{")
    e.ln("    if ((ucReg >= 0x0BU) && (ucReg <= 0x19U) && ((ucReg & 0x1U) != 0U))")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[0x00U][0] &= (unsigned char)~(1U << ((ucReg - 0x0BU) / 2U));")
    e.ln("    }")
    e.ln("    else if (ucReg == 0x1BU)")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[0x01U][0] &= (unsigned char)~0x02U;")
    e.ln("    }")
    e.ln("    else if (ucReg == 0x1DU)")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[0x01U][0] &= (unsigned char)~0x01U;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("/* STATUS_HIGH'in READY/BUSY bitleri salt okunur; yazim tek-atis tetigi sayilir. */")
    e.ln(f"static void {module}SimSonrasiYaz(S{pas}Sim* spSim, unsigned char ucReg, unsigned char ucEski)")
    e.ln("{")
    e.ln("    if (ucReg == 0x01U)")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[0x01U][0] = (unsigned char)((spSim->ucArrReg[0x01U][0] & 0xF8U) | (ucEski & 0x07U));")
    e.ln("        spSim->uiTetik = 1U;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    _ = mod


def _ltc2991_kur(e: _E) -> None:
    e.ln("    for (uiIndex = 0U; uiIndex < 8U; uiIndex++)")
    e.ln("    {")
    e.ln("        spSim->iArrKanalMv[uiIndex] = 3300;")
    e.ln("    }")
    e.ln("    spSim->iSicaklikSantiC = 2500;")
    e.ln("    spSim->iVccMv = 3300;")
    e.ln("    spSim->uiTetik = 0U;")


# --- LTC2945: guc monitoru ---------------------------------------------------------------

def _ltc2945_state(e: _E) -> None:
    e.ln("    int iSenseUv;  /* hedef sont gerilimi (uV; LSB 25 uV, 12 bit)            */")
    e.ln("    int iVinMv;    /* hedef VIN (mV; LSB 25 mV, 12 bit)                      */")
    e.ln("    int iAdinUv;   /* hedef ADIN (uV; LSB 500 uV, 12 bit)                    */")


def _ltc2945_api_header(e: _E, mod: str, pas: str, module: str) -> None:
    for name, param, doc in (
        ("SenseAyarla", "int iUv", "Hedef sont (delta-sense) gerilimi, uV. Kod = uV / 25."),
        ("VinAyarla", "int iMv", "Hedef VIN, mV. Kod = mV / 25."),
        ("AdinAyarla", "int iUv", "Hedef ADIN, uV. Kod = uV / 500."),
    ):
        e.ln("/**")
        e.ln(f" * @brief {doc}")
        e.ln(" * @param spSim Simulator.")
        e.ln(f" * @param {param.split()[1]} Deger.")
        e.ln(" */")
        e.ln(f"void {module}Sim{name}(S{pas}Sim* spSim, {param});")
        e.blank()
    e.ln("/**")
    e.ln(" * @brief Hedef akimi sont direnciyle sont gerilimine cevirir (uV = mA * mohm).")
    e.ln(" * @param spSim Simulator.")
    e.ln(" * @param iMa Akim (mA).")
    e.ln(" * @param iRsenseMohm Sont direnci (miliohm; spec device.config.sense_resistor_mohms).")
    e.ln(" */")
    e.ln(f"void {module}SimAkimAyarla(S{pas}Sim* spSim, int iMa, int iRsenseMohm);")
    e.blank()
    _ = mod


def _ltc2945_behavior(e: _E, mod: str, pas: str, module: str) -> None:
    for name, param, field in (("SenseAyarla", "int iUv", "iSenseUv"), ("VinAyarla", "int iMv", "iVinMv"),
                               ("AdinAyarla", "int iUv", "iAdinUv")):
        e.ln(f"void {module}Sim{name}(S{pas}Sim* spSim, {param})")
        e.ln("{")
        e.ln(f"    if (spSim != (S{pas}Sim*)0)")
        e.ln("    {")
        e.ln(f"        spSim->{field} = {param.split()[1]};")
        e.ln("    }")
        e.ln("}")
        e.blank()
    e.ln(f"void {module}SimAkimAyarla(S{pas}Sim* spSim, int iMa, int iRsenseMohm)")
    e.ln("{")
    e.ln(f"    if (spSim != (S{pas}Sim*)0)")
    e.ln("    {")
    e.ln("        spSim->iSenseUv = iMa * iRsenseMohm;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("/* 12-bit kod D15..D4'e yazilir (MSB = kod >> 4, LSB = kod << 4). */")
    e.ln(f"static void {module}Sim12BitYaz(S{pas}Sim* spSim, unsigned char ucMsbReg, int iKod)")
    e.ln("{")
    e.ln("    if (iKod < 0)")
    e.ln("    {")
    e.ln("        iKod = 0;")
    e.ln("    }")
    e.ln("    if (iKod > 4095)")
    e.ln("    {")
    e.ln("        iKod = 4095;")
    e.ln("    }")
    e.ln("    spSim->ucArrReg[ucMsbReg][0] = (unsigned char)(((unsigned int)iKod >> 4U) & 0xFFU);")
    e.ln("    spSim->ucArrReg[ucMsbReg + 1U][0] = (unsigned char)(((unsigned int)iKod & 0xFU) << 4U);")
    e.ln("}")
    e.blank()
    e.ln("/* Okunan 12-bit kod (D15..D4). */")
    e.ln(f"static int {module}Sim12BitOku(const S{pas}Sim* spSim, unsigned char ucMsbReg)")
    e.ln("{")
    e.ln("    return (int)((((unsigned int)spSim->ucArrReg[ucMsbReg][0] << 8U) |")
    e.ln("                  (unsigned int)spSim->ucArrReg[ucMsbReg + 1U][0]) >> 4U);")
    e.ln("}")
    e.blank()
    e.ln("/* MAX/MIN izleme registerleri (datasheet: her donusumde guncellenir). */")
    e.ln(f"static void {module}SimMaxMin(S{pas}Sim* spSim, unsigned char ucMaxReg, unsigned char ucMinReg, int iKod)")
    e.ln("{")
    e.ln(f"    if (iKod > {module}Sim12BitOku(spSim, ucMaxReg))")
    e.ln("    {")
    e.ln(f"        {module}Sim12BitYaz(spSim, ucMaxReg, iKod);")
    e.ln("    }")
    e.ln(f"    if (iKod < {module}Sim12BitOku(spSim, ucMinReg))")
    e.ln("    {")
    e.ln(f"        {module}Sim12BitYaz(spSim, ucMinReg, iKod);")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("/* Donusum tiki: SHUTDOWN (CONTROL bit 1) degilse SENSE/VIN/ADIN kodlari ve 24-bit guc")
    e.ln(" * carpimi (sense_kod x vin_kod) uretilir, ADC_BUSY temizlenir, MAX/MIN izlenir. */")
    e.ln(f"static void {module}SimOncesiOku(S{pas}Sim* spSim)")
    e.ln("{")
    e.ln("    int iSense;")
    e.ln("    int iVin;")
    e.ln("    unsigned int uiGuc;")
    e.blank()
    e.ln("    if (spSim->uiHataModu == SPEC2CODE_SIM_HATA_HAZIR_YOK)")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[0x00U][0] |= 0x08U; /* ADC_BUSY takili kalir */")
    e.ln("        return;")
    e.ln("    }")
    e.ln("    if ((spSim->ucArrReg[0x00U][0] & 0x02U) != 0U)")
    e.ln("    {")
    e.ln("        return; /* SHUTDOWN: ADC durdu, registerler donar */")
    e.ln("    }")
    e.ln("    iSense = spSim->iSenseUv / 25;")
    e.ln("    iVin = spSim->iVinMv / 25;")
    e.ln(f"    {module}Sim12BitYaz(spSim, 0x14U, iSense);")
    e.ln(f"    {module}Sim12BitYaz(spSim, 0x1EU, iVin);")
    e.ln(f"    {module}Sim12BitYaz(spSim, 0x28U, spSim->iAdinUv / 500);")
    e.ln(f"    {module}SimMaxMin(spSim, 0x16U, 0x18U, {module}Sim12BitOku(spSim, 0x14U));")
    e.ln(f"    {module}SimMaxMin(spSim, 0x20U, 0x22U, {module}Sim12BitOku(spSim, 0x1EU));")
    e.ln(f"    {module}SimMaxMin(spSim, 0x2AU, 0x2CU, {module}Sim12BitOku(spSim, 0x28U));")
    e.ln(f"    uiGuc = (unsigned int){module}Sim12BitOku(spSim, 0x14U) * (unsigned int){module}Sim12BitOku(spSim, 0x1EU);")
    e.ln("    spSim->ucArrReg[0x05U][0] = (unsigned char)((uiGuc >> 16U) & 0xFFU);")
    e.ln("    spSim->ucArrReg[0x06U][0] = (unsigned char)((uiGuc >> 8U) & 0xFFU);")
    e.ln("    spSim->ucArrReg[0x07U][0] = (unsigned char)(uiGuc & 0xFFU);")
    e.ln("    spSim->ucArrReg[0x00U][0] &= (unsigned char)~0x08U; /* ADC_BUSY = 0 */")
    e.ln("}")
    e.blank()
    e.ln(f"static void {module}SimSonrasiOku(S{pas}Sim* spSim, unsigned char ucReg)")
    e.ln("{")
    e.ln("    (void)spSim;")
    e.ln("    (void)ucReg;")
    e.ln("}")
    e.blank()
    e.ln("/* FAULT_CLEAR (0x04) yazimi FAULT'u temizler; ADC_BUSY salt okunurdur. */")
    e.ln(f"static void {module}SimSonrasiYaz(S{pas}Sim* spSim, unsigned char ucReg, unsigned char ucEski)")
    e.ln("{")
    e.ln("    if (ucReg == 0x00U)")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[0x00U][0] = (unsigned char)((spSim->ucArrReg[0x00U][0] & (unsigned char)~0x08U) | (ucEski & 0x08U));")
    e.ln("    }")
    e.ln("    else if (ucReg == 0x04U)")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[0x03U][0] = 0U;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    _ = mod


def _ltc2945_kur(e: _E) -> None:
    e.ln("    spSim->iSenseUv = 50000; /* 50 mV sont -> 10 mohm'da 5 A */")
    e.ln("    spSim->iVinMv = 12000;")
    e.ln("    spSim->iAdinUv = 1000000;")
    e.ln("    (void)uiIndex;")


# --- DS1682: gecen zaman / olay sayaci -------------------------------------------------

def _ds1682_state(e: _E) -> None:
    e.ln("    unsigned int uiEtcTik;    /* gecen zaman sayaci (0.25 s tik)                  */")
    e.ln("    unsigned int uiOlay;      /* olay sayaci (17 bit)                              */")
    e.ln("    unsigned int uiTikAdimi;  /* her okuma isleminde ETC'ye eklenen tik (vars. 4)  */")


def _ds1682_api_header(e: _E, mod: str, pas: str, module: str) -> None:
    for name, param, doc in (
        ("EtcAyarla", "unsigned int uiSaniye", "Gecen zaman sayacini saniye cinsinden kurar (0.25 s tik = x4)."),
        ("OlayAyarla", "unsigned int uiOlay", "Olay sayacini kurar (17 bit)."),
        ("OlayEkle", "unsigned int uiAdet", "EVENT pini darbesi gibi olay sayacini artirir."),
        ("TikAdimiAyarla", "unsigned int uiTik", "Her okuma isleminde ETC'nin ilerleyecegi tik (0 = donmus sayac)."),
    ):
        e.ln("/**")
        e.ln(f" * @brief {doc}")
        e.ln(" * @param spSim Simulator.")
        e.ln(f" * @param {param.split()[1]} Deger.")
        e.ln(" */")
        e.ln(f"void {module}Sim{name}(S{pas}Sim* spSim, {param});")
        e.blank()
    _ = mod


def _ds1682_behavior(e: _E, mod: str, pas: str, module: str) -> None:
    e.ln(f"void {module}SimEtcAyarla(S{pas}Sim* spSim, unsigned int uiSaniye)")
    e.ln("{")
    e.ln(f"    if (spSim != (S{pas}Sim*)0)")
    e.ln("    {")
    e.ln("        spSim->uiEtcTik = uiSaniye * 4U;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln(f"void {module}SimOlayAyarla(S{pas}Sim* spSim, unsigned int uiOlay)")
    e.ln("{")
    e.ln(f"    if (spSim != (S{pas}Sim*)0)")
    e.ln("    {")
    e.ln("        spSim->uiOlay = uiOlay & 0x1FFFFU;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln(f"void {module}SimOlayEkle(S{pas}Sim* spSim, unsigned int uiAdet)")
    e.ln("{")
    e.ln(f"    if (spSim != (S{pas}Sim*)0)")
    e.ln("    {")
    e.ln("        spSim->uiOlay = (spSim->uiOlay + uiAdet) & 0x1FFFFU;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln(f"void {module}SimTikAdimiAyarla(S{pas}Sim* spSim, unsigned int uiTik)")
    e.ln("{")
    e.ln(f"    if (spSim != (S{pas}Sim*)0)")
    e.ln("    {")
    e.ln("        spSim->uiTikAdimi = uiTik;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("/* 32-bit little-endian sayaci ardisik dort register'a yazar. */")
    e.ln(f"static void {module}Sim32Yaz(S{pas}Sim* spSim, unsigned char ucLowReg, unsigned int uiDeger)")
    e.ln("{")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln("    for (uiIndex = 0U; uiIndex < 4U; uiIndex++)")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[ucLowReg + uiIndex][0] = (unsigned char)((uiDeger >> (8U * uiIndex)) & 0xFFU);")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln(f"static unsigned int {module}Sim32Oku(const S{pas}Sim* spSim, unsigned char ucLowReg)")
    e.ln("{")
    e.ln("    unsigned int uiDeger = 0U;")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln("    for (uiIndex = 0U; uiIndex < 4U; uiIndex++)")
    e.ln("    {")
    e.ln("        uiDeger |= (unsigned int)spSim->ucArrReg[ucLowReg + uiIndex][0] << (8U * uiIndex);")
    e.ln("    }")
    e.ln("    return uiDeger;")
    e.ln("}")
    e.blank()
    e.ln("/* Sayac tiki: her okuma isleminde ETC ilerler (EVENT pini aktifmis gibi), ETC/EVENT")
    e.ln(" * registerleri ve CONFIGURATION[0] (olay bit 16) guncellenir, ETC >= ALARM ise ALARM_FLAG. */")
    e.ln(f"static void {module}SimOncesiOku(S{pas}Sim* spSim)")
    e.ln("{")
    e.ln("    unsigned int uiAlarm;")
    e.blank()
    e.ln("    if (spSim->uiHataModu != SPEC2CODE_SIM_HATA_HAZIR_YOK)")
    e.ln("    {")
    e.ln("        spSim->uiEtcTik += spSim->uiTikAdimi;")
    e.ln("    }")
    e.ln(f"    {module}Sim32Yaz(spSim, 0x05U, spSim->uiEtcTik);")
    e.ln("    spSim->ucArrReg[0x09U][0] = (unsigned char)(spSim->uiOlay & 0xFFU);")
    e.ln("    spSim->ucArrReg[0x0AU][0] = (unsigned char)((spSim->uiOlay >> 8U) & 0xFFU);")
    e.ln("    spSim->ucArrReg[0x00U][0] = (unsigned char)((spSim->ucArrReg[0x00U][0] & (unsigned char)~0x01U) |")
    e.ln("                                                (unsigned char)((spSim->uiOlay >> 16U) & 0x1U));")
    e.ln(f"    uiAlarm = {module}Sim32Oku(spSim, 0x01U);")
    e.ln("    if ((uiAlarm != 0U) && (spSim->uiEtcTik >= uiAlarm))")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[0x00U][0] |= 0x40U; /* ALARM_FLAG */")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln(f"static void {module}SimSonrasiOku(S{pas}Sim* spSim, unsigned char ucReg)")
    e.ln("{")
    e.ln("    (void)spSim;")
    e.ln("    (void)ucReg;")
    e.ln("}")
    e.blank()
    e.ln("/* ETC/EVENT registerlerine yazim sayaci kurar; RESET_COMMAND (0x1D) = 0x55 ve")
    e.ln(" * RESET_ENABLE (CONFIGURATION bit 2) ile sayaclar sifirlanir; ALARM_FLAG/EVENT MSB salt okunur. */")
    e.ln(f"static void {module}SimSonrasiYaz(S{pas}Sim* spSim, unsigned char ucReg, unsigned char ucEski)")
    e.ln("{")
    e.ln("    if (ucReg == 0x00U)")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[0x00U][0] = (unsigned char)((spSim->ucArrReg[0x00U][0] & 0xBEU) | (ucEski & 0x41U));")
    e.ln("    }")
    e.ln("    else if ((ucReg >= 0x05U) && (ucReg <= 0x08U))")
    e.ln("    {")
    e.ln(f"        spSim->uiEtcTik = {module}Sim32Oku(spSim, 0x05U);")
    e.ln("    }")
    e.ln("    else if ((ucReg == 0x09U) || (ucReg == 0x0AU))")
    e.ln("    {")
    e.ln("        spSim->uiOlay = (spSim->uiOlay & 0x10000U) | ((unsigned int)spSim->ucArrReg[0x0AU][0] << 8U) |")
    e.ln("                        (unsigned int)spSim->ucArrReg[0x09U][0];")
    e.ln("    }")
    e.ln("    else if ((ucReg == 0x1DU) && (spSim->ucArrReg[0x1DU][0] == 0x55U) &&")
    e.ln("             ((spSim->ucArrReg[0x00U][0] & 0x04U) != 0U))")
    e.ln("    {")
    e.ln("        spSim->uiEtcTik = 0U;")
    e.ln("        spSim->uiOlay = 0U;")
    e.ln("        spSim->ucArrReg[0x00U][0] &= (unsigned char)~0x40U;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    _ = mod


def _ds1682_kur(e: _E) -> None:
    e.ln("    spSim->uiEtcTik = 0U;")
    e.ln("    spSim->uiOlay = 0U;")
    e.ln("    spSim->uiTikAdimi = 4U; /* her okuma ~1 s ilerletir */")
    e.ln("    (void)uiIndex;")


_BEHAVIOR: dict[str, dict[str, Callable]] = {
    "LTC2991": {
        "state": _ltc2991_state,
        "api_header": _ltc2991_api_header,
        "behavior": _ltc2991_behavior,
        "kur": _ltc2991_kur,
    },
    "LTC2945": {
        "state": _ltc2945_state,
        "api_header": _ltc2945_api_header,
        "behavior": _ltc2945_behavior,
        "kur": _ltc2945_kur,
    },
    "DS1682": {
        "state": _ds1682_state,
        "api_header": _ds1682_api_header,
        "behavior": _ds1682_behavior,
        "kur": _ds1682_kur,
    },
}


def has_behavior(plan: _ChipPlan) -> bool:
    return plan.part.upper() in _BEHAVIOR or plan.part.upper() in _SPI_BEHAVIOR


# --- entegre simulatoru ----------------------------------------------------------------

def sim_header(plan: _ChipPlan) -> str:
    if plan.transport == "spi":
        return spi_sim_header(plan)
    mod, pas, module = plan.mod, plan.pascal, plan.module
    reg_count, max_bytes, _rows = _reg_table(plan)
    beh = _BEHAVIOR.get(plan.part.upper())
    e = _E(0)
    e.ln("/**")
    e.ln(f" * @file {module}_sim.h")
    e.ln(f" * @brief {plan.part} sanal cihazi: descriptor register modeli + hata enjeksiyonu"
         + (" + davranis (READY bitleri, donusum kodlari)." if beh else "."))
    e.ln(" *")
    e.ln(" * Kullanim (karisik mod, kart uzerinde cihaz henuz yokken):")
    e.ln(f" *   static S{pas}Sim S_sSim;")
    e.ln(f" *   {module}SimKur(&S_sSim, {mod}_I2C_ADDR);")
    e.ln(" *   spec2codeSimI2cEkle(&S_sSim.sCihaz);   -- bu adres artik sanal, digerleri gercek")
    e.ln(" * Generated by Spec2Code. Do not edit by hand.")
    e.ln(" */")
    e.ln(f"#ifndef {mod}_SIM_H")
    e.ln(f"#define {mod}_SIM_H")
    e.blank()
    e.ln('#include "spec2code_sim.h"')
    e.blank()
    e.ln("#if SPEC2CODE_CIT_SIM")
    e.blank()
    e.ln(f"#define {mod}_SIM_REG_SAYISI {reg_count}U /* en yuksek register ofseti + 1 */")
    e.ln(f"#define {mod}_SIM_BAYT_MAX {max_bytes}U   /* en genis register (bayt) */")
    e.blank()
    e.ln("/**")
    e.ln(f" * @brief {plan.part} simulator durumu. sCihaz ILK alandir (sanal cihaz zinciri).")
    e.ln(" */")
    e.ln("typedef struct")
    e.ln("{")
    e.ln("    SSpec2codeI2cSimCihaz sCihaz;")
    e.ln(f"    unsigned char ucArrReg[{mod}_SIM_REG_SAYISI][{mod}_SIM_BAYT_MAX]; /* register dosyasi */")
    e.ln("    unsigned char ucPointer;    /* son yazilan register adresi (otomatik artar) */")
    e.ln("    unsigned char ucBaytIndeks; /* genis registerde okunan bayt                  */")
    e.ln("    unsigned int uiHataModu;    /* SPEC2CODE_SIM_HATA_*                          */")
    e.ln("    unsigned int uiYazmaSayac;  /* kac yazma transferi geldi                     */")
    e.ln("    unsigned int uiOkumaSayac;  /* kac okuma transferi geldi                     */")
    if beh:
        beh["state"](e)
    e.ln("}" + f" S{pas}Sim;")
    e.blank()
    e.ln("/**")
    e.ln(f" * @brief Simulatoru reset degerleriyle kurar (descriptor reset'leri) ve zincir dugumunu doldurur.")
    e.ln(" * @param spSim Simulator.")
    e.ln(" * @param ucAdres 7-bit adres (spec: <MOD>_I2C_ADDR).")
    e.ln(" */")
    e.ln(f"void {module}SimKur(S{pas}Sim* spSim, unsigned char ucAdres);")
    e.blank()
    e.ln("/**")
    e.ln(" * @brief Hata enjeksiyonu: SPEC2CODE_SIM_HATA_YOK / _NACK / _HAZIR_YOK.")
    e.ln(" * @param spSim Simulator.")
    e.ln(" * @param uiHataModu Mod.")
    e.ln(" */")
    e.ln(f"void {module}SimHataAyarla(S{pas}Sim* spSim, unsigned int uiHataModu);")
    e.blank()
    e.ln("/**")
    e.ln(" * @brief Bir register baytini dogrudan yazar (senaryo kurmak icin; ro registerlere de yazar).")
    e.ln(" * @param spSim Simulator.")
    e.ln(" * @param ucReg Register ofseti.")
    e.ln(" * @param ucBayt Bayt indeksi (genis registerde 0 = MSB).")
    e.ln(" * @param ucDeger Deger.")
    e.ln(" */")
    e.ln(f"void {module}SimRegisterYaz(S{pas}Sim* spSim, unsigned char ucReg, unsigned char ucBayt,")
    e.ln("                          unsigned char ucDeger);")
    e.blank()
    if beh:
        beh["api_header"](e, mod, pas, module)
    e.ln("#endif /* SPEC2CODE_CIT_SIM */")
    e.blank()
    e.ln(f"#endif /* {mod}_SIM_H */")
    return e.text()


def sim_source(plan: _ChipPlan) -> str:
    if plan.transport == "spi":
        return spi_sim_source(plan)
    mod, pas, module = plan.mod, plan.pascal, plan.module
    reg_count, max_bytes, rows = _reg_table(plan)
    beh = _BEHAVIOR.get(plan.part.upper())
    by_off = {r[0]: r for r in rows}
    e = _E(0)
    e.ln("/**")
    e.ln(f" * @file {module}_sim.c")
    e.ln(f" * @brief {plan.part} sanal cihazi gerceklemesi. Generated by Spec2Code.")
    e.ln(" *")
    e.ln(" * Register modeli: yazma transferinin ilk bayti pointer'dir, kalan baytlar")
    e.ln(" * pointer'dan itibaren yazilir (salt okunur register ACK alir ama degismez);")
    e.ln(" * okuma pointer'dan baslar, genis registerin baytlari bittikce sonraki")
    e.ln(" * register'a gecer (I2C otomatik artis).")
    e.ln(" */")
    e.ln(f'#include "{module}_sim.h"')
    e.blank()
    e.ln("#if SPEC2CODE_CIT_SIM")
    e.blank()
    e.ln("/* Register basina bayt genisligi (0 = descriptor'da tanimsiz: 1 bayt, sifir okunur). */")
    e.ln(f"static const unsigned char S_ucArr{pas}SimGenislik[{mod}_SIM_REG_SAYISI] = " + "{")
    e.ln("    " + ", ".join(f"{by_off[i][1] if i in by_off else 0}U" for i in range(reg_count)))
    e.ln("};")
    e.blank()
    e.ln("/* Register basina yazilabilirlik (rw/wo = 1). */")
    e.ln(f"static const unsigned char S_ucArr{pas}SimYazilabilir[{mod}_SIM_REG_SAYISI] = " + "{")
    e.ln("    " + ", ".join(f"{by_off[i][2] if i in by_off else 0}U" for i in range(reg_count)))
    e.ln("};")
    e.blank()
    e.ln("/* Reset degerleri (descriptor `reset`, MSB once). */")
    e.ln(f"static const unsigned char S_ucArr{pas}SimReset[{mod}_SIM_REG_SAYISI][{mod}_SIM_BAYT_MAX] = " + "{")
    for i in range(reg_count):
        if i in by_off:
            off, nbytes, _w, reset, name = by_off[i]
            vals = [(reset >> (8 * (nbytes - 1 - k))) & 0xFF for k in range(nbytes)]
            vals += [0] * (max_bytes - nbytes)
            e.ln("    {" + ", ".join(_hex(v) for v in vals) + "}," + f" /* {name} */")
        else:
            e.ln("    {" + ", ".join("0x00U" for _ in range(max_bytes)) + "},")
    e.ln("};")
    e.blank()
    e.ln(f"static unsigned char {module}SimGenislik(unsigned char ucReg)")
    e.ln("{")
    e.ln(f"    if (ucReg >= {mod}_SIM_REG_SAYISI)")
    e.ln("    {")
    e.ln("        return 1U;")
    e.ln("    }")
    e.ln(f"    return (S_ucArr{pas}SimGenislik[ucReg] == 0U) ? 1U : S_ucArr{pas}SimGenislik[ucReg];")
    e.ln("}")
    e.blank()
    if beh:
        beh["behavior"](e, mod, pas, module)
    # --- HAL geri cagrilari ---
    e.ln(f"static int {module}SimYaz(void* vpDurum, const unsigned char* ucpVeri, unsigned int uiBoy)")
    e.ln("{")
    e.ln(f"    S{pas}Sim* spSim = (S{pas}Sim*)vpDurum;")
    e.ln("    unsigned int uiIndex;")
    e.ln("    unsigned char ucReg;")
    e.ln("    unsigned char ucBayt;")
    e.ln("    unsigned char ucEski;")
    e.blank()
    e.ln("    if (spSim->uiHataModu == SPEC2CODE_SIM_HATA_NACK)")
    e.ln("    {")
    e.ln("        return 1;")
    e.ln("    }")
    e.ln("    if (uiBoy == 0U)")
    e.ln("    {")
    e.ln("        return 0; /* yalniz adres probe'u: ACK */")
    e.ln("    }")
    e.ln("    spSim->uiYazmaSayac++;")
    e.ln("    spSim->ucPointer = ucpVeri[0];")
    e.ln("    spSim->ucBaytIndeks = 0U;")
    e.ln("    ucReg = spSim->ucPointer;")
    e.ln("    ucBayt = 0U;")
    e.ln("    for (uiIndex = 1U; uiIndex < uiBoy; uiIndex++)")
    e.ln("    {")
    e.ln(f"        if (ucReg < {mod}_SIM_REG_SAYISI)")
    e.ln("        {")
    e.ln("            ucEski = spSim->ucArrReg[ucReg][ucBayt];")
    e.ln(f"            if (S_ucArr{pas}SimYazilabilir[ucReg] != 0U)")
    e.ln("            {")
    e.ln("                spSim->ucArrReg[ucReg][ucBayt] = ucpVeri[uiIndex];")
    if beh:
        e.ln(f"                {module}SimSonrasiYaz(spSim, ucReg, ucEski);")
    e.ln("            }")
    if not beh:
        e.ln("            (void)ucEski;")
    e.ln("        }")
    e.ln("        ucBayt++;")
    e.ln(f"        if (ucBayt >= {module}SimGenislik(ucReg))")
    e.ln("        {")
    e.ln("            ucBayt = 0U;")
    e.ln("            ucReg++;")
    e.ln("        }")
    e.ln("    }")
    e.ln("    return 0;")
    e.ln("}")
    e.blank()
    e.ln(f"static int {module}SimOku(void* vpDurum, unsigned char* ucpVeri, unsigned int uiBoy)")
    e.ln("{")
    e.ln(f"    S{pas}Sim* spSim = (S{pas}Sim*)vpDurum;")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln("    if (spSim->uiHataModu == SPEC2CODE_SIM_HATA_NACK)")
    e.ln("    {")
    e.ln("        return 1;")
    e.ln("    }")
    e.ln("    spSim->uiOkumaSayac++;")
    if beh:
        e.ln(f"    {module}SimOncesiOku(spSim);")
    e.ln("    for (uiIndex = 0U; uiIndex < uiBoy; uiIndex++)")
    e.ln("    {")
    e.ln(f"        if (spSim->ucPointer < {mod}_SIM_REG_SAYISI)")
    e.ln("        {")
    e.ln("            ucpVeri[uiIndex] = spSim->ucArrReg[spSim->ucPointer][spSim->ucBaytIndeks];")
    e.ln("        }")
    e.ln("        else")
    e.ln("        {")
    e.ln("            ucpVeri[uiIndex] = 0xFFU;")
    e.ln("        }")
    e.ln("        spSim->ucBaytIndeks++;")
    e.ln(f"        if (spSim->ucBaytIndeks >= {module}SimGenislik(spSim->ucPointer))")
    e.ln("        {")
    if beh:
        e.ln(f"            {module}SimSonrasiOku(spSim, spSim->ucPointer);")
    e.ln("            spSim->ucBaytIndeks = 0U;")
    e.ln("            spSim->ucPointer++;")
    e.ln("        }")
    e.ln("    }")
    e.ln("    return 0;")
    e.ln("}")
    e.blank()
    e.ln(f"void {module}SimKur(S{pas}Sim* spSim, unsigned char ucAdres)")
    e.ln("{")
    e.ln("    unsigned int uiIndex;")
    e.ln("    unsigned int uiBayt;")
    e.blank()
    e.ln(f"    if (spSim == (S{pas}Sim*)0)")
    e.ln("    {")
    e.ln("        return;")
    e.ln("    }")
    e.ln(f"    for (uiIndex = 0U; uiIndex < {mod}_SIM_REG_SAYISI; uiIndex++)")
    e.ln("    {")
    e.ln(f"        for (uiBayt = 0U; uiBayt < {mod}_SIM_BAYT_MAX; uiBayt++)")
    e.ln("        {")
    e.ln(f"            spSim->ucArrReg[uiIndex][uiBayt] = S_ucArr{pas}SimReset[uiIndex][uiBayt];")
    e.ln("        }")
    e.ln("    }")
    e.ln("    spSim->ucPointer = 0U;")
    e.ln("    spSim->ucBaytIndeks = 0U;")
    e.ln("    spSim->uiHataModu = SPEC2CODE_SIM_HATA_YOK;")
    e.ln("    spSim->uiYazmaSayac = 0U;")
    e.ln("    spSim->uiOkumaSayac = 0U;")
    if beh:
        beh["kur"](e)
    e.ln("    spSim->sCihaz.ucAdres = ucAdres;")
    e.ln("    spSim->sCihaz.vpDurum = spSim;")
    e.ln(f"    spSim->sCihaz.pfYaz = {module}SimYaz;")
    e.ln(f"    spSim->sCihaz.pfOku = {module}SimOku;")
    e.ln("    spSim->sCihaz.spSonraki = (SSpec2codeI2cSimCihaz*)0;")
    e.ln("}")
    e.blank()
    e.ln(f"void {module}SimHataAyarla(S{pas}Sim* spSim, unsigned int uiHataModu)")
    e.ln("{")
    e.ln(f"    if (spSim != (S{pas}Sim*)0)")
    e.ln("    {")
    e.ln("        spSim->uiHataModu = uiHataModu;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln(f"void {module}SimRegisterYaz(S{pas}Sim* spSim, unsigned char ucReg, unsigned char ucBayt,")
    e.ln("                          unsigned char ucDeger)")
    e.ln("{")
    e.ln(f"    if ((spSim != (S{pas}Sim*)0) && (ucReg < {mod}_SIM_REG_SAYISI) && (ucBayt < {mod}_SIM_BAYT_MAX))")
    e.ln("    {")
    e.ln("        spSim->ucArrReg[ucReg][ucBayt] = ucDeger;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("#endif /* SPEC2CODE_CIT_SIM */")
    return e.text()



# --- SPI TICS-register cihazi simulatoru ---------------------------------------------------

def _spi_model(plan: _ChipPlan) -> dict:
    from orchestrator import tics
    model = tics.register_model(plan.descriptor)
    frame_bits = int(model.get("frame_bits", 24) or 24)
    return {
        "frame_bytes": frame_bits // 8,
        "address_bits": int(model.get("address_bits", 15) or 15),
        "address_shift": int(model.get("address_shift", 8) or 8),
        "data_bits": int(model.get("data_bits", 8) or 8),
        "rw_bit": int(model.get("rw_bit", frame_bits - 1) or (frame_bits - 1)),
        "read_value": 0 if int(model.get("write_value", 0) or 0) else 1,
    }


def _spi_reg_rows(plan: _ChipPlan) -> tuple[int, list[tuple[int, int, int, str]]]:
    rows: list[tuple[int, int, int, str]] = []
    max_off = 0
    for rg in plan.descriptor.get("registers", []):
        off = int(rg.get("offset", 0))
        if off > 0x7FFF:
            continue
        access = str(rg.get("access", "rw")).lower()
        rows.append((off, 1 if "w" in access else 0, int(rg.get("reset", 0) or 0), str(rg.get("name", ""))))
        max_off = max(max_off, off)
    return max_off + 1, rows


def _lmk04832_state(e: _E) -> None:
    e.ln("    unsigned int uiPll1Kilit; /* PLL1 dijital kilit (RB_PLL_STATUS bit 2)      */")
    e.ln("    unsigned int uiPll2Kilit; /* PLL2 dijital kilit (RB_PLL_STATUS bit 0)      */")


def _lmk04832_api_header(e: _E, mod: str, pas: str, module: str) -> None:
    e.ln("/**")
    e.ln(" * @brief PLL kilit durumlarini kurar; her okumada RB_PLL_STATUS (0x183) buna gore uretilir:")
    e.ln(" *        bit2 RB_PLL1_DLD, bit0 RB_PLL2_DLD, bit3/bit1 kilit-kaybi bayraklari (kilit yoksa 1).")
    e.ln(" * @param spSim Simulator.")
    e.ln(" * @param uiPll1 1 = PLL1 kilitli.")
    e.ln(" * @param uiPll2 1 = PLL2 kilitli.")
    e.ln(" */")
    e.ln(f"void {module}SimKilitAyarla(S{pas}Sim* spSim, unsigned int uiPll1, unsigned int uiPll2);")
    e.blank()
    _ = mod


def _lmk04832_behavior(e: _E, mod: str, pas: str, module: str) -> None:
    e.ln(f"void {module}SimKilitAyarla(S{pas}Sim* spSim, unsigned int uiPll1, unsigned int uiPll2)")
    e.ln("{")
    e.ln(f"    if (spSim != (S{pas}Sim*)0)")
    e.ln("    {")
    e.ln("        spSim->uiPll1Kilit = (uiPll1 != 0U) ? 1U : 0U;")
    e.ln("        spSim->uiPll2Kilit = (uiPll2 != 0U) ? 1U : 0U;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("/* Her okuma cercevesinden once: RB_PLL_STATUS kilit durumundan uretilir. */")
    e.ln(f"static void {module}SimOncesiOku(S{pas}Sim* spSim)")
    e.ln("{")
    e.ln("    unsigned short usDurum = 0U;")
    e.blank()
    e.ln("    if (spSim->uiHataModu == SPEC2CODE_SIM_HATA_HAZIR_YOK)")
    e.ln("    {")
    e.ln("        spSim->usArrReg[0x183U] = 0x0AU; /* iki PLL de kilit kaybi */")
    e.ln("        return;")
    e.ln("    }")
    e.ln("    usDurum |= (unsigned short)((spSim->uiPll1Kilit != 0U) ? 0x04U : 0x08U);")
    e.ln("    usDurum |= (unsigned short)((spSim->uiPll2Kilit != 0U) ? 0x01U : 0x02U);")
    e.ln("    spSim->usArrReg[0x183U] = usDurum;")
    e.ln("}")
    e.blank()
    _ = mod


def _lmk04832_kur(e: _E) -> None:
    e.ln("    spSim->uiPll1Kilit = 1U;")
    e.ln("    spSim->uiPll2Kilit = 1U;")


_SPI_BEHAVIOR: dict[str, dict[str, Callable]] = {
    "LMK04832": {
        "state": _lmk04832_state,
        "api_header": _lmk04832_api_header,
        "behavior": _lmk04832_behavior,
        "kur": _lmk04832_kur,
    },
}


def spi_sim_header(plan: _ChipPlan) -> str:
    mod, pas, module = plan.mod, plan.pascal, plan.module
    reg_count, _rows = _spi_reg_rows(plan)
    m = _spi_model(plan)
    beh = _SPI_BEHAVIOR.get(plan.part.upper())
    e = _E(0)
    e.ln("/**")
    e.ln(f" * @file {module}_sim.h")
    e.ln(f" * @brief {plan.part} sanal SPI cihazi: descriptor register modeli ({m['frame_bytes'] * 8}-bit cerceve,")
    e.ln(f" *        {m['address_bits']}-bit adres, {m['data_bits']}-bit veri) + hata enjeksiyonu"
         + (" + davranis (PLL kilit bitleri)." if beh else "."))
    e.ln(" *")
    e.ln(" * Kullanim (karisik mod, kart uzerinde cihaz henuz yokken):")
    e.ln(f" *   static S{pas}Sim S_sSim;")
    e.ln(f" *   {module}SimKur(&S_sSim, {mod}_SPI_SELECT);")
    e.ln(" *   spec2codeSimSpiEkle(&S_sSim.sCihaz);   -- bu chip-select artik sanal, digerleri gercek")
    e.ln(" * Generated by Spec2Code. Do not edit by hand.")
    e.ln(" */")
    e.ln(f"#ifndef {mod}_SIM_H")
    e.ln(f"#define {mod}_SIM_H")
    e.blank()
    e.ln('#include "spec2code_sim.h"')
    e.blank()
    e.ln("#if SPEC2CODE_CIT_SIM")
    e.blank()
    e.ln(f"#define {mod}_SIM_REG_SAYISI {reg_count}U /* en yuksek register adresi + 1 */")
    e.ln(f"#define {mod}_SIM_FRAME_BYTES {m['frame_bytes']}U")
    e.blank()
    e.ln("/**")
    e.ln(f" * @brief {plan.part} simulator durumu. sCihaz ILK alandir (sanal cihaz zinciri).")
    e.ln(" */")
    e.ln("typedef struct")
    e.ln("{")
    e.ln("    SSpec2codeSpiSimCihaz sCihaz;")
    e.ln(f"    unsigned short usArrReg[{mod}_SIM_REG_SAYISI]; /* register dosyasi (veri {m['data_bits']} bit) */")
    e.ln("    unsigned int uiHataModu;   /* SPEC2CODE_SIM_HATA_*                    */")
    e.ln("    unsigned int uiYazmaSayac; /* kac yazma cercevesi geldi               */")
    e.ln("    unsigned int uiOkumaSayac; /* kac okuma cercevesi geldi               */")
    e.ln("    unsigned int uiSonAdres;   /* son cercevenin adresi (teshis)           */")
    if beh:
        beh["state"](e)
    e.ln("}" + f" S{pas}Sim;")
    e.blank()
    e.ln("/**")
    e.ln(" * @brief Simulatoru descriptor reset degerleriyle kurar ve zincir dugumunu doldurur.")
    e.ln(" * @param spSim Simulator.")
    e.ln(" * @param ucSelect Chip-select indeksi (spec: <MOD>_SPI_SELECT).")
    e.ln(" */")
    e.ln(f"void {module}SimKur(S{pas}Sim* spSim, unsigned char ucSelect);")
    e.blank()
    e.ln("/**")
    e.ln(" * @brief Hata enjeksiyonu: SPEC2CODE_SIM_HATA_YOK / _NACK (transfer basarisiz) / _HAZIR_YOK.")
    e.ln(" * @param spSim Simulator.")
    e.ln(" * @param uiHataModu Mod.")
    e.ln(" */")
    e.ln(f"void {module}SimHataAyarla(S{pas}Sim* spSim, unsigned int uiHataModu);")
    e.blank()
    e.ln("/**")
    e.ln(" * @brief Bir registeri dogrudan yazar (senaryo kurmak icin; ro registerlere de yazar).")
    e.ln(" * @param spSim Simulator.")
    e.ln(" * @param uiAdres Register adresi.")
    e.ln(" * @param usDeger Deger.")
    e.ln(" */")
    e.ln(f"void {module}SimRegisterYaz(S{pas}Sim* spSim, unsigned int uiAdres, unsigned short usDeger);")
    e.blank()
    if beh:
        beh["api_header"](e, mod, pas, module)
    e.ln("#endif /* SPEC2CODE_CIT_SIM */")
    e.blank()
    e.ln(f"#endif /* {mod}_SIM_H */")
    return e.text()


def spi_sim_source(plan: _ChipPlan) -> str:
    mod, pas, module = plan.mod, plan.pascal, plan.module
    reg_count, rows = _spi_reg_rows(plan)
    m = _spi_model(plan)
    beh = _SPI_BEHAVIOR.get(plan.part.upper())
    addr_mask = (1 << m["address_bits"]) - 1
    data_mask = (1 << m["data_bits"]) - 1
    e = _E(0)
    e.ln("/**")
    e.ln(f" * @file {module}_sim.c")
    e.ln(f" * @brief {plan.part} sanal SPI cihazi gerceklemesi. Generated by Spec2Code.")
    e.ln(" *")
    e.ln(f" * Cerceve (descriptor register_model): {m['frame_bytes'] * 8} bit MSB-once; R/W biti {m['rw_bit']}")
    e.ln(f" * ({m['read_value']} = okuma), adres bit {m['address_shift']}.., veri son {m['data_bits']} bit. Okumada")
    e.ln(" * cevap ayni cercevenin veri bitlerinde doner (MISO), yazimda yazilabilir register saklanir.")
    e.ln(" */")
    e.ln(f'#include "{module}_sim.h"')
    e.blank()
    e.ln("#if SPEC2CODE_CIT_SIM")
    e.blank()
    e.ln("typedef struct")
    e.ln("{")
    e.ln("    unsigned short usAdres;")
    e.ln("    unsigned short usReset;")
    e.ln("    unsigned char ucYazilabilir;")
    e.ln("}" + f" S{pas}SimRegTanim;")
    e.blank()
    e.ln(f"#define {mod}_SIM_TANIM_SAYISI {max(1, len(rows))}U")
    e.blank()
    e.ln(f"static const S{pas}SimRegTanim S_sArr{pas}SimTanim[{mod}_SIM_TANIM_SAYISI] = " + "{")
    if rows:
        for off, w, reset, name in rows:
            e.ln(f"    {{{_hex(off, 16)}, {_hex(reset & 0xFFFF, 16)}, {w}U}}, /* {name} */")
    else:
        e.ln("    {0x0000U, 0x0000U, 1U},")
    e.ln("};")
    e.blank()
    e.ln(f"static unsigned char {module}SimYazilabilir(unsigned int uiAdres)")
    e.ln("{")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln(f"    for (uiIndex = 0U; uiIndex < {mod}_SIM_TANIM_SAYISI; uiIndex++)")
    e.ln("    {")
    e.ln(f"        if (S_sArr{pas}SimTanim[uiIndex].usAdres == uiAdres)")
    e.ln("        {")
    e.ln(f"            return S_sArr{pas}SimTanim[uiIndex].ucYazilabilir;")
    e.ln("        }")
    e.ln("    }")
    e.ln("    return 1U; /* descriptor'da tanimsiz adres: TICS dizisi yazabilsin diye yazilabilir */")
    e.ln("}")
    e.blank()
    if beh:
        beh["behavior"](e, mod, pas, module)
    e.ln(f"static int {module}SimTransfer(void* vpDurum, const unsigned char* ucpTx, unsigned char* ucpRx,")
    e.ln("                               unsigned int uiBoy)")
    e.ln("{")
    e.ln(f"    S{pas}Sim* spSim = (S{pas}Sim*)vpDurum;")
    e.ln("    unsigned int uiWord = 0U;")
    e.ln("    unsigned int uiAdres;")
    e.ln("    unsigned int uiVeri;")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln("    if (spSim->uiHataModu == SPEC2CODE_SIM_HATA_NACK)")
    e.ln("    {")
    e.ln("        return 1;")
    e.ln("    }")
    e.ln(f"    if (uiBoy != {mod}_SIM_FRAME_BYTES)")
    e.ln("    {")
    e.ln("        return 1; /* yalniz register cercevesi modellenir */")
    e.ln("    }")
    e.ln("    for (uiIndex = 0U; uiIndex < uiBoy; uiIndex++)")
    e.ln("    {")
    e.ln("        uiWord = (uiWord << 8U) | (unsigned int)ucpTx[uiIndex];")
    e.ln("    }")
    e.ln(f"    uiAdres = (uiWord >> {m['address_shift']}U) & {_hex(addr_mask, 16)};")
    e.ln("    spSim->uiSonAdres = uiAdres;")
    e.ln(f"    if (((uiWord >> {m['rw_bit']}U) & 0x1U) == {m['read_value']}U)")
    e.ln("    {")
    e.ln("        spSim->uiOkumaSayac++;")
    if beh:
        e.ln(f"        {module}SimOncesiOku(spSim);")
    e.ln(f"        uiVeri = (uiAdres < {mod}_SIM_REG_SAYISI) ? (unsigned int)spSim->usArrReg[uiAdres] : 0U;")
    e.ln(f"        uiWord = (uiWord & ~{_hex(data_mask, 32)}) | (uiVeri & {_hex(data_mask, 32)});")
    e.ln("    }")
    e.ln("    else")
    e.ln("    {")
    e.ln("        spSim->uiYazmaSayac++;")
    e.ln(f"        if ((uiAdres < {mod}_SIM_REG_SAYISI) && ({module}SimYazilabilir(uiAdres) != 0U))")
    e.ln("        {")
    e.ln(f"            spSim->usArrReg[uiAdres] = (unsigned short)(uiWord & {_hex(data_mask, 32)});")
    e.ln("        }")
    e.ln("    }")
    e.ln("    if (ucpRx != (unsigned char*)0)")
    e.ln("    {")
    e.ln("        for (uiIndex = 0U; uiIndex < uiBoy; uiIndex++)")
    e.ln("        {")
    e.ln("            ucpRx[uiIndex] = (unsigned char)((uiWord >> (8U * (uiBoy - 1U - uiIndex))) & 0xFFU);")
    e.ln("        }")
    e.ln("    }")
    e.ln("    return 0;")
    e.ln("}")
    e.blank()
    e.ln(f"void {module}SimKur(S{pas}Sim* spSim, unsigned char ucSelect)")
    e.ln("{")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln(f"    if (spSim == (S{pas}Sim*)0)")
    e.ln("    {")
    e.ln("        return;")
    e.ln("    }")
    e.ln(f"    for (uiIndex = 0U; uiIndex < {mod}_SIM_REG_SAYISI; uiIndex++)")
    e.ln("    {")
    e.ln("        spSim->usArrReg[uiIndex] = 0U;")
    e.ln("    }")
    e.ln(f"    for (uiIndex = 0U; uiIndex < {mod}_SIM_TANIM_SAYISI; uiIndex++)")
    e.ln("    {")
    e.ln(f"        if (S_sArr{pas}SimTanim[uiIndex].usAdres < {mod}_SIM_REG_SAYISI)")
    e.ln("        {")
    e.ln(f"            spSim->usArrReg[S_sArr{pas}SimTanim[uiIndex].usAdres] = S_sArr{pas}SimTanim[uiIndex].usReset;")
    e.ln("        }")
    e.ln("    }")
    e.ln("    spSim->uiHataModu = SPEC2CODE_SIM_HATA_YOK;")
    e.ln("    spSim->uiYazmaSayac = 0U;")
    e.ln("    spSim->uiOkumaSayac = 0U;")
    e.ln("    spSim->uiSonAdres = 0U;")
    if beh:
        beh["kur"](e)
    e.ln("    spSim->sCihaz.ucSelect = ucSelect;")
    e.ln("    spSim->sCihaz.vpDurum = spSim;")
    e.ln(f"    spSim->sCihaz.pfTransfer = {module}SimTransfer;")
    e.ln("    spSim->sCihaz.spSonraki = (SSpec2codeSpiSimCihaz*)0;")
    e.ln("}")
    e.blank()
    e.ln(f"void {module}SimHataAyarla(S{pas}Sim* spSim, unsigned int uiHataModu)")
    e.ln("{")
    e.ln(f"    if (spSim != (S{pas}Sim*)0)")
    e.ln("    {")
    e.ln("        spSim->uiHataModu = uiHataModu;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln(f"void {module}SimRegisterYaz(S{pas}Sim* spSim, unsigned int uiAdres, unsigned short usDeger)")
    e.ln("{")
    e.ln(f"    if ((spSim != (S{pas}Sim*)0) && (uiAdres < {mod}_SIM_REG_SAYISI))")
    e.ln("    {")
    e.ln("        spSim->usArrReg[uiAdres] = usDeger;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("#endif /* SPEC2CODE_CIT_SIM */")
    return e.text()
