"""Shell katmani (``outputs/<proje>/shell/``): konsol UART'indan komutla CIT / I2C tarama / log seviyesi.

Kullanicinin KENDI main'inde derlenir (test bench ajaniyla ilgisi yoktur; ajan bu klasoru
derlemez, Vitis sahnelemesi ayri `<app>_shell` uygulamasina koyar). ``drivers/`` ve ``cit/``
gibi tasinabilirdir: icinde urun adi gecmez.

Uretilen agac:
* ``shell/shell_uart.h/.c``          - BSP stdin/stdout cihazindan (``STDIN_BASEADDRESS``) bloklamadan
                                      tek bayt oku/yaz; platforma gore XUartLite / XUartPs / XUartPsv.
* ``shell/shell.h/.c``               - CEKIRDEK (komut icermez): satir okuma, yukari/asagi ok gecmisi, tokenize,
                                      ``SShellCommand {ad, isleyici, yardim}`` tablo dagitimi; ``shellInit``,
                                      ``shellCommandsRegister``, ``shellCheck`` (bloklamaz); komutlarin kullandigi
                                      erisimciler (``shellBus/Limit/Cit``, ``shellCommandCount/Get``).
* ``shell/shell_user_commands.h/.c`` - TUM KOMUTLAR tek tabloda (``S_sArrUserCommands``): ``cit``, ``i2c_search``,
                                      ``i2c_read``, ``i2c_write`` (``i2c_bus``), ``mem``, ``sdl``, ``help`` ve ornek
                                      ``mod <x> <y>`` (custom IP register yazimi).
                                      Yeni komut = bir fonksiyon + tabloya bir satir (kullanici istegi 2026-09-08:
                                      cit/sdl gibi komutlar da bu dosyada dursun).
* ``main.h/.c`` (KOK dizin)          - ana program: Colossal banner, bus kur, ``sistemCitInit``, ``shellInit``,
                                      ``shellCommandsRegister(shellUserCommandTable(), ...)``,
                                      ``while (1) shellCheck();``.

Tasarim notlari:
* Cikti ``xil_printf`` ile konsola gider; ``cit`` raporu ``dbg_printf`` INFO satirlaridir, esik
  komutta DEGISTIRILMEZ (kullanici ``sdl info`` ile acar; v0.1.204 istegi).
* ``i2c_search`` spec'teki her I2C denetleyicisinde 0x08..0x77 tek-bayt yazma probu yapar
  (ajanin i2c_scan'iyle ayni yontem). I2C switch (TCA9548A) adresleri ATLANIR: aktif
  switch'e 0x00 yazmak secili kanali kapatirdi.
* Konsol metinleri Ingilizce (SAHA istegi 2026-09-08: "kabuk" ifadesi istenmedi).
"""

from __future__ import annotations

import re
from pathlib import Path

from hostplat import io as hio
from orchestrator import banner_font, cit_layer, cmodel
from orchestrator.bsp_flow import is_sdt, lookup_suffix

SHELL_DIR = "shell"

_UART_BY_PLATFORM = {
    "microblaze_7series": "XUartLite",
    "zynq_7000": "XUartPs",
    "zynq_ultrascale": "XUartPs",
    "versal": "XUartPsv",
}

_UART_API = {
    "XUartLite": ("xuartlite_l.h", "XUartLite_IsReceiveEmpty(STDIN_BASEADDRESS) != 0U",
                  "XUartLite_RecvByte", "XUartLite_SendByte"),
    "XUartPs": ("xuartps_hw.h", "XUartPs_IsReceiveData(STDIN_BASEADDRESS) == 0U",
                "XUartPs_RecvByte", "XUartPs_SendByte"),
    "XUartPsv": ("xuartpsv_hw.h", "XUartPsv_IsReceiveData(STDIN_BASEADDRESS) == 0U",
                 "XUartPsv_RecvByte", "XUartPsv_SendByte"),
}


def console_uart_driver(spec: dict) -> str:
    """Konsol UART surucusu: spec'teki MDM olmayan ilk UART, yoksa platform varsayilani."""
    for controller in spec.get("controllers", []):
        if controller.get("type") == "uart" and controller.get("subtype") != "mdm":
            driver = str(controller.get("driver", ""))
            if driver in _UART_API:
                return driver
    platform = str(spec.get("project", {}).get("platform", ""))
    return _UART_BY_PLATFORM.get(platform, "XUartPs")


# --- shell_uart --------------------------------------------------------------------------

def uart_header() -> str:
    return (
        "/**\n"
        " * @file shell_uart.h\n"
        " * @brief Konsol UART'i (BSP stdin/stdout) uzerinden bloklamayan bayt okuma/yazma.\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        "#ifndef SHELL_UART_H\n"
        "#define SHELL_UART_H\n\n"
        '#include "xil_types.h"\n\n'
        "/* Konsolda bekleyen bir bayt varsa onu verir ve TRUE doner; yoksa hemen FALSE doner. */\n"
        "unsigned int shellUartByteRead(unsigned char* ucpByte);\n"
        "/* Bir bayti konsola yazar (gonderim FIFO'su doluysa bosalana kadar bekler). */\n"
        "void shellUartByteWrite(unsigned char ucByte);\n\n"
        "#endif /* SHELL_UART_H */\n"
    )


def uart_source(spec: dict) -> str:
    driver = console_uart_driver(spec)
    header, empty_expr, recv, send = _UART_API[driver]
    return (
        "/**\n"
        " * @file shell_uart.c\n"
        f" * @brief Konsol UART'i bayt erisimi ({driver}, BSP STDIN/STDOUT_BASEADDRESS).\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        '#include "shell_uart.h"\n'
        '#include "xparameters.h"\n'
        f'#include "{header}"\n'
        "#include <stddef.h>\n\n"
        "unsigned int shellUartByteRead(unsigned char* ucpByte)\n"
        "{\n"
        "#if defined(STDIN_BASEADDRESS)\n"
        "    if (ucpByte == NULL)\n"
        "    {\n"
        "        return FALSE;\n"
        "    }\n"
        f"    if ({empty_expr})\n"
        "    {\n"
        "        return FALSE;\n"
        "    }\n"
        f"    *ucpByte = (unsigned char){recv}(STDIN_BASEADDRESS);\n"
        "    return TRUE;\n"
        "#else\n"
        "    (void)ucpByte;\n"
        "    return FALSE; /* BSP'de stdin cihazi yok */\n"
        "#endif\n"
        "}\n\n"
        "void shellUartByteWrite(unsigned char ucByte)\n"
        "{\n"
        "#if defined(STDOUT_BASEADDRESS)\n"
        f"    {send}(STDOUT_BASEADDRESS, ucByte);\n"
        "#else\n"
        "    (void)ucByte;\n"
        "#endif\n"
        "}\n"
    )


# --- shell -------------------------------------------------------------------------------

def shell_header() -> str:
    return (
        "/**\n"
        " * @file shell.h\n"
        " * @brief Konsol shell'i CEKIRDEGI: satir okuma, gecmis, tokenize, komut tablosu dagitimi.\n"
        " *\n"
        " * Kullanim (kart yazilimi, bkz. main.c):\n"
        " *   sistemCitBusVarsayilan(&S_sBus); sistemCitInit(&S_sBus);   -- ana dongu oncesi\n"
        " *   shellInit(&S_sBus, &S_sLimit, &S_sCit);\n"
        " *   shellCommandsRegister(shellUserCommandTable(), shellUserCommandCount());\n"
        " *   while (1) { shellCheck(); }                                -- bloklamaz\n"
        " *\n"
        " * Komut modeli: her komut `SShellCommand {cpName, fpHandler, cpHelp}` satiridir. Isleyici\n"
        " * `void f(unsigned int uiArgc, const char* cpArrArgv[])` imzasindadir; cpArrArgv[0] komut adi,\n"
        " * sonrakiler STRING argumanlar (sayi gerekiyorsa atoi/strtol ile cevrilir). Bu dosyada KOMUT YOKTUR:\n"
        " * tum komutlar (cit, i2c_search, sdl, help, mod ...) shell_user_commands.c'deki tek tablodadir;\n"
        " * main.c o tabloyu shellCommandsRegister ile kaydeder.\n"
        " *\n"
        " * Yukari/asagi ok tuslari (ESC [ A / ESC [ B) komut gecmisinde gezer (son SHELL_HISTORY_MAX).\n"
        " * `cit` raporu dbg_printf INFO satirlaridir: `sdl info` (ya da ustu) ile gorunur; komut esigi\n"
        " * degistirmez, yalniz `cit: OK|NOK|ERROR (run #n)` sonuc satiri her seviyede basilir.\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        "#ifndef SHELL_H\n"
        "#define SHELL_H\n\n"
        '#include "sistem_cit.h"\n\n'
        "#define SHELL_LINE_MAX 48U\n"
        "#define SHELL_ARG_MAX 8U     /* komut adi dahil en fazla token */\n"
        "#define SHELL_HISTORY_MAX 8U /* yukari/asagi ok ile gezilen son komutlar */\n"
        "#define SHELL_TABLE_MAX 4U   /* kayitli komut tablosu sayisi (yerlesik + kullanici ...) */\n"
        '#define SHELL_PROMPT "> "\n\n'
        "/* Komut isleyicisi: uiArgc token sayisi (>= 1), cpArrArgv[0] komut adi, digerleri string arguman. */\n"
        "typedef void (*FShellHandler)(unsigned int uiArgc, const char* cpArrArgv[]);\n\n"
        "typedef struct\n"
        "{\n"
        '    const char* cpName;      /* konsolda yazilan ad (or. "mod") */\n'
        "    FShellHandler fpHandler; /* isleyici */\n"
        '    const char* cpHelp;      /* help satiri: "<args>  aciklama" */\n'
        "} SShellCommand;\n\n"
        "/* Shell'i CIT yapilariyla baglar, istemi basar. Yapilar kalici olmali; komut tablosu ayrica kaydedilir. */\n"
        "void shellInit(SSistemCitBus* spBus, const SSistemCitLimit* spLimit, SSistemCit* spCit);\n"
        "/* Komut tablosu kaydeder (shell_user_commands.c). Tablo kalici (static) olmali. TRUE = kaydedildi. */\n"
        "unsigned int shellCommandsRegister(const SShellCommand* spTable, unsigned int uiCount);\n"
        "/* Ana dongude cagrilir: konsolda bayt varsa isler, satir tamamlaninca komutu kosar; bloklamaz. */\n"
        "void shellCheck(void);\n\n"
        "/* Komut isleyicilerinin kullandigi erisimciler. */\n"
        "SSistemCitBus* shellBus(void);\n"
        "const SSistemCitLimit* shellLimit(void);\n"
        "SSistemCit* shellCit(void);\n"
        "/* Kayitli komutlar (tum tablolar, kayit sirasiyla): help listesi icin. */\n"
        "unsigned int shellCommandCount(void);\n"
        "const SShellCommand* shellCommandGet(unsigned int uiIndex);\n\n"
        "#endif /* SHELL_H */\n"
    )


def _i2c_bus_entries(spec: dict, plans: list) -> list[tuple[str, str, str]]:
    """(denetleyici id, SSistemCitBus alani, surucu) - CIT bus'indaki I2C denetleyicileri."""
    out = []
    for controller in cit_layer.bus_controllers(plans):
        if controller.get("type") != "i2c":
            continue
        htype, _ = cmodel._handle_for(controller)
        out.append((str(controller.get("id")), cit_layer.controller_field(controller), htype))
    return out


def _i2c_device_names(spec: dict, controller_id: str) -> list[tuple[int, str]]:
    """Denetleyicideki I2C cihazlari (adres, "kimlik (parca[, switch 0x70 ch3])") - i2c_search etiketi."""
    mux_by_id = {str(m.get("id")): m for m in spec.get("muxes", [])}
    out: list[tuple[int, str]] = []
    for device in spec.get("devices", []):
        attach = device.get("attach") or {}
        if str(attach.get("controller_id")) != controller_id or attach.get("i2c_address") is None:
            continue
        try:
            address = int(str(attach.get("i2c_address")), 0)
        except ValueError:
            continue
        label = f"{device.get('id')} ({device.get('part')}"
        via = attach.get("via_mux") or {}
        mux = mux_by_id.get(str(via.get("mux_id"))) if via else None
        if mux is not None:
            label += f", switch {mux.get('i2c_address')} ch{via.get('channel')}"
        out.append((address, label + ")"))
    return sorted(out)


def _i2c_table_name(controller_id: str) -> str:
    return "S_sArrI2cDevice" + "".join(p.capitalize() for p in controller_id.split("_"))


def custom_ips(spec: dict) -> list[dict]:
    """Spec'teki custom IP'ler (id, base_address, register_count); bozuk kayit atlanir."""
    out: list[dict] = []
    for item in spec.get("custom_ips", []) or []:
        if str(item.get("register_map") or "").strip():
            continue  # bilinen IP: register adli `ip_<id>` komutu var, generic dump/read/write uretilmez (ad cakisir)
        try:
            base = int(str(item.get("base_address")), 0)
            count = int(item.get("register_count") or 0)
        except (TypeError, ValueError):
            continue
        cid = re.sub(r"[^a-z0-9_]", "_", str(item.get("id", "")).lower())
        if not cid or count < 1:
            continue
        out.append({"id": cid, "base": base, "count": count, "instance": str(item.get("instance") or ""),
                    "ip_name": str(item.get("ip_name") or "")})
    return out


def _custom_ip_handler(cid: str) -> str:
    return "shellUser" + "".join(p.capitalize() for p in cid.split("_") if p)


def known_ip_maps(spec: dict) -> list[dict]:
    """Register haritasi bilinen custom IP'ler (register_map alani dolu) + istenirse surucusu olan AXI
    denetleyiciler (generation_options.controller_register_maps: XIic/XSpi/XUartLite -> PG haritasi):
    {id, base, key, params, ip_name}."""
    from backend.ip_register_maps import driver_map_key

    out: list[dict] = []
    if (spec.get("generation_options") or {}).get("controller_register_maps"):
        for c in spec.get("controllers", []) or []:
            key = driver_map_key(str(c.get("driver") or ""))
            cid = re.sub(r"[^a-z0-9_]", "_", str(c.get("id", "")).lower())
            try:
                base = int(str(c.get("base_address")), 0)
            except (TypeError, ValueError):
                continue
            if key and cid:
                out.append({"id": cid, "base": base, "key": key, "params": {}, "ip_name": key})
    for item in spec.get("custom_ips", []) or []:
        key = str(item.get("register_map") or "").strip()
        if not key:
            continue
        cid = re.sub(r"[^a-z0-9_]", "_", str(item.get("id", "")).lower())
        try:
            base = int(str(item.get("base_address")), 0)
        except (TypeError, ValueError):
            continue
        if cid:
            out.append({"id": cid, "base": base, "key": key, "params": dict(item.get("ip_parameters") or {}),
                        "ip_name": str(item.get("ip_name") or key)})
    return out


def _known_ip_handler(cid: str) -> str:
    # register_map.generate_shell_command ile ayni ad: shellUser<Pascal(map)>
    return "shellUser" + "".join(p[:1].upper() + p[1:] for p in cid.split("_") if p)


def _mux_addresses(spec: dict) -> list[int]:
    addrs = []
    for mux in spec.get("muxes", []):
        try:
            addrs.append(int(str(mux.get("i2c_address", "0")), 0))
        except ValueError:
            continue
    return sorted(set(addrs))


def shell_source() -> str:
    e = cit_layer._E(0)
    e.ln("/**")
    e.ln(" * @file shell.c")
    e.ln(" * @brief Konsol shell'i cekirdegi: satir okuma, gecmis, tokenize, tablo dagitimi (komutlar ayri dosyada).")
    e.ln(" *")
    e.ln(" * Generated by Spec2Code. Do not edit by hand.")
    e.ln(" */")
    e.ln('#include "shell.h"')
    e.ln('#include "shell_uart.h"')
    e.ln('#include "xil_printf.h"')
    e.ln("#include <stddef.h>")
    e.ln("#include <string.h>")
    e.blank()
    e.ln("static SSistemCitBus* S_spBus = NULL;")
    e.ln("static const SSistemCitLimit* S_spLimit = NULL;")
    e.ln("static SSistemCit* S_spCit = NULL;")
    e.ln("static char S_cArrLine[SHELL_LINE_MAX];")
    e.ln("static unsigned int S_uiLineLength = 0U;")
    e.ln("/* Komut gecmisi: halka; S_uiHistoryCount kayitli sayi, S_uiHistoryHead sonraki yazma yeri,")
    e.ln(" * S_uiHistoryCursor gezinti konumu (== count: gecmis disinda, bos satir). */")
    e.ln("static char S_cArrHistory[SHELL_HISTORY_MAX][SHELL_LINE_MAX];")
    e.ln("static unsigned int S_uiHistoryCount = 0U;")
    e.ln("static unsigned int S_uiHistoryHead = 0U;")
    e.ln("static unsigned int S_uiHistoryCursor = 0U;")
    e.ln("static unsigned int S_uiEscapeState = 0U; /* 0: yok, 1: ESC alindi, 2: ESC [ alindi */")
    e.ln("/* Kayitli komut tablolari (shellCommandsRegister sirasiyla). */")
    e.ln("static const SShellCommand* S_spArrTable[SHELL_TABLE_MAX];")
    e.ln("static unsigned int S_uiArrTableCount[SHELL_TABLE_MAX];")
    e.ln("static unsigned int S_uiTableCount = 0U;")
    e.blank()
    e.ln("static void shellPromptWrite(void)")
    e.ln("{")
    e.ln('    xil_printf("%s", SHELL_PROMPT);')
    e.ln("}")
    e.blank()
    # --- gecmis
    e.ln("/* --- komut gecmisi ---------------------------------------------------------------------- */")
    e.blank()
    e.ln("static void shellHistoryAdd(const char* cpLine)")
    e.ln("{")
    e.ln("    unsigned int uiLast;")
    e.blank()
    e.ln("    if (S_uiHistoryCount > 0U)")
    e.ln("    {")
    e.ln("        uiLast = (S_uiHistoryHead + SHELL_HISTORY_MAX - 1U) % SHELL_HISTORY_MAX;")
    e.ln("        if (strcmp(S_cArrHistory[uiLast], cpLine) == 0)")
    e.ln("        {")
    e.ln("            return; /* ayni komut arka arkaya: tek kayit */")
    e.ln("        }")
    e.ln("    }")
    e.ln("    (void)strncpy(S_cArrHistory[S_uiHistoryHead], cpLine, SHELL_LINE_MAX - 1U);")
    e.ln("    S_cArrHistory[S_uiHistoryHead][SHELL_LINE_MAX - 1U] = '\\0';")
    e.ln("    S_uiHistoryHead = (S_uiHistoryHead + 1U) % SHELL_HISTORY_MAX;")
    e.ln("    if (S_uiHistoryCount < SHELL_HISTORY_MAX)")
    e.ln("    {")
    e.ln("        S_uiHistoryCount++;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("/* Gezinti konumundaki kaydi (0 = en eski) satira yukler ve ekranda yeniden cizer. */")
    e.ln("static void shellHistoryLoad(unsigned int uiCursor)")
    e.ln("{")
    e.ln("    unsigned int uiIndex;")
    e.ln("    unsigned int uiSlot;")
    e.blank()
    e.ln("    for (uiIndex = 0U; uiIndex < S_uiLineLength; uiIndex++)")
    e.ln("    {")
    e.ln('        xil_printf("\\b \\b"); /* ekrandaki satiri sil */')
    e.ln("    }")
    e.ln("    S_uiLineLength = 0U;")
    e.ln("    S_cArrLine[0] = '\\0';")
    e.ln("    if (uiCursor < S_uiHistoryCount)")
    e.ln("    {")
    e.ln("        uiSlot = (S_uiHistoryHead + SHELL_HISTORY_MAX - S_uiHistoryCount + uiCursor) % SHELL_HISTORY_MAX;")
    e.ln("        (void)strncpy(S_cArrLine, S_cArrHistory[uiSlot], SHELL_LINE_MAX - 1U);")
    e.ln("        S_cArrLine[SHELL_LINE_MAX - 1U] = '\\0';")
    e.ln("        S_uiLineLength = (unsigned int)strlen(S_cArrLine);")
    e.ln('        xil_printf("%s", S_cArrLine);')
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("/* ESC [ A (yukari) / ESC [ B (asagi): 0 = tuketilmedi, 1 = kacis dizisinin parcasi. */")
    e.ln("static unsigned int shellEscapeHandle(unsigned char ucByte)")
    e.ln("{")
    e.ln("    if (S_uiEscapeState == 0U)")
    e.ln("    {")
    e.ln("        if (ucByte == 0x1BU)")
    e.ln("        {")
    e.ln("            S_uiEscapeState = 1U;")
    e.ln("            return TRUE;")
    e.ln("        }")
    e.ln("        return FALSE;")
    e.ln("    }")
    e.ln("    if (S_uiEscapeState == 1U)")
    e.ln("    {")
    e.ln("        S_uiEscapeState = (ucByte == (unsigned char)'[') ? 2U : 0U;")
    e.ln("        return TRUE;")
    e.ln("    }")
    e.ln("    S_uiEscapeState = 0U;")
    e.ln("    if (ucByte == (unsigned char)'A')")
    e.ln("    {")
    e.ln("        if (S_uiHistoryCursor > 0U)")
    e.ln("        {")
    e.ln("            S_uiHistoryCursor--;")
    e.ln("            shellHistoryLoad(S_uiHistoryCursor);")
    e.ln("        }")
    e.ln("    }")
    e.ln("    else if (ucByte == (unsigned char)'B')")
    e.ln("    {")
    e.ln("        if (S_uiHistoryCursor < S_uiHistoryCount)")
    e.ln("        {")
    e.ln("            S_uiHistoryCursor++;")
    e.ln("            shellHistoryLoad(S_uiHistoryCursor); /* count'a ulasinca bos satir */")
    e.ln("        }")
    e.ln("    }")
    e.ln("    else")
    e.ln("    {")
    e.ln("        /* sol/sag/diger CSI: yok sayilir */")
    e.ln("    }")
    e.ln("    return TRUE;")
    e.ln("}")
    e.blank()
    # --- tokenize + dagitim
    e.ln("/* --- tokenize + tablo dagitimi ---------------------------------------------------------- */")
    e.blank()
    e.ln("/* Satiri bosluklardan token'lara boler (yerinde, '\\0' ile). Donus: token sayisi. */")
    e.ln("static unsigned int shellTokenize(char* cpLine, const char* cpArrArgv[])")
    e.ln("{")
    e.ln("    unsigned int uiArgc = 0U;")
    e.blank()
    e.ln("    while ((*cpLine != '\\0') && (uiArgc < SHELL_ARG_MAX))")
    e.ln("    {")
    e.ln("        while (*cpLine == ' ')")
    e.ln("        {")
    e.ln("            cpLine++;")
    e.ln("        }")
    e.ln("        if (*cpLine == '\\0')")
    e.ln("        {")
    e.ln("            break;")
    e.ln("        }")
    e.ln("        cpArrArgv[uiArgc] = cpLine;")
    e.ln("        uiArgc++;")
    e.ln("        while ((*cpLine != '\\0') && (*cpLine != ' '))")
    e.ln("        {")
    e.ln("            cpLine++;")
    e.ln("        }")
    e.ln("        if (*cpLine == ' ')")
    e.ln("        {")
    e.ln("            *cpLine = '\\0';")
    e.ln("            cpLine++;")
    e.ln("        }")
    e.ln("    }")
    e.ln("    return uiArgc;")
    e.ln("}")
    e.blank()
    e.ln("static const SShellCommand* shellCommandFind(const char* cpName)")
    e.ln("{")
    e.ln("    unsigned int uiTable;")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln("    for (uiTable = 0U; uiTable < S_uiTableCount; uiTable++)")
    e.ln("    {")
    e.ln("        for (uiIndex = 0U; uiIndex < S_uiArrTableCount[uiTable]; uiIndex++)")
    e.ln("        {")
    e.ln("            if (strcmp(S_spArrTable[uiTable][uiIndex].cpName, cpName) == 0)")
    e.ln("            {")
    e.ln("                return &S_spArrTable[uiTable][uiIndex];")
    e.ln("            }")
    e.ln("        }")
    e.ln("    }")
    e.ln("    return NULL;")
    e.ln("}")
    e.blank()
    e.ln("static void shellLineExecute(char* cpLine)")
    e.ln("{")
    e.ln("    const char* cpArrArgv[SHELL_ARG_MAX];")
    e.ln("    const SShellCommand* spCommand;")
    e.ln("    unsigned int uiArgc;")
    e.blank()
    e.ln("    uiArgc = shellTokenize(cpLine, cpArrArgv);")
    e.ln("    if (uiArgc == 0U)")
    e.ln("    {")
    e.ln("        return;")
    e.ln("    }")
    e.ln("    spCommand = shellCommandFind(cpArrArgv[0]);")
    e.ln("    if (spCommand == NULL)")
    e.ln("    {")
    e.ln('        xil_printf("unknown command: %s (type help)\\r\\n", cpArrArgv[0]);')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    spCommand->fpHandler(uiArgc, cpArrArgv);")
    e.ln("}")
    e.blank()
    # --- public API
    e.ln("/* --- genel API -------------------------------------------------------------------------- */")
    e.blank()
    e.ln("SSistemCitBus* shellBus(void)")
    e.ln("{")
    e.ln("    return S_spBus;")
    e.ln("}")
    e.blank()
    e.ln("const SSistemCitLimit* shellLimit(void)")
    e.ln("{")
    e.ln("    return S_spLimit;")
    e.ln("}")
    e.blank()
    e.ln("SSistemCit* shellCit(void)")
    e.ln("{")
    e.ln("    return S_spCit;")
    e.ln("}")
    e.blank()
    e.ln("unsigned int shellCommandCount(void)")
    e.ln("{")
    e.ln("    unsigned int uiTable;")
    e.ln("    unsigned int uiTotal = 0U;")
    e.blank()
    e.ln("    for (uiTable = 0U; uiTable < S_uiTableCount; uiTable++)")
    e.ln("    {")
    e.ln("        uiTotal += S_uiArrTableCount[uiTable];")
    e.ln("    }")
    e.ln("    return uiTotal;")
    e.ln("}")
    e.blank()
    e.ln("const SShellCommand* shellCommandGet(unsigned int uiIndex)")
    e.ln("{")
    e.ln("    unsigned int uiTable;")
    e.blank()
    e.ln("    for (uiTable = 0U; uiTable < S_uiTableCount; uiTable++)")
    e.ln("    {")
    e.ln("        if (uiIndex < S_uiArrTableCount[uiTable])")
    e.ln("        {")
    e.ln("            return &S_spArrTable[uiTable][uiIndex];")
    e.ln("        }")
    e.ln("        uiIndex -= S_uiArrTableCount[uiTable];")
    e.ln("    }")
    e.ln("    return NULL;")
    e.ln("}")
    e.blank()
    e.ln("unsigned int shellCommandsRegister(const SShellCommand* spTable, unsigned int uiCount)")
    e.ln("{")
    e.ln("    if ((spTable == NULL) || (uiCount == 0U) || (S_uiTableCount >= SHELL_TABLE_MAX))")
    e.ln("    {")
    e.ln("        return FALSE;")
    e.ln("    }")
    e.ln("    S_spArrTable[S_uiTableCount] = spTable;")
    e.ln("    S_uiArrTableCount[S_uiTableCount] = uiCount;")
    e.ln("    S_uiTableCount++;")
    e.ln("    return TRUE;")
    e.ln("}")
    e.blank()
    e.ln("void shellInit(SSistemCitBus* spBus, const SSistemCitLimit* spLimit, SSistemCit* spCit)")
    e.ln("{")
    e.ln("    S_spBus = spBus;")
    e.ln("    S_spLimit = spLimit;")
    e.ln("    S_spCit = spCit;")
    e.ln("    S_uiLineLength = 0U;")
    e.ln("    S_cArrLine[0] = '\\0';")
    e.ln("    S_uiHistoryCount = 0U;")
    e.ln("    S_uiHistoryHead = 0U;")
    e.ln("    S_uiHistoryCursor = 0U;")
    e.ln("    S_uiEscapeState = 0U;")
    e.ln("    S_uiTableCount = 0U;")
    e.ln('    xil_printf("\\r\\nshell is initialized (type help)\\r\\n");')
    e.ln("    shellPromptWrite();")
    e.ln("}")
    e.blank()
    e.ln("void shellCheck(void)")
    e.ln("{")
    e.ln("    unsigned char ucByte;")
    e.blank()
    e.ln("    while (shellUartByteRead(&ucByte) == TRUE)")
    e.ln("    {")
    e.ln("        if (shellEscapeHandle(ucByte) == TRUE)")
    e.ln("        {")
    e.ln("            continue; /* ok tuslari: gecmis gezintisi */")
    e.ln("        }")
    e.ln("        if ((ucByte == (unsigned char)'\\r') || (ucByte == (unsigned char)'\\n'))")
    e.ln("        {")
    e.ln("            if (S_uiLineLength == 0U)")
    e.ln("            {")
    e.ln("                /* CR+LF ciftinin ikinci karakteri ya da bos satir: yalniz istem. */")
    e.ln('                xil_printf("\\r\\n");')
    e.ln("                shellPromptWrite();")
    e.ln("                continue;")
    e.ln("            }")
    e.ln('            xil_printf("\\r\\n");')
    e.ln("            S_cArrLine[S_uiLineLength] = '\\0';")
    e.ln("            shellHistoryAdd(S_cArrLine);")
    e.ln("            S_uiHistoryCursor = S_uiHistoryCount;")
    e.ln("            shellLineExecute(S_cArrLine); /* satir yerinde token'lanir (gecmis kopyasi zaten alindi) */")
    e.ln("            S_uiLineLength = 0U;")
    e.ln("            shellPromptWrite();")
    e.ln("        }")
    e.ln("        else if ((ucByte == 0x08U) || (ucByte == 0x7FU))")
    e.ln("        {")
    e.ln("            if (S_uiLineLength > 0U)")
    e.ln("            {")
    e.ln("                S_uiLineLength--;")
    e.ln('                xil_printf("\\b \\b");')
    e.ln("            }")
    e.ln("        }")
    e.ln("        else if ((ucByte >= 0x20U) && (ucByte < 0x7FU))")
    e.ln("        {")
    e.ln("            if (S_uiLineLength < (SHELL_LINE_MAX - 1U))")
    e.ln("            {")
    e.ln("                S_cArrLine[S_uiLineLength] = (char)ucByte;")
    e.ln("                S_uiLineLength++;")
    e.ln("                shellUartByteWrite(ucByte); /* yansi */")
    e.ln("            }")
    e.ln("        }")
    e.ln("        else")
    e.ln("        {")
    e.ln("            /* diger kontrol karakterleri yok sayilir */")
    e.ln("        }")
    e.ln("    }")
    e.ln("}")
    return e.text() + "\n"


# --- shell_user_commands -----------------------------------------------------------------

def user_commands_header() -> str:
    return (
        "/**\n"
        " * @file shell_user_commands.h\n"
        " * @brief Shell komut tablosu: cit, i2c_search, sdl, help, mod ... - kendi komutlarini buraya eklersin.\n"
        " *\n"
        " * Yeni komut eklemek icin:\n"
        " *   1. shell_user_commands.c'de `static void shellUser<Ad>(unsigned int uiArgc, const char* cpArrArgv[])`\n"
        " *      isleyicisini yaz (cpArrArgv[1..] STRING; sayi gerekiyorsa atoi/strtol).\n"
        ' *   2. S_sArrUserCommands[] tablosuna `{"<konsol adi>", shellUser<Ad>, "<args>  aciklama"}` satiri ekle.\n'
        " *   Baska hicbir yere dokunma: main.c tabloyu shellCommandsRegister ile bir kez kaydeder,\n"
        " *   `help` yeni satiri kendiliginden listeler.\n"
        " *\n"
        " * Generated by Spec2Code (ornek icerik; kendi projende serbestce duzenle).\n"
        " */\n"
        "#ifndef SHELL_USER_COMMANDS_H\n"
        "#define SHELL_USER_COMMANDS_H\n\n"
        '#include "shell.h"\n\n'
        "/* Komut tablosu ve eleman sayisi (main.c: shellCommandsRegister(...)). */\n"
        "const SShellCommand* shellUserCommandTable(void);\n"
        "unsigned int shellUserCommandCount(void);\n\n"
        "#endif /* SHELL_USER_COMMANDS_H */\n"
    )


def user_commands_source(spec: dict, plans: list) -> str:
    """Tum komutlar: cit, i2c_search, sdl, help (spec'e gore uretilir) + ornek mod. Tek tablo."""
    i2c = _i2c_bus_entries(spec, plans)
    htypes = sorted({h for _, _, h in i2c})
    mux_addrs = _mux_addresses(spec)
    ips = custom_ips(spec)
    e = cit_layer._E(0)
    e.ln("/**")
    e.ln(" * @file shell_user_commands.c")
    e.ln(" * @brief TUM shell komutlari tek tabloda: cit, i2c_search, sdl, help ve ornek `mod <x> <y>`.")
    e.ln(" *")
    e.ln(" * Yeni komut = asagiya bir isleyici + S_sArrUserCommands[]'a bir satir. Argumanlar STRING")
    e.ln(" * (cpArrArgv[1..]); sayi gerekiyorsa atoi/strtol. `help` tabloyu kendiliginden listeler.")
    e.ln(" *")
    e.ln(" *   > mod 3 open     -> Xil_Out32(SHELL_USER_MOD_BASEADDR + 3*4, 0x04040404)")
    e.ln(" *   > mod 3 close    -> Xil_Out32(SHELL_USER_MOD_BASEADDR + 3*4, 0)")
    e.ln(" *   > mod 3 test     -> open, AXI INTC kesmesini bekle (1 s), 14 konnektor durumunu bas, close")
    e.ln(' *   x: 0..7 (register indeksi, 4 baytlik ofsetle), y: "open" | "close".')
    e.ln(" *")
    e.ln(" * Generated by Spec2Code (kendi projende serbestce duzenle).")
    e.ln(" */")
    e.ln('#include "shell_user_commands.h"')
    e.ln('#include "dbg_printf.h"')
    e.ln('#include "xil_io.h"')
    e.ln('#include "xparameters.h"')
    e.ln("#ifdef XPAR_XINTC_NUM_INSTANCES")
    e.ln('#include "xintc.h"')
    e.ln('#include "xil_exception.h"')
    e.ln('#include "sleep.h"')
    e.ln("#endif")
    e.ln('#include "xil_printf.h"')
    e.ln('#include "xstatus.h"')
    for ip in known_ip_maps(spec):
        e.ln(f'#include "{ip["id"]}_shell.h" /* bilinen IP ({ip["ip_name"]}) register haritasi: drivers/ip */')
    if "XIic" in htypes:
        e.ln('#include "xiic.h"')
        e.ln('#include "xiic_l.h"')
    if "XIicPs" in htypes:
        e.ln('#include "xiicps.h"')
    e.ln("#include <stddef.h>")
    e.ln("#include <stdlib.h>")
    e.ln("#include <string.h>")
    e.blank()
    e.ln("/* --- mod: GPIO loopback test IP'si -----------------------------------------------------")
    e.ln(" * reg0..reg7   : 8 test modu; desen yaz = test basla, 0 yaz = bitir (open / close).")
    e.ln(" * reg8..reg21  : 14 konnektorun durum registeri; bit = GPIO, 0 = OK, 1 = HATA (32 bit basilir,")
    e.ln(" *                kullanilmayan bitler donanimda 0 kalir).")
    e.ln(" * Test bitince IP AXI INTC uzerinden (rising edge) kesme uretir; `mod <x> test` desen yazar,")
    e.ln(" * kesmeyi 1 s bekler, 14 durumu renkli basar (0 yesil, 1 kirmizi) ve 0 yazarak kapatir.")
    e.ln(" * TODO (projeye gore): SHELL_USER_MOD_BASEADDR = XPAR_<IP>_BASEADDR,")
    e.ln(" *   SHELL_USER_MOD_INTR_ID = XPAR_INTC_0_<IP>_<PORT>_VEC_ID (xparameters.h). */")
    e.ln("#ifndef SHELL_USER_MOD_BASEADDR")
    e.ln("#define SHELL_USER_MOD_BASEADDR 0x00000000U")
    e.ln("#endif")
    e.ln("#ifndef SHELL_USER_MOD_INTR_ID")
    e.ln("#define SHELL_USER_MOD_INTR_ID 0U /* TODO: XPAR_INTC_0_<IP>_..._VEC_ID */")
    e.ln("#define SHELL_USER_MOD_INTR_ID_UNSET 1 /* ayarlanana kadar `mod test` uyarir */")
    e.ln("#endif")
    intc_suffix = lookup_suffix(is_sdt(spec))
    intc_default = "XPAR_XINTC_0_BASEADDR" if is_sdt(spec) else "XPAR_INTC_0_DEVICE_ID"
    e.ln(f"#if defined(XPAR_XINTC_NUM_INSTANCES) && !defined(SHELL_USER_MOD_INTC_{intc_suffix})")
    e.ln(f"#define SHELL_USER_MOD_INTC_{intc_suffix} {intc_default}")
    e.ln("#endif")
    e.ln("#define SHELL_USER_MOD_REG_COUNT 8U")
    e.ln("#define SHELL_USER_MOD_CONNECTOR_COUNT 14U")
    e.ln("#define SHELL_USER_MOD_STATUS_OFFSET (SHELL_USER_MOD_REG_COUNT * 4U)")
    e.ln("#define SHELL_USER_MOD_TEST_TIMEOUT_MS 1000U")
    e.ln('#define SHELL_USER_MOD_COLOR_OK "\\033[32m"')
    e.ln('#define SHELL_USER_MOD_COLOR_ERR "\\033[31m"')
    e.ln('#define SHELL_USER_MOD_COLOR_RESET "\\033[0m"')
    e.blank()
    e.ln('/* reg0..reg7\'ye "open" ile yazilacak desenler (reg x -> (x+1) tekrarli bayt: reg0 0x01010101 ...')
    e.ln(' * reg7 0x08080808; kullanici istegi 2026-09-09, 0x00000000 ile baslamaz); "close" 0 yazar. */')
    e.ln("static const unsigned int S_uiArrModValue[SHELL_USER_MOD_REG_COUNT] = {")
    e.ln("    0x01010101U, 0x02020202U, 0x03030303U, 0x04040404U, 0x05050505U, 0x06060606U, 0x07070707U, 0x08080808U,")
    e.ln("};")
    if mux_addrs:
        e.ln("/* I2C switch adresleri: taramada atlanir (0x00 yazmak secili kanali kapatirdi). */")
        e.ln("static const unsigned int S_uiArrSwitchAddress[] = {" + ", ".join(f"0x{a:02X}U" for a in mux_addrs) + "};")
    if i2c:
        e.ln("/* Spec'teki I2C cihazlari (adres -> kimlik): i2c_search ACK satirini etiketler. */")
        e.ln("typedef struct")
        e.ln("{")
        e.ln("    unsigned int uiAddress;")
        e.ln("    const char* cpName;")
        e.ln("} SShellUserI2cDevice;")
        for cid, _, _ in i2c:
            names = _i2c_device_names(spec, cid)
            entries = ", ".join(f'{{0x{a:02X}U, "{n}"}}' for a, n in names) or '{0xFFU, ""}'
            e.ln(f"static const SShellUserI2cDevice {_i2c_table_name(cid)}[] = {{{entries}}};")
    if len(i2c) > 1:
        e.ln("static unsigned int S_uiI2cBus = 0U; /* i2c_read/i2c_write'in kullandigi denetleyici (i2c_bus ile secilir) */")
    e.blank()
    e.ln("/* String arguman -> sayi (0x.. hex ya da ondalik). Bozuk metin FALSE. */")
    e.ln("static unsigned int shellUserParseNumber(const char* cpText, unsigned long* ulpValue)")
    e.ln("{")
    e.ln("    char* cpEnd = NULL;")
    e.blank()
    e.ln("    if ((cpText == NULL) || (cpText[0] == '\\0'))")
    e.ln("    {")
    e.ln("        return FALSE;")
    e.ln("    }")
    e.ln("    *ulpValue = strtoul(cpText, &cpEnd, 0);")
    e.ln("    return ((cpEnd != NULL) && (*cpEnd == '\\0')) ? TRUE : FALSE;")
    e.ln("}")
    e.blank()
    e.ln("/* mem <addr> [value]: 32-bit register oku / yaz (Xil_In32 / Xil_Out32), yazdiktan sonra geri okur. */")
    e.ln("static void shellUserMem(unsigned int uiArgc, const char* cpArrArgv[])")
    e.ln("{")
    e.ln("    unsigned long ulAddress;")
    e.ln("    unsigned long ulValue;")
    e.blank()
    e.ln("    if ((uiArgc < 2U) || (uiArgc > 3U) || (shellUserParseNumber(cpArrArgv[1], &ulAddress) == FALSE))")
    e.ln("    {")
    e.ln('        xil_printf("usage: mem <addr> [value]   (hex 0x.. or decimal)\\r\\n");')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    if ((ulAddress & 3UL) != 0UL)")
    e.ln("    {")
    e.ln('        xil_printf("mem: address must be 4-byte aligned\\r\\n");')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    if (uiArgc == 3U)")
    e.ln("    {")
    e.ln("        if (shellUserParseNumber(cpArrArgv[2], &ulValue) == FALSE)")
    e.ln("        {")
    e.ln('            xil_printf("mem: bad value \'%s\'\\r\\n", cpArrArgv[2]);')
    e.ln("            return;")
    e.ln("        }")
    e.ln("        Xil_Out32((UINTPTR)ulAddress, (u32)ulValue);")
    e.ln("    }")
    e.ln('    xil_printf("0x%08X = 0x%08X\\r\\n", (unsigned int)ulAddress, (unsigned int)Xil_In32((UINTPTR)ulAddress));')
    e.ln("}")
    e.blank()
    if ips:
        e.ln("/* --- custom IP register erisimi: <id> dump | read <n> | write <n> <value> ------------------")
        e.ln(" * n = register numarasi (0'dan baslar, her biri 4 bayt: adres = base + 4*n); XSA'daki adres")
        e.ln(" * araligiyla (register_count) sinirlidir. dump tum araligi 4'er bayt okur. */")
        e.ln("static void shellUserCustomIp(const char* cpName, unsigned int uiBase, unsigned int uiCount, unsigned int uiArgc, const char* cpArrArgv[])")
        e.ln("{")
        e.ln("    unsigned long ulIndex;")
        e.ln("    unsigned long ulValue;")
        e.ln("    unsigned int uiIndex;")
        e.blank()
        e.ln('    if ((uiArgc >= 2U) && (strcmp(cpArrArgv[1], "dump") == 0))')
        e.ln("    {")
        e.ln('        xil_printf("%s: base 0x%08X, %u registers\\r\\n", cpName, uiBase, uiCount);')
        e.ln("        for (uiIndex = 0U; uiIndex < uiCount; uiIndex++)")
        e.ln("        {")
        e.ln("            if ((uiIndex % 4U) == 0U)")
        e.ln("            {")
        e.ln('                xil_printf("  reg%4u @0x%08X:", uiIndex, uiBase + (uiIndex * 4U));')
        e.ln("            }")
        e.ln('            xil_printf(" %08X", (unsigned int)Xil_In32((UINTPTR)uiBase + ((UINTPTR)uiIndex * 4U)));')
        e.ln("            if (((uiIndex % 4U) == 3U) || (uiIndex == (uiCount - 1U)))")
        e.ln("            {")
        e.ln('                xil_printf("\\r\\n");')
        e.ln("            }")
        e.ln("        }")
        e.ln("        return;")
        e.ln("    }")
        e.ln('    if ((uiArgc >= 3U) && (strcmp(cpArrArgv[1], "read") == 0) && (shellUserParseNumber(cpArrArgv[2], &ulIndex) == TRUE))')
        e.ln("    {")
        e.ln("        if (ulIndex >= (unsigned long)uiCount)")
        e.ln("        {")
        e.ln('            xil_printf("%s: register %lu out of range (0..%u)\\r\\n", cpName, ulIndex, uiCount - 1U);')
        e.ln("            return;")
        e.ln("        }")
        e.ln('        xil_printf("%s reg%lu @0x%08X = 0x%08X\\r\\n", cpName, ulIndex, uiBase + ((unsigned int)ulIndex * 4U),')
        e.ln("                   (unsigned int)Xil_In32((UINTPTR)uiBase + ((UINTPTR)ulIndex * 4U)));")
        e.ln("        return;")
        e.ln("    }")
        e.ln('    if ((uiArgc >= 4U) && (strcmp(cpArrArgv[1], "write") == 0) && (shellUserParseNumber(cpArrArgv[2], &ulIndex) == TRUE) &&')
        e.ln("        (shellUserParseNumber(cpArrArgv[3], &ulValue) == TRUE))")
        e.ln("    {")
        e.ln("        if (ulIndex >= (unsigned long)uiCount)")
        e.ln("        {")
        e.ln('            xil_printf("%s: register %lu out of range (0..%u)\\r\\n", cpName, ulIndex, uiCount - 1U);')
        e.ln("            return;")
        e.ln("        }")
        e.ln("        Xil_Out32((UINTPTR)uiBase + ((UINTPTR)ulIndex * 4U), (u32)ulValue);")
        e.ln('        xil_printf("%s reg%lu @0x%08X <= 0x%08X, readback 0x%08X\\r\\n", cpName, ulIndex, uiBase + ((unsigned int)ulIndex * 4U),')
        e.ln("                   (unsigned int)ulValue, (unsigned int)Xil_In32((UINTPTR)uiBase + ((UINTPTR)ulIndex * 4U)));")
        e.ln("        return;")
        e.ln("    }")
        e.ln('    xil_printf("usage: %s dump | read <n> | write <n> <value>   (n = 0..%u, 4-byte registers)\\r\\n", cpName, uiCount - 1U);')
        e.ln("}")
        e.blank()
        for ip in ips:
            note = f"{ip['instance']}" + (f", {ip['ip_name']}" if ip["ip_name"] else "")
            e.ln(f"/* {ip['id']}: {note}; base 0x{ip['base']:08X}, {ip['count']} x 4 B (XSA adres araligi). */")
            e.ln(f"static void {_custom_ip_handler(ip['id'])}(unsigned int uiArgc, const char* cpArrArgv[])")
            e.ln("{")
            e.ln(f'    shellUserCustomIp("{ip["id"]}", 0x{ip["base"]:08X}U, {ip["count"]}U, uiArgc, cpArrArgv);')
            e.ln("}")
            e.blank()
    e.ln("/* cit: sistemCitRead kosar. Rapor dbg_printf INFO satirlaridir: gorunmesi icin `sdl info` (ya da ustu);")
    e.ln(" * esik burada DEGISTIRILMEZ (kullanici istegi), sonuc satiri her zaman basilir. */")
    e.ln("static void shellUserCit(unsigned int uiArgc, const char* cpArrArgv[])")
    e.ln("{")
    e.ln("    int iResult;")
    e.blank()
    e.ln("    (void)uiArgc;")
    e.ln("    (void)cpArrArgv;")
    e.ln("    if ((shellBus() == NULL) || (shellCit() == NULL))")
    e.ln("    {")
    e.ln('        xil_printf("cit: shell is not initialized\\r\\n");')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    iResult = sistemCitRead(shellBus(), shellLimit(), shellCit());")
    e.ln(f'    xil_printf("cit: %s (run #%u)\\r\\n", (iResult == {cit_layer.STATUS_OK}) ? "OK" : ((iResult == {cit_layer.STATUS_NOK}) ? "NOK" : "ERROR"), shellCit()->uiSayac);')
    e.ln("}")
    e.blank()
    if i2c:
        e.ln("static const char* shellUserI2cDeviceName(const SShellUserI2cDevice* spTable, unsigned int uiCount, unsigned int uiAddress)")
        e.ln("{")
        e.ln("    unsigned int uiIndex;")
        e.blank()
        e.ln("    for (uiIndex = 0U; uiIndex < uiCount; uiIndex++)")
        e.ln("    {")
        e.ln("        if (spTable[uiIndex].uiAddress == uiAddress)")
        e.ln("        {")
        e.ln("            return spTable[uiIndex].cpName;")
        e.ln("        }")
        e.ln("    }")
        e.ln('    return "(not in spec)";')
        e.ln("}")
        e.blank()
        if mux_addrs:
            e.ln("static unsigned int shellUserI2cIsSwitchAddress(unsigned int uiAddress)")
            e.ln("{")
            e.ln("    unsigned int uiIndex;")
            e.blank()
            e.ln("    for (uiIndex = 0U; uiIndex < (sizeof(S_uiArrSwitchAddress) / sizeof(S_uiArrSwitchAddress[0])); uiIndex++)")
            e.ln("    {")
            e.ln("        if (S_uiArrSwitchAddress[uiIndex] == uiAddress)")
            e.ln("        {")
            e.ln("            return TRUE;")
            e.ln("        }")
            e.ln("    }")
            e.ln("    return FALSE;")
            e.ln("}")
            e.blank()
        for htype in htypes:
            e.ln(f"static unsigned int shellUserI2cProbe{htype}({htype}* spIic, unsigned int uiAddress)")
            e.ln("{")
            e.ln("    unsigned char ucProbe = 0x00U;")
            if htype == "XIic":
                e.blank()
                e.ln("    /* Dinamik mod: gonderilen bayt sayisi 1 ise ACK alindi. */")
                e.ln("    return ((unsigned int)XIic_DynSend(spIic->BaseAddress, (unsigned short)uiAddress, &ucProbe, 1U, XIIC_STOP) == 1U) ? TRUE : FALSE;")
            else:
                e.ln("    int iStatus;")
                e.blank()
                e.ln("    iStatus = XIicPs_MasterSendPolled(spIic, &ucProbe, 1, (unsigned short)uiAddress);")
                e.ln("    while (XIicPs_BusIsBusy(spIic) == TRUE)")
                e.ln("    {")
                e.ln("        /* bus bosalana kadar bekle */")
                e.ln("    }")
                e.ln("    return (iStatus == XST_SUCCESS) ? TRUE : FALSE;")
            e.ln("}")
            e.blank()
            # Ham yazma / register okuma (i2c_write, i2c_read)
            e.ln(f"static unsigned int shellUserI2cWrite{htype}({htype}* spIic, unsigned int uiAddress, unsigned char* ucpData, unsigned int uiCount)")
            e.ln("{")
            if htype == "XIic":
                e.ln("    return ((unsigned int)XIic_DynSend(spIic->BaseAddress, (unsigned short)uiAddress, ucpData, (unsigned char)uiCount, XIIC_STOP) == uiCount) ? TRUE : FALSE;")
            else:
                e.ln("    int iStatus;")
                e.blank()
                e.ln("    iStatus = XIicPs_MasterSendPolled(spIic, ucpData, (int)uiCount, (unsigned short)uiAddress);")
                e.ln("    while (XIicPs_BusIsBusy(spIic) == TRUE)")
                e.ln("    {")
                e.ln("        /* bus bosalana kadar bekle */")
                e.ln("    }")
                e.ln("    return (iStatus == XST_SUCCESS) ? TRUE : FALSE;")
            e.ln("}")
            e.blank()
            e.ln(f"static unsigned int shellUserI2cRead{htype}({htype}* spIic, unsigned int uiAddress, unsigned char ucRegister, unsigned char* ucpData, unsigned int uiCount)")
            e.ln("{")
            if htype == "XIic":
                e.ln("    if ((unsigned int)XIic_DynSend(spIic->BaseAddress, (unsigned short)uiAddress, &ucRegister, 1U, XIIC_REPEATED_START) != 1U)")
                e.ln("    {")
                e.ln("        return FALSE;")
                e.ln("    }")
                e.ln("    return ((unsigned int)XIic_DynRecv(spIic->BaseAddress, (unsigned char)uiAddress, ucpData, (unsigned char)uiCount) == uiCount) ? TRUE : FALSE;")
            else:
                e.ln("    int iStatus;")
                e.blank()
                e.ln("    iStatus = XIicPs_MasterSendPolled(spIic, &ucRegister, 1, (unsigned short)uiAddress);")
                e.ln("    while (XIicPs_BusIsBusy(spIic) == TRUE)")
                e.ln("    {")
                e.ln("        /* bus bosalana kadar bekle */")
                e.ln("    }")
                e.ln("    if (iStatus != XST_SUCCESS)")
                e.ln("    {")
                e.ln("        return FALSE;")
                e.ln("    }")
                e.ln("    iStatus = XIicPs_MasterRecvPolled(spIic, ucpData, (int)uiCount, (unsigned short)uiAddress);")
                e.ln("    while (XIicPs_BusIsBusy(spIic) == TRUE)")
                e.ln("    {")
                e.ln("        /* bus bosalana kadar bekle */")
                e.ln("    }")
                e.ln("    return (iStatus == XST_SUCCESS) ? TRUE : FALSE;")
            e.ln("}")
            e.blank()
        # Secili denetleyiciye dagitim (tek denetleyicide dogrudan).
        bus_expr = "S_uiI2cBus" if len(i2c) > 1 else "0U"
        e.ln("static unsigned int shellUserI2cBusWrite(unsigned int uiAddress, unsigned char* ucpData, unsigned int uiCount)")
        e.ln("{")
        e.ln(f"    switch ({bus_expr})")
        e.ln("    {")
        for index, (cid, fld, htype) in enumerate(i2c):
            e.ln(f"        case {index}U:")
            e.ln(f"            return shellUserI2cWrite{htype}(shellBus()->{fld}, uiAddress, ucpData, uiCount);")
        e.ln("        default:")
        e.ln("            return FALSE;")
        e.ln("    }")
        e.ln("}")
        e.blank()
        e.ln("static unsigned int shellUserI2cBusRead(unsigned int uiAddress, unsigned char ucRegister, unsigned char* ucpData, unsigned int uiCount)")
        e.ln("{")
        e.ln(f"    switch ({bus_expr})")
        e.ln("    {")
        for index, (cid, fld, htype) in enumerate(i2c):
            e.ln(f"        case {index}U:")
            e.ln(f"            return shellUserI2cRead{htype}(shellBus()->{fld}, uiAddress, ucRegister, ucpData, uiCount);")
        e.ln("        default:")
        e.ln("            return FALSE;")
        e.ln("    }")
        e.ln("}")
        e.blank()
        if len(i2c) > 1:
            e.ln("static const char* const S_cpArrI2cBusName[] = {" + ", ".join(f'"{cid}"' for cid, _, _ in i2c) + "};")
            e.blank()
            e.ln("/* i2c_bus [id]: i2c_read/i2c_write icin denetleyici sec ya da listele. */")
            e.ln("static void shellUserI2cBus(unsigned int uiArgc, const char* cpArrArgv[])")
            e.ln("{")
            e.ln("    unsigned int uiIndex;")
            e.blank()
            e.ln("    for (uiIndex = 0U; uiIndex < (sizeof(S_cpArrI2cBusName) / sizeof(S_cpArrI2cBusName[0])); uiIndex++)")
            e.ln("    {")
            e.ln("        if ((uiArgc >= 2U) && (strcmp(cpArrArgv[1], S_cpArrI2cBusName[uiIndex]) == 0))")
            e.ln("        {")
            e.ln("            S_uiI2cBus = uiIndex;")
            e.ln("        }")
            e.ln("    }")
            e.ln("    for (uiIndex = 0U; uiIndex < (sizeof(S_cpArrI2cBusName) / sizeof(S_cpArrI2cBusName[0])); uiIndex++)")
            e.ln("    {")
            e.ln('        xil_printf("  %s %s\\r\\n", (uiIndex == S_uiI2cBus) ? "*" : " ", S_cpArrI2cBusName[uiIndex]);')
            e.ln("    }")
            e.ln("}")
            e.blank()
        e.ln("/* i2c_write <addr> <byte...>: ham bayt dizisi yaz (ilk bayt genelde register adresi). */")
        e.ln("static void shellUserI2cWrite(unsigned int uiArgc, const char* cpArrArgv[])")
        e.ln("{")
        e.ln("    unsigned char ucArrData[SHELL_ARG_MAX];")
        e.ln("    unsigned long ulAddress;")
        e.ln("    unsigned long ulValue;")
        e.ln("    unsigned int uiIndex;")
        e.blank()
        e.ln("    if ((uiArgc < 3U) || (shellUserParseNumber(cpArrArgv[1], &ulAddress) == FALSE) || (ulAddress > 0x7FUL))")
        e.ln("    {")
        e.ln('        xil_printf("usage: i2c_write <addr> <byte> [byte ...]   (hex 0x.. or decimal)\\r\\n");')
        e.ln("        return;")
        e.ln("    }")
        e.ln("    for (uiIndex = 2U; uiIndex < uiArgc; uiIndex++)")
        e.ln("    {")
        e.ln("        if ((shellUserParseNumber(cpArrArgv[uiIndex], &ulValue) == FALSE) || (ulValue > 0xFFUL))")
        e.ln("        {")
        e.ln('            xil_printf("i2c_write: bad byte \'%s\'\\r\\n", cpArrArgv[uiIndex]);')
        e.ln("            return;")
        e.ln("        }")
        e.ln("        ucArrData[uiIndex - 2U] = (unsigned char)ulValue;")
        e.ln("    }")
        e.ln("    if (shellUserI2cBusWrite((unsigned int)ulAddress, ucArrData, uiArgc - 2U) == TRUE)")
        e.ln("    {")
        e.ln('        xil_printf("i2c_write 0x%02X: %u byte(s) OK\\r\\n", (unsigned int)ulAddress, uiArgc - 2U);')
        e.ln("    }")
        e.ln("    else")
        e.ln("    {")
        e.ln('        xil_printf("i2c_write 0x%02X: NACK / bus error\\r\\n", (unsigned int)ulAddress);')
        e.ln("    }")
        e.ln("}")
        e.blank()
        e.ln("/* i2c_read <addr> <reg> [n]: register adresini yaz, n bayt oku (varsayilan 1, en fazla 16). */")
        e.ln("static void shellUserI2cRead(unsigned int uiArgc, const char* cpArrArgv[])")
        e.ln("{")
        e.ln("    unsigned char ucArrData[16];")
        e.ln("    unsigned long ulAddress;")
        e.ln("    unsigned long ulRegister;")
        e.ln("    unsigned long ulCount = 1UL;")
        e.ln("    unsigned int uiIndex;")
        e.blank()
        e.ln("    if ((uiArgc < 3U) || (uiArgc > 4U) || (shellUserParseNumber(cpArrArgv[1], &ulAddress) == FALSE) || (ulAddress > 0x7FUL) ||")
        e.ln("        (shellUserParseNumber(cpArrArgv[2], &ulRegister) == FALSE) || (ulRegister > 0xFFUL) ||")
        e.ln("        ((uiArgc == 4U) && ((shellUserParseNumber(cpArrArgv[3], &ulCount) == FALSE) || (ulCount < 1UL) || (ulCount > 16UL))))")
        e.ln("    {")
        e.ln('        xil_printf("usage: i2c_read <addr> <reg> [n=1..16]   (hex 0x.. or decimal)\\r\\n");')
        e.ln("        return;")
        e.ln("    }")
        e.ln("    if (shellUserI2cBusRead((unsigned int)ulAddress, (unsigned char)ulRegister, ucArrData, (unsigned int)ulCount) == FALSE)")
        e.ln("    {")
        e.ln('        xil_printf("i2c_read 0x%02X: NACK / bus error\\r\\n", (unsigned int)ulAddress);')
        e.ln("        return;")
        e.ln("    }")
        e.ln('    xil_printf("0x%02X reg 0x%02X:", (unsigned int)ulAddress, (unsigned int)ulRegister);')
        e.ln("    for (uiIndex = 0U; uiIndex < (unsigned int)ulCount; uiIndex++)")
        e.ln("    {")
        e.ln('        xil_printf(" %02X", (unsigned int)ucArrData[uiIndex]);')
        e.ln("    }")
        e.ln('    xil_printf("\\r\\n");')
        e.ln("}")
        e.blank()
        e.ln("static void shellUserI2cSearch(unsigned int uiArgc, const char* cpArrArgv[])")
        e.ln("{")
        e.ln("    unsigned int uiAddress;")
        e.ln("    unsigned int uiFound;")
        e.blank()
        e.ln("    (void)uiArgc;")
        e.ln("    (void)cpArrArgv;")
        e.ln("    if (shellBus() == NULL)")
        e.ln("    {")
        e.ln('        xil_printf("i2c_search: shell is not initialized\\r\\n");')
        e.ln("        return;")
        e.ln("    }")
        for cid, fld, htype in i2c:
            table = _i2c_table_name(cid)
            e.ln(f'    xil_printf("{cid}: scanning 0x08..0x77\\r\\n");')
            e.ln("    uiFound = 0U;")
            e.ln("    for (uiAddress = 0x08U; uiAddress <= 0x77U; uiAddress++)")
            e.ln("    {")
            if mux_addrs:
                e.ln("        if (shellUserI2cIsSwitchAddress(uiAddress) == TRUE)")
                e.ln("        {")
                e.ln('            xil_printf("  0x%02X  (I2C switch, skipped)\\r\\n", uiAddress);')
                e.ln("            continue;")
                e.ln("        }")
            e.ln(f"        if (shellUserI2cProbe{htype}(shellBus()->{fld}, uiAddress) == TRUE)")
            e.ln("        {")
            e.ln(f'            xil_printf("  0x%02X  ACK  %s\\r\\n", uiAddress, shellUserI2cDeviceName({table}, sizeof({table}) / sizeof({table}[0]), uiAddress));')
            e.ln("            uiFound++;")
            e.ln("        }")
            e.ln("    }")
            e.ln(f'    xil_printf("{cid}: %u device(s)\\r\\n", uiFound);')
        e.ln("}")
    else:
        e.ln("static void shellUserI2cSearch(unsigned int uiArgc, const char* cpArrArgv[])")
        e.ln("{")
        e.ln("    (void)uiArgc;")
        e.ln("    (void)cpArrArgv;")
        e.ln('    xil_printf("i2c_search: no I2C controller in this project\\r\\n");')
        e.ln("}")
    e.blank()
    e.ln("static void shellUserSdl(unsigned int uiArgc, const char* cpArrArgv[])")
    e.ln("{")
    e.ln('    static const char* const S_cpArrLevelName[] = {"always", "error", "warning", "msg", "info", "trace"};')
    e.ln("    const char* cpArgument;")
    e.ln("    unsigned int uiLevel;")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln("    if (uiArgc < 2U)")
    e.ln("    {")
    e.ln('        xil_printf("log level: %s (%u)\\r\\n", dbgLevelName(dbgLevelGet()), dbgLevelGet());')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    cpArgument = cpArrArgv[1];")
    e.ln("    uiLevel = DEBUG_LEVEL_TRACE + 1U; /* gecersiz */")
    e.ln("    for (uiIndex = 0U; uiIndex <= DEBUG_LEVEL_TRACE; uiIndex++)")
    e.ln("    {")
    e.ln("        if (strcmp(cpArgument, S_cpArrLevelName[uiIndex]) == 0)")
    e.ln("        {")
    e.ln("            uiLevel = uiIndex;")
    e.ln("        }")
    e.ln("    }")
    e.ln("    if ((uiLevel > DEBUG_LEVEL_TRACE) && (cpArgument[0] >= '0') && (cpArgument[0] <= '5') && (cpArgument[1] == '\\0'))")
    e.ln("    {")
    e.ln("        uiLevel = (unsigned int)(cpArgument[0] - '0');")
    e.ln("    }")
    e.ln("    if (uiLevel > DEBUG_LEVEL_TRACE)")
    e.ln("    {")
    e.ln('        xil_printf("sdl: invalid level \'%s\' (error|warning|msg|info|trace|0..5)\\r\\n", cpArgument);')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    (void)dbgLevelSet(uiLevel);")
    e.ln('    xil_printf("log level: %s (%u)\\r\\n", dbgLevelName(dbgLevelGet()), dbgLevelGet());')
    e.ln("}")
    e.blank()
    e.ln("static void shellUserHelp(unsigned int uiArgc, const char* cpArrArgv[])")
    e.ln("{")
    e.ln("    const SShellCommand* spCommand;")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln("    (void)uiArgc;")
    e.ln("    (void)cpArrArgv;")
    e.ln('    xil_printf("commands:\\r\\n");')
    e.ln("    for (uiIndex = 0U; uiIndex < shellCommandCount(); uiIndex++)")
    e.ln("    {")
    e.ln("        spCommand = shellCommandGet(uiIndex);")
    e.ln('        xil_printf("  %-12s %s\\r\\n", spCommand->cpName, spCommand->cpHelp);')
    e.ln("    }")
    e.ln("}")
    e.blank()
    mod_handler = _MOD_HANDLER.replace("SHELL_USER_MOD_INTC_DEVICE_ID", f"SHELL_USER_MOD_INTC_{lookup_suffix(is_sdt(spec))}")
    for line in mod_handler.splitlines():
        e.ln(line)
    e.blank()
    e.ln("/* KOMUT TABLOSU: konsol adi, isleyici, help satiri. Yeni komut = bir satir. */")
    e.ln("static const SShellCommand S_sArrUserCommands[] = {")
    e.ln('    {"cit", shellUserCit, "read all devices, print the report"},')
    e.ln('    {"i2c_search", shellUserI2cSearch, "scan I2C addresses 0x08..0x77"},')
    if i2c:
        if len(i2c) > 1:
            e.ln('    {"i2c_bus", shellUserI2cBus, "[id]  select/list the I2C controller for i2c_read/i2c_write"},')
        e.ln('    {"i2c_read", shellUserI2cRead, "<addr> <reg> [n]  write reg pointer, read n bytes (default 1)"},')
        e.ln('    {"i2c_write", shellUserI2cWrite, "<addr> <byte...>  write raw bytes (first byte usually the reg)"},')
    e.ln('    {"mem", shellUserMem, "<addr> [value]  read / write a 32-bit register (Xil_In32/Xil_Out32)"},')
    for ip in ips:
        e.ln(f'    {{"{ip["id"]}", {_custom_ip_handler(ip["id"])}, "dump | read <n> | write <n> <value>  custom IP @0x{ip["base"]:08X}, {ip["count"]} regs"}},')
    for ip in known_ip_maps(spec):
        e.ln(f'    {{"ip_{ip["id"]}", {_known_ip_handler(ip["id"])}, "rd|wr <REG>[.<FIELD>] [value] | dump | help  {ip["ip_name"]} @0x{ip["base"]:08X} (register adlariyla)"}},')
    e.ln('    {"sdl", shellUserSdl, "<level>  set debug level: error|warning|msg|info|trace (0..5)"},')
    e.ln('    {"help", shellUserHelp, "list commands"},')
    e.ln('    {"mod", shellUserMod, "<0..7> <open|close|test>  gpio loopback IP: open=pattern, close=0, test=open+irq wait+14 status+close"},')
    e.ln("};")
    e.blank()
    e.ln("const SShellCommand* shellUserCommandTable(void)")
    e.ln("{")
    e.ln("    return S_sArrUserCommands;")
    e.ln("}")
    e.blank()
    e.ln("unsigned int shellUserCommandCount(void)")
    e.ln("{")
    e.ln("    return (unsigned int)(sizeof(S_sArrUserCommands) / sizeof(S_sArrUserCommands[0]));")
    e.ln("}")
    return e.text() + "\n"


_MOD_HANDLER = (
        "#ifdef XPAR_XINTC_NUM_INSTANCES\n"
        "static XIntc S_sModIntc;\n"
        "static unsigned int S_uiModIntcReady = 0U;\n"
        "/* Kesme isleyicisi yalniz bayragi kurar; okuma/kapatma ana dongude (yazilim kontrollu). */\n"
        "static volatile unsigned int S_uiModTestDone = 0U;\n\n"
        "static void shellUserModInterruptHandler(void* pvArgument)\n"
        "{\n"
        "    (void)pvArgument;\n"
        "    S_uiModTestDone = 1U;\n"
        "}\n\n"
        "/* AXI INTC'yi ilk `mod test`te kurar: baglan, etkinlestir, islemci kesmesini ac. */\n"
        "static unsigned int shellUserModIntcInit(void)\n"
        "{\n"
        "    if (S_uiModIntcReady == 1U)\n"
        "    {\n"
        "        return TRUE;\n"
        "    }\n"
        "    if (XIntc_Initialize(&S_sModIntc, SHELL_USER_MOD_INTC_DEVICE_ID) != XST_SUCCESS)\n"
        "    {\n"
        '        xil_printf("mod: XIntc_Initialize failed (SHELL_USER_MOD_INTC_DEVICE_ID)\\r\\n");\n'
        "        return FALSE;\n"
        "    }\n"
        "    if (XIntc_Connect(&S_sModIntc, (u8)SHELL_USER_MOD_INTR_ID, shellUserModInterruptHandler, NULL) != XST_SUCCESS)\n"
        "    {\n"
        '        xil_printf("mod: XIntc_Connect failed (SHELL_USER_MOD_INTR_ID %u)\\r\\n", (unsigned int)SHELL_USER_MOD_INTR_ID);\n'
        "        return FALSE;\n"
        "    }\n"
        "    if (XIntc_Start(&S_sModIntc, XIN_REAL_MODE) != XST_SUCCESS)\n"
        "    {\n"
        '        xil_printf("mod: XIntc_Start failed\\r\\n");\n'
        "        return FALSE;\n"
        "    }\n"
        "    XIntc_Enable(&S_sModIntc, (u8)SHELL_USER_MOD_INTR_ID);\n"
        "    Xil_ExceptionInit();\n"
        "    Xil_ExceptionRegisterHandler(XIL_EXCEPTION_ID_INT, (Xil_ExceptionHandler)XIntc_InterruptHandler, &S_sModIntc);\n"
        "    Xil_ExceptionEnable();\n"
        "    S_uiModIntcReady = 1U;\n"
        "    return TRUE;\n"
        "}\n"
        "#endif /* XPAR_XINTC_NUM_INSTANCES */\n\n"
        "/* 14 konnektor durumu: her satir bir konnektor, 32 bit tek tek (bit31..bit0, 8'li gruplar); 0 yesil, 1 kirmizi. */\n"
        "static void shellUserModStatusPrint(void)\n"
        "{\n"
        "    unsigned int uiConnector;\n"
        "    unsigned int uiBit;\n"
        "    unsigned int uiAddress;\n"
        "    unsigned int uiStatus;\n"
        "    unsigned int uiErrors;\n"
        "    unsigned int uiTotalErrors = 0U;\n\n"
        '    xil_printf("  conn  reg  address     status      bit31 ... bit0 (0 = OK, 1 = ERR)\\r\\n");\n'
        "    for (uiConnector = 0U; uiConnector < SHELL_USER_MOD_CONNECTOR_COUNT; uiConnector++)\n"
        "    {\n"
        "        uiAddress = SHELL_USER_MOD_BASEADDR + SHELL_USER_MOD_STATUS_OFFSET + (uiConnector * 4U);\n"
        "        uiStatus = (unsigned int)Xil_In32((UINTPTR)uiAddress);\n"
        "        uiErrors = 0U;\n"
        '        xil_printf("  %4u  %3u  0x%08X  0x%08X  ", uiConnector + 1U, SHELL_USER_MOD_REG_COUNT + uiConnector, uiAddress, uiStatus);\n'
        "        for (uiBit = 32U; uiBit > 0U; uiBit--)\n"
        "        {\n"
        "            if (((uiStatus >> (uiBit - 1U)) & 1U) != 0U)\n"
        "            {\n"
        '                xil_printf("%s1", SHELL_USER_MOD_COLOR_ERR);\n'
        "                uiErrors++;\n"
        "            }\n"
        "            else\n"
        "            {\n"
        '                xil_printf("%s0", SHELL_USER_MOD_COLOR_OK);\n'
        "            }\n"
        "            if ((((uiBit - 1U) % 8U) == 0U) && (uiBit > 1U))\n"
        "            {\n"
        '                xil_printf("%s ", SHELL_USER_MOD_COLOR_RESET);\n'
        "            }\n"
        "        }\n"
        '        xil_printf("%s  %s%u error(s)%s\\r\\n", SHELL_USER_MOD_COLOR_RESET, (uiErrors == 0U) ? SHELL_USER_MOD_COLOR_OK : SHELL_USER_MOD_COLOR_ERR,\n'
        "                   uiErrors, SHELL_USER_MOD_COLOR_RESET);\n"
        "        uiTotalErrors += uiErrors;\n"
        "    }\n"
        '    xil_printf("%smod: gpio loopback %s - %u error bit(s) in %u connectors%s\\r\\n",\n'
        "               (uiTotalErrors == 0U) ? SHELL_USER_MOD_COLOR_OK : SHELL_USER_MOD_COLOR_ERR, (uiTotalErrors == 0U) ? \"OK\" : \"NOK\",\n"
        "               uiTotalErrors, SHELL_USER_MOD_CONNECTOR_COUNT, SHELL_USER_MOD_COLOR_RESET);\n"
        "}\n\n"
        "/* mod <x> test: desen yaz -> kesme bekle (SHELL_USER_MOD_TEST_TIMEOUT_MS) -> durumlari bas -> 0 yaz. */\n"
        "static void shellUserModTest(int iIndex, unsigned int uiAddress)\n"
        "{\n"
        "#if defined(XPAR_XINTC_NUM_INSTANCES) && !defined(SHELL_USER_MOD_INTR_ID_UNSET)\n"
        "    unsigned int uiElapsedMs = 0U;\n\n"
        "    if (shellUserModIntcInit() == FALSE)\n"
        "    {\n"
        "        return;\n"
        "    }\n"
        "    S_uiModTestDone = 0U;\n"
        "    Xil_Out32((UINTPTR)uiAddress, (u32)S_uiArrModValue[iIndex]);\n"
        '    xil_printf("mod: test %d started (reg%d <= 0x%08X), waiting for interrupt (max %u ms)\\r\\n", iIndex, iIndex,\n'
        "               S_uiArrModValue[iIndex], (unsigned int)SHELL_USER_MOD_TEST_TIMEOUT_MS);\n"
        "    while ((S_uiModTestDone == 0U) && (uiElapsedMs < SHELL_USER_MOD_TEST_TIMEOUT_MS))\n"
        "    {\n"
        "        usleep(1000U);\n"
        "        uiElapsedMs++;\n"
        "    }\n"
        "    if (S_uiModTestDone == 1U)\n"
        "    {\n"
        '        xil_printf("mod: interrupt received after %u ms\\r\\n", uiElapsedMs);\n'
        "    }\n"
        "    else\n"
        "    {\n"
        '        xil_printf("%smod: TIMEOUT - no interrupt within %u ms (status below may be incomplete)%s\\r\\n",\n'
        "                   SHELL_USER_MOD_COLOR_ERR, uiElapsedMs, SHELL_USER_MOD_COLOR_RESET);\n"
        "    }\n"
        "    shellUserModStatusPrint();\n"
        "    Xil_Out32((UINTPTR)uiAddress, 0U);\n"
        "    S_uiModTestDone = 0U;\n"
        '    xil_printf("mod: reg%d <= 0x00000000 (close)\\r\\n", iIndex);\n'
        "#elif defined(SHELL_USER_MOD_INTR_ID_UNSET)\n"
        "    (void)iIndex;\n"
        "    (void)uiAddress;\n"
        '    xil_printf("mod: SHELL_USER_MOD_INTR_ID is not set (XPAR_INTC_0_<IP>_..._VEC_ID, edit shell_user_commands.c)\\r\\n");\n'
        "#else\n"
        "    (void)iIndex;\n"
        "    (void)uiAddress;\n"
        '    xil_printf("mod: no AXI INTC in this design (XPAR_XINTC_NUM_INSTANCES) - test needs the interrupt\\r\\n");\n'
        "#endif\n"
        "}\n\n"
        "static void shellUserMod(unsigned int uiArgc, const char* cpArrArgv[])\n"
        "{\n"
        "    int iIndex;\n"
        "    unsigned int uiValue;\n"
        "    unsigned int uiAddress;\n\n"
        "    if (SHELL_USER_MOD_BASEADDR == 0U)\n"
        "    {\n"
        '        xil_printf("mod: SHELL_USER_MOD_BASEADDR is not set (edit shell_user_commands.c)\\r\\n");\n'
        "        return;\n"
        "    }\n"
        "    if (uiArgc != 3U)\n"
        "    {\n"
        '        xil_printf("usage: mod <0..7> <open|close|test>\\r\\n");\n'
        "        return;\n"
        "    }\n"
        "    iIndex = atoi(cpArrArgv[1]); /* string arguman -> sayi */\n"
        "    if ((cpArrArgv[1][0] < '0') || (cpArrArgv[1][0] > '9') || (iIndex < 0) || (iIndex >= (int)SHELL_USER_MOD_REG_COUNT))\n"
        "    {\n"
        '        xil_printf("mod: x must be 0..7 (got \'%s\')\\r\\n", cpArrArgv[1]);\n'
        "        return;\n"
        "    }\n"
        "    uiAddress = SHELL_USER_MOD_BASEADDR + ((unsigned int)iIndex * 4U);\n"
        '    if (strcmp(cpArrArgv[2], "test") == 0)\n'
        "    {\n"
        "        shellUserModTest(iIndex, uiAddress);\n"
        "        return;\n"
        "    }\n"
        '    if (strcmp(cpArrArgv[2], "open") == 0)\n'
        "    {\n"
        "        uiValue = S_uiArrModValue[iIndex];\n"
        "    }\n"
        '    else if (strcmp(cpArrArgv[2], "close") == 0)\n'
        "    {\n"
        "        uiValue = 0U;\n"
        "    }\n"
        "    else\n"
        "    {\n"
        '        xil_printf("mod: y must be open, close or test (got \'%s\')\\r\\n", cpArrArgv[2]);\n'
        "        return;\n"
        "    }\n"
        "    Xil_Out32((UINTPTR)uiAddress, (u32)uiValue);\n"
        '    xil_printf("mod: reg%d @0x%08X <= 0x%08X (%s)\\r\\n", iIndex, uiAddress, uiValue, cpArrArgv[2]);\n'
        "}\n\n"
)


# --- main ----------------------------------------------------------------------------------

def _c_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def banner_lines(spec: dict) -> list[str]:
    """Proje adi buyuk harf, FIGlet Colossal (acilista main.c basar)."""
    name = str(spec.get("project", {}).get("name", "kart"))
    return banner_font.render_banner(name)


def main_source(spec: dict) -> str:
    name = str(spec.get("project", {}).get("name", "kart"))
    banner = "".join(
        f'    xil_printf("{_c_string(line)}\\r\\n");\n' for line in banner_lines(spec)
    )
    return (
        "/**\n"
        " * @file main.c\n"
        f" * @brief {name}: ana program - CIT + konsol shell'i. Kendi projene kopyala ve uyarla.\n"
        " *\n"
        " * Konum: cikti kokunde (shell/ icinde degil) - Vitis src/ altinda tek basina durur.\n"
        " * Derleme: drivers/ (kart alt klasorleri dahil), cit/ ve shell/ include yolunda; dbg_printf.c\n"
        " * dahil tum .c dosyalari projede. Test bench ajani (tests/) BU projeye alinmaz.\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        '#include "main.h"\n'
        '#include "dbg_printf.h"\n'
        '#include "sistem_cit.h"\n'
        '#include "shell.h"\n'
        '#include "shell_user_commands.h"\n'
        '#include "xil_printf.h"\n\n'
        "static SSistemCitBus S_sBus;\n"
        "static const SSistemCitLimit S_sLimit = SISTEM_CIT_LIMIT_VARSAYILAN;\n"
        "static SSistemCit S_sCit;\n\n"
        "/* Acilis banner'i: proje adi (FIGlet Colossal). */\n"
        "static void mainBannerWrite(void)\n"
        "{\n"
        '    xil_printf("\\r\\n");\n'
        + banner
        + '    xil_printf("\\r\\n");\n'
        "}\n\n"
        "int main(void)\n"
        "{\n"
        "    int iStatus;\n\n"
        "    mainBannerWrite();\n"
        "    (void)dbgLevelSet(DEBUG_LEVEL_ERROR); /* sdl komutuyla canli degisir */\n"
        "    sistemCitBusVarsayilan(&S_sBus); /* denetleyici ornekleri + I2C cihaz tablosu */\n"
        "    iStatus = sistemCitInit(&S_sBus); /* her entegrenin DeviceInit'i */\n"
        f"    if (iStatus != {cit_layer.STATUS_OK})\n"
        "    {\n"
        '        dbg_printf(DEBUG_LEVEL_ERROR, "sistemCitInit: %d", iStatus);\n'
        "    }\n"
        "    shellInit(&S_sBus, &S_sLimit, &S_sCit);\n"
        "    (void)shellCommandsRegister(shellUserCommandTable(), shellUserCommandCount()); /* cit, sdl, mod ... */\n"
        "    while (1)\n"
        "    {\n"
        "        shellCheck(); /* konsolda komut varsa isler; bloklamaz */\n"
        "        /* kendi periyodik islerin buraya */\n"
        "    }\n"
        "    return 0;\n"
        "}\n"
    )


def main_header(spec: dict) -> str:
    name = str(spec.get("project", {}).get("name", "kart"))
    return (
        "/**\n"
        " * @file main.h\n"
        f" * @brief {name}: ana program bildirimi (main.c ile cift).\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        "#ifndef MAIN_H\n"
        "#define MAIN_H\n\n"
        "int main(void);\n\n"
        "#endif /* MAIN_H */\n"
    )


# --- README + yazma ---------------------------------------------------------------------

def readme_section(spec: dict, plans: list) -> str:
    i2c = _i2c_bus_entries(spec, plans)
    lines = [
        "",
        "## Konsol shell'i (`shell/`)",
        "",
        "Kendi main'inde derlenir; test bench ajaniyla ilgisi yoktur. Konsol UART'indan (BSP stdin,",
        f"`{console_uart_driver(spec)}`) satir okur, komut tablosundan dagitir. `main.c` kopyala-yapistir",
        "ana programdir (acilista Colossal banner). Vitis kurulumu bu kodu `<app>_shell` olarak ayrica derler.",
        "",
        "| Dosya | Icerik |",
        "|---|---|",
        "| `shell/shell_uart.h/.c` | `shellUartByteRead()` (bloklamaz) / `shellUartByteWrite()` |",
        "| `shell/shell.h/.c` | cekirdek (komut yok): satir okuma, ok tusu gecmisi, tokenize, `SShellCommand` tablo dagitimi; `shellInit`, `shellCommandsRegister`, `shellCheck` |",
        "| `shell/shell_user_commands.h/.c` | TUM komutlar tek tabloda `S_sArrUserCommands[]`: `cit`, `i2c_search`, `sdl`, `help` ve ornek `mod <0..7> <open|close>` |",
        "| `main.h/.c` (kok dizin) | banner -> bus kur -> `sistemCitInit` -> `shellInit` -> komut tablosunu kaydet -> `while (1) shellCheck();`; Vitis `<app>_shell` src/ kokunde tek basina |",
        "",
        "Yeni komut: `shell_user_commands.c`'de `static void shellUser<Ad>(unsigned int uiArgc, const char* cpArrArgv[])`",
        "yaz, `S_sArrUserCommands[]`'a `{\"<ad>\", shellUser<Ad>, \"<args>  aciklama\"}` satiri ekle. Argumanlar string",
        "(`cpArrArgv[1..]`), sayi icin `atoi`. `help` tabloyu otomatik listeler.",
        "",
        "| Komut | Ne yapar |",
        "|---|---|",
        "| `cit` | `sistemCitRead()`; cerceveli/renkli rapor INFO satirlaridir (`sdl info` ile gorunur), sonuc satiri her zaman |",
        f"| `i2c_search` | {', '.join(c for c, _, _ in i2c) or 'I2C yok'}: 0x08..0x77 yazma probu, ACK listesi (switch adresleri atlanir) |",
        "| `sdl <level>` | set debug level: `error` `warning` `msg` `info` `trace` ya da 0..5 |",
        "| `i2c_read <addr> <reg> [n]` | secili I2C denetleyicisinde register isaretcisini yazip n bayt okur (`0x48 reg 0x01: 0A 1B`) |",
        "| `i2c_write <addr> <byte...>` | ham bayt dizisi yazar (ilk bayt genelde register; switch icin `i2c_write 0x70 0x08`) |",
        "| `i2c_bus [id]` | birden fazla I2C denetleyicisi varsa: i2c_read/i2c_write icin denetleyici sec/listele |",
        "| `mem <addr> [value]` | 32-bit register oku / yaz (`Xil_In32` / `Xil_Out32`), yazinca geri okur |",
        *[f"| `{ip['id']} dump\\|read <n>\\|write <n> <value>` | custom IP ({ip['ip_name'] or ip['instance']}) base 0x{ip['base']:08X}, {ip['count']} x 4 B register: n = register no (0..{ip['count'] - 1}), dump tum araligi okur |"
          for ip in custom_ips(spec)],
        *[f"| `ip_{ip['id']} rd\\|wr <REG>[.<FIELD>] [value]\\|dump\\|help` | bilinen IP haritasi ({ip['ip_name']}, base 0x{ip['base']:08X}): register/bit alani ADIYLA oku-yaz (`drivers/ip/{ip['id']}_regs.h`) |"
          for ip in known_ip_maps(spec)],
        "| `help` | komut listesi (tablodan) |",
        "| `mod <x> <y>` | GPIO loopback test IP'si: `open` reg x <= desen, `close` 0, `test` = open + AXI INTC kesmesini bekle (1 s) + 14 konnektor durumunu renkli bas (bit 0 yesil OK, 1 kirmizi HATA) + close; `SHELL_USER_MOD_BASEADDR` ve `SHELL_USER_MOD_INTR_ID` ayarlanmali |",
        "",
    ]
    return "\n".join(lines)


def write_shell_layer(spec: dict, out_dir: Path, plans: list) -> tuple[list[str], str]:
    """shell/ agacini yazar; (yazilan yollar, README bolumu). CIT plani yoksa bos."""
    if not plans:
        return [], ""
    shell_dir = out_dir / SHELL_DIR
    written = [
        hio.write_output(shell_dir / "shell_uart.h", uart_header()),
        hio.write_output(shell_dir / "shell_uart.c", uart_source(spec)),
        hio.write_output(shell_dir / "shell.h", shell_header()),
        hio.write_output(shell_dir / "shell.c", shell_source()),
        hio.write_output(shell_dir / "shell_user_commands.h", user_commands_header()),
        hio.write_output(shell_dir / "shell_user_commands.c", user_commands_source(spec, plans)),
        # main.h/.c KOK dizinde, shell/ icinde degil: Vitis src/ altinda tek basina, bagimsiz durur
        # (kullanici istegi 2026-09-11). Eski surumlerin shell/main.* ve main_example.* kalintilari
        # silinir - ayni agacta iki main olmasin.
        hio.write_output(out_dir / "main.h", main_header(spec)),
        hio.write_output(out_dir / "main.c", main_source(spec)),
    ]
    for stale in ("main.h", "main.c", "main_example.h", "main_example.c"):
        stale_path = shell_dir / stale
        if stale_path.is_file():
            stale_path.unlink()
    return [str(p) for p in written], readme_section(spec, plans)
