"""Shell katmani (``outputs/<proje>/shell/``): konsol UART'indan komutla CIT / I2C tarama / log seviyesi.

Kullanicinin KENDI main'inde derlenir (test bench ajaniyla ilgisi yoktur; ajan bu klasoru
derlemez, Vitis sahnelemesi ayri `<app>_shell` uygulamasina koyar). ``drivers/`` ve ``cit/``
gibi tasinabilirdir: icinde urun adi gecmez.

Uretilen agac:
* ``shell/shell_uart.h/.c``          - BSP stdin/stdout cihazindan (``STDIN_BASEADDRESS``) bloklamadan
                                      tek bayt oku/yaz; platforma gore XUartLite / XUartPs / XUartPsv.
* ``shell/shell.h/.c``               - komut TABLOSU dagitimi: ``SShellCommand {ad, isleyici, yardim}``,
                                      ``shellInit``, ``shellCommandsRegister``, ``shellCheck`` (bloklamaz),
                                      yerlesik komutlar ``cit``, ``i2c_search``, ``sdl``, ``help``; yukari/asagi
                                      ok gecmisi; argumanlar STRING dizisi (argv), sayi gerekiyorsa ``atoi``.
* ``shell/shell_user_commands.h/.c`` - KULLANICI komutlari: tek tablo (``S_sArrUserCommands``) + isleyiciler;
                                      ornek ``mod <x> <y>`` (custom IP register yazimi). Yeni komut = bir
                                      fonksiyon + tabloya bir satir.
* ``shell/main.h/.c``                - ana program: Colossal banner, bus kur, ``sistemCitInit``, ``shellInit``,
                                      ``shellCommandsRegister(shellUserCommandTable(), ...)``,
                                      ``while (1) shellCheck();``.

Tasarim notlari:
* Cikti ``xil_printf`` ile konsola gider; ``cit`` komutu ``dbg_printf`` esigini gecici olarak
  INFO'ya cekip ``sistemCitRead``'in cerceveli/renkli raporunu bastirir, sonra geri alir.
* ``i2c_search`` spec'teki her I2C denetleyicisinde 0x08..0x77 tek-bayt yazma probu yapar
  (ajanin i2c_scan'iyle ayni yontem). I2C switch (TCA9548A) adresleri ATLANIR: aktif
  switch'e 0x00 yazmak secili kanali kapatirdi.
* Konsol metinleri Ingilizce (SAHA istegi 2026-09-08: "kabuk" ifadesi istenmedi).
"""

from __future__ import annotations

from pathlib import Path

from hostplat import io as hio
from orchestrator import banner_font, cit_layer, cmodel

SHELL_DIR = "shell"

_UART_BY_PLATFORM = {
    "microblaze_7series": "XUartLite",
    "zynq_7000": "XUartPs",
    "zynq_ultrascale": "XUartPs",
    "versal": "XUartPsv",
}

_UART_API = {
    "XUartLite": ("xuartlite_l.h", "XUartLite_IsReceiveEmpty(STDIN_BASEADDRESS) != 0U",
                  "XUartLite_RecvByte", "XUartLite_SendByte"),
    "XUartPs": ("xuartps_hw.h", "XUartPs_IsReceiveData(STDIN_BASEADDRESS) == 0U",
                "XUartPs_RecvByte", "XUartPs_SendByte"),
    "XUartPsv": ("xuartpsv_hw.h", "XUartPsv_IsReceiveData(STDIN_BASEADDRESS) == 0U",
                 "XUartPsv_RecvByte", "XUartPsv_SendByte"),
}


def console_uart_driver(spec: dict) -> str:
    """Konsol UART surucusu: spec'teki MDM olmayan ilk UART, yoksa platform varsayilani."""
    for controller in spec.get("controllers", []):
        if controller.get("type") == "uart" and controller.get("subtype") != "mdm":
            driver = str(controller.get("driver", ""))
            if driver in _UART_API:
                return driver
    platform = str(spec.get("project", {}).get("platform", ""))
    return _UART_BY_PLATFORM.get(platform, "XUartPs")


# --- shell_uart --------------------------------------------------------------------------

def uart_header() -> str:
    return (
        "/**\n"
        " * @file shell_uart.h\n"
        " * @brief Konsol UART'i (BSP stdin/stdout) uzerinden bloklamayan bayt okuma/yazma.\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        "#ifndef SHELL_UART_H\n"
        "#define SHELL_UART_H\n\n"
        '#include "xil_types.h"\n\n'
        "/* Konsolda bekleyen bir bayt varsa onu verir ve TRUE doner; yoksa hemen FALSE doner. */\n"
        "unsigned int shellUartByteRead(unsigned char* ucpByte);\n"
        "/* Bir bayti konsola yazar (gonderim FIFO'su doluysa bosalana kadar bekler). */\n"
        "void shellUartByteWrite(unsigned char ucByte);\n\n"
        "#endif /* SHELL_UART_H */\n"
    )


def uart_source(spec: dict) -> str:
    driver = console_uart_driver(spec)
    header, empty_expr, recv, send = _UART_API[driver]
    return (
        "/**\n"
        " * @file shell_uart.c\n"
        f" * @brief Konsol UART'i bayt erisimi ({driver}, BSP STDIN/STDOUT_BASEADDRESS).\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        '#include "shell_uart.h"\n'
        '#include "xparameters.h"\n'
        f'#include "{header}"\n'
        "#include <stddef.h>\n\n"
        "unsigned int shellUartByteRead(unsigned char* ucpByte)\n"
        "{\n"
        "#if defined(STDIN_BASEADDRESS)\n"
        "    if (ucpByte == NULL)\n"
        "    {\n"
        "        return FALSE;\n"
        "    }\n"
        f"    if ({empty_expr})\n"
        "    {\n"
        "        return FALSE;\n"
        "    }\n"
        f"    *ucpByte = (unsigned char){recv}(STDIN_BASEADDRESS);\n"
        "    return TRUE;\n"
        "#else\n"
        "    (void)ucpByte;\n"
        "    return FALSE; /* BSP'de stdin cihazi yok */\n"
        "#endif\n"
        "}\n\n"
        "void shellUartByteWrite(unsigned char ucByte)\n"
        "{\n"
        "#if defined(STDOUT_BASEADDRESS)\n"
        f"    {send}(STDOUT_BASEADDRESS, ucByte);\n"
        "#else\n"
        "    (void)ucByte;\n"
        "#endif\n"
        "}\n"
    )


# --- shell -------------------------------------------------------------------------------

def shell_header() -> str:
    return (
        "/**\n"
        " * @file shell.h\n"
        " * @brief Konsol shell'i: komut tablosu dagitimi (cit / i2c_search / sdl / help + kullanici komutlari).\n"
        " *\n"
        " * Kullanim (kart yazilimi, bkz. main.c):\n"
        " *   sistemCitBusVarsayilan(&S_sBus); sistemCitInit(&S_sBus);   -- ana dongu oncesi\n"
        " *   shellInit(&S_sBus, &S_sLimit, &S_sCit);\n"
        " *   shellCommandsRegister(shellUserCommandTable(), shellUserCommandCount());\n"
        " *   while (1) { shellCheck(); }                                -- bloklamaz\n"
        " *\n"
        " * Komut modeli: her komut `SShellCommand {cpName, fpHandler, cpHelp}` satiridir. Isleyici\n"
        " * `void f(unsigned int uiArgc, const char* cpArrArgv[])` imzasindadir; cpArrArgv[0] komut adi,\n"
        " * sonrakiler STRING argumanlar (sayi gerekiyorsa atoi/strtol ile cevrilir). Yerlesik tablo\n"
        " * shell.c'de, kullanici tablosu shell_user_commands.c'de; ikisi de ayni dagitimdan gecer.\n"
        " *\n"
        " * Yerlesik komutlar:\n"
        " *   cit               tum entegreleri oku, cerceveli/renkli raporu bas (sistemCitRead)\n"
        " *   i2c_search        her I2C denetleyicisinde 0x08..0x77 adres tarama (ACK listesi)\n"
        " *   sdl <level>       set debug level: error | warning | msg | info | trace (ya da 0..5)\n"
        " *   help              komut listesi (yerlesik + kullanici)\n"
        " *\n"
        " * Yukari/asagi ok tuslari (ESC [ A / ESC [ B) komut gecmisinde gezer (son SHELL_HISTORY_MAX).\n"
        " * `cit` raporu sdl seviyesinden BAGIMSIZ basilir (komutun ciktisidir); sdl yalniz\n"
        " * surucu/CIT kodunun kendi dbg_printf satirlarini (hata izleri vb.) suzer.\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        "#ifndef SHELL_H\n"
        "#define SHELL_H\n\n"
        '#include "sistem_cit.h"\n\n'
        "#define SHELL_LINE_MAX 48U\n"
        "#define SHELL_ARG_MAX 8U     /* komut adi dahil en fazla token */\n"
        "#define SHELL_HISTORY_MAX 8U /* yukari/asagi ok ile gezilen son komutlar */\n"
        "#define SHELL_TABLE_MAX 4U   /* kayitli komut tablosu sayisi (yerlesik + kullanici ...) */\n"
        '#define SHELL_PROMPT "> "\n\n'
        "/* Komut isleyicisi: uiArgc token sayisi (>= 1), cpArrArgv[0] komut adi, digerleri string arguman. */\n"
        "typedef void (*FShellHandler)(unsigned int uiArgc, const char* cpArrArgv[]);\n\n"
        "typedef struct\n"
        "{\n"
        '    const char* cpName;      /* konsolda yazilan ad (or. "mod") */\n'
        "    FShellHandler fpHandler; /* isleyici */\n"
        '    const char* cpHelp;      /* help satiri: "<args>  aciklama" */\n'
        "} SShellCommand;\n\n"
        "/* Shell'i CIT yapilariyla baglar, yerlesik tabloyu kaydeder, istemi basar. Yapilar kalici olmali. */\n"
        "void shellInit(SSistemCitBus* spBus, const SSistemCitLimit* spLimit, SSistemCit* spCit);\n"
        "/* Ek komut tablosu kaydeder (kullanici komutlari). Tablo kalici (static) olmali. TRUE = kaydedildi. */\n"
        "unsigned int shellCommandsRegister(const SShellCommand* spTable, unsigned int uiCount);\n"
        "/* Ana dongude cagrilir: konsolda bayt varsa isler, satir tamamlaninca komutu kosar; bloklamaz. */\n"
        "void shellCheck(void);\n\n"
        "#endif /* SHELL_H */\n"
    )


def _i2c_bus_entries(spec: dict, plans: list) -> list[tuple[str, str, str]]:
    """(denetleyici id, SSistemCitBus alani, surucu) - CIT bus'indaki I2C denetleyicileri."""
    out = []
    for controller in cit_layer.bus_controllers(plans):
        if controller.get("type") != "i2c":
            continue
        htype, _ = cmodel._handle_for(controller)
        out.append((str(controller.get("id")), cit_layer.controller_field(controller), htype))
    return out


def _mux_addresses(spec: dict) -> list[int]:
    addrs = []
    for mux in spec.get("muxes", []):
        try:
            addrs.append(int(str(mux.get("i2c_address", "0")), 0))
        except ValueError:
            continue
    return sorted(set(addrs))


def shell_source(spec: dict, plans: list) -> str:
    i2c = _i2c_bus_entries(spec, plans)
    htypes = sorted({h for _, _, h in i2c})
    mux_addrs = _mux_addresses(spec)
    e = cit_layer._E(0)
    e.ln("/**")
    e.ln(" * @file shell.c")
    e.ln(" * @brief Konsol shell'i: satir okuma, gecmis, tokenize, tablo dagitimi, yerlesik komutlar.")
    e.ln(" *")
    e.ln(" * Generated by Spec2Code. Do not edit by hand.")
    e.ln(" */")
    e.ln('#include "shell.h"')
    e.ln('#include "shell_uart.h"')
    e.ln('#include "dbg_printf.h"')
    e.ln('#include "xil_printf.h"')
    e.ln('#include "xstatus.h"')
    if "XIic" in htypes:
        e.ln('#include "xiic.h"')
        e.ln('#include "xiic_l.h"')
    if "XIicPs" in htypes:
        e.ln('#include "xiicps.h"')
    e.ln("#include <stddef.h>")
    e.ln("#include <string.h>")
    e.blank()
    e.ln("static SSistemCitBus* S_spBus = NULL;")
    e.ln("static const SSistemCitLimit* S_spLimit = NULL;")
    e.ln("static SSistemCit* S_spCit = NULL;")
    e.ln("static char S_cArrLine[SHELL_LINE_MAX];")
    e.ln("static unsigned int S_uiLineLength = 0U;")
    e.ln("/* Komut gecmisi: halka; S_uiHistoryCount kayitli sayi, S_uiHistoryHead sonraki yazma yeri,")
    e.ln(" * S_uiHistoryCursor gezinti konumu (== count: gecmis disinda, bos satir). */")
    e.ln("static char S_cArrHistory[SHELL_HISTORY_MAX][SHELL_LINE_MAX];")
    e.ln("static unsigned int S_uiHistoryCount = 0U;")
    e.ln("static unsigned int S_uiHistoryHead = 0U;")
    e.ln("static unsigned int S_uiHistoryCursor = 0U;")
    e.ln("static unsigned int S_uiEscapeState = 0U; /* 0: yok, 1: ESC alindi, 2: ESC [ alindi */")
    e.ln("/* Kayitli komut tablolari: [0] yerlesik, sonrakiler shellCommandsRegister ile. */")
    e.ln("static const SShellCommand* S_spArrTable[SHELL_TABLE_MAX];")
    e.ln("static unsigned int S_uiArrTableCount[SHELL_TABLE_MAX];")
    e.ln("static unsigned int S_uiTableCount = 0U;")
    if mux_addrs:
        e.ln("/* I2C switch adresleri: taramada atlanir (0x00 yazmak secili kanali kapatirdi). */")
        e.ln("static const unsigned int S_uiArrSwitchAddress[] = {" + ", ".join(f"0x{a:02X}U" for a in mux_addrs) + "};")
    e.blank()
    e.ln("static void shellPromptWrite(void)")
    e.ln("{")
    e.ln('    xil_printf("%s", SHELL_PROMPT);')
    e.ln("}")
    e.blank()
    # --- yerlesik: cit
    e.ln("/* --- yerlesik komutlar ---------------------------------------------------------------- */")
    e.blank()
    e.ln("static void shellCommandCit(unsigned int uiArgc, const char* cpArrArgv[])")
    e.ln("{")
    e.ln("    unsigned int uiOldLevel;")
    e.ln("    int iResult;")
    e.blank()
    e.ln("    (void)uiArgc;")
    e.ln("    (void)cpArrArgv;")
    e.ln("    if ((S_spBus == NULL) || (S_spCit == NULL))")
    e.ln("    {")
    e.ln('        xil_printf("cit: shell is not initialized\\r\\n");')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    uiOldLevel = dbgLevelGet();")
    e.ln("    if (uiOldLevel < DEBUG_LEVEL_INFO)")
    e.ln("    {")
    e.ln("        (void)dbgLevelSet(DEBUG_LEVEL_INFO); /* rapor INFO seviyesinde basilir */")
    e.ln("    }")
    e.ln("    iResult = sistemCitRead(S_spBus, S_spLimit, S_spCit);")
    e.ln("    (void)dbgLevelSet(uiOldLevel);")
    e.ln(f'    xil_printf("cit: %s (run #%u)\\r\\n", (iResult == {cit_layer.STATUS_OK}) ? "OK" : ((iResult == {cit_layer.STATUS_NOK}) ? "NOK" : "ERROR"), S_spCit->uiSayac);')
    e.ln("}")
    e.blank()
    # --- yerlesik: i2c_search
    if i2c:
        if mux_addrs:
            e.ln("static unsigned int shellI2cIsSwitchAddress(unsigned int uiAddress)")
            e.ln("{")
            e.ln("    unsigned int uiIndex;")
            e.blank()
            e.ln("    for (uiIndex = 0U; uiIndex < (sizeof(S_uiArrSwitchAddress) / sizeof(S_uiArrSwitchAddress[0])); uiIndex++)")
            e.ln("    {")
            e.ln("        if (S_uiArrSwitchAddress[uiIndex] == uiAddress)")
            e.ln("        {")
            e.ln("            return TRUE;")
            e.ln("        }")
            e.ln("    }")
            e.ln("    return FALSE;")
            e.ln("}")
            e.blank()
        for htype in htypes:
            e.ln(f"static unsigned int shellI2cProbe{htype}({htype}* spIic, unsigned int uiAddress)")
            e.ln("{")
            e.ln("    unsigned char ucProbe = 0x00U;")
            if htype == "XIic":
                e.blank()
                e.ln("    /* Dinamik mod: gonderilen bayt sayisi 1 ise ACK alindi. */")
                e.ln("    return ((unsigned int)XIic_DynSend(spIic->BaseAddress, (unsigned short)uiAddress, &ucProbe, 1U, XIIC_STOP) == 1U) ? TRUE : FALSE;")
            else:
                e.ln("    int iStatus;")
                e.blank()
                e.ln("    iStatus = XIicPs_MasterSendPolled(spIic, &ucProbe, 1, (unsigned short)uiAddress);")
                e.ln("    while (XIicPs_BusIsBusy(spIic) == TRUE)")
                e.ln("    {")
                e.ln("        /* bus bosalana kadar bekle */")
                e.ln("    }")
                e.ln("    return (iStatus == XST_SUCCESS) ? TRUE : FALSE;")
            e.ln("}")
            e.blank()
        e.ln("static void shellCommandI2cSearch(unsigned int uiArgc, const char* cpArrArgv[])")
        e.ln("{")
        e.ln("    unsigned int uiAddress;")
        e.ln("    unsigned int uiFound;")
        e.blank()
        e.ln("    (void)uiArgc;")
        e.ln("    (void)cpArrArgv;")
        e.ln("    if (S_spBus == NULL)")
        e.ln("    {")
        e.ln('        xil_printf("i2c_search: shell is not initialized\\r\\n");')
        e.ln("        return;")
        e.ln("    }")
        for cid, fld, htype in i2c:
            e.ln(f'    xil_printf("{cid}: scanning 0x08..0x77\\r\\n");')
            e.ln("    uiFound = 0U;")
            e.ln("    for (uiAddress = 0x08U; uiAddress <= 0x77U; uiAddress++)")
            e.ln("    {")
            if mux_addrs:
                e.ln("        if (shellI2cIsSwitchAddress(uiAddress) == TRUE)")
                e.ln("        {")
                e.ln('            xil_printf("  0x%02X  (I2C switch, skipped)\\r\\n", uiAddress);')
                e.ln("            continue;")
                e.ln("        }")
            e.ln(f"        if (shellI2cProbe{htype}(S_spBus->{fld}, uiAddress) == TRUE)")
            e.ln("        {")
            e.ln('            xil_printf("  0x%02X  ACK\\r\\n", uiAddress);')
            e.ln("            uiFound++;")
            e.ln("        }")
            e.ln("    }")
            e.ln(f'    xil_printf("{cid}: %u device(s)\\r\\n", uiFound);')
        e.ln("}")
    else:
        e.ln("static void shellCommandI2cSearch(unsigned int uiArgc, const char* cpArrArgv[])")
        e.ln("{")
        e.ln("    (void)uiArgc;")
        e.ln("    (void)cpArrArgv;")
        e.ln('    xil_printf("i2c_search: no I2C controller in this project\\r\\n");')
        e.ln("}")
    e.blank()
    # --- yerlesik: sdl
    e.ln("static void shellCommandSdl(unsigned int uiArgc, const char* cpArrArgv[])")
    e.ln("{")
    e.ln('    static const char* const S_cpArrLevelName[] = {"always", "error", "warning", "msg", "info", "trace"};')
    e.ln("    const char* cpArgument;")
    e.ln("    unsigned int uiLevel;")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln("    if (uiArgc < 2U)")
    e.ln("    {")
    e.ln('        xil_printf("log level: %s (%u)\\r\\n", dbgLevelName(dbgLevelGet()), dbgLevelGet());')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    cpArgument = cpArrArgv[1];")
    e.ln("    uiLevel = DEBUG_LEVEL_TRACE + 1U; /* gecersiz */")
    e.ln("    for (uiIndex = 0U; uiIndex <= DEBUG_LEVEL_TRACE; uiIndex++)")
    e.ln("    {")
    e.ln("        if (strcmp(cpArgument, S_cpArrLevelName[uiIndex]) == 0)")
    e.ln("        {")
    e.ln("            uiLevel = uiIndex;")
    e.ln("        }")
    e.ln("    }")
    e.ln("    if ((uiLevel > DEBUG_LEVEL_TRACE) && (cpArgument[0] >= '0') && (cpArgument[0] <= '5') && (cpArgument[1] == '\\0'))")
    e.ln("    {")
    e.ln("        uiLevel = (unsigned int)(cpArgument[0] - '0');")
    e.ln("    }")
    e.ln("    if (uiLevel > DEBUG_LEVEL_TRACE)")
    e.ln("    {")
    e.ln('        xil_printf("sdl: invalid level \'%s\' (error|warning|msg|info|trace|0..5)\\r\\n", cpArgument);')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    (void)dbgLevelSet(uiLevel);")
    e.ln('    xil_printf("log level: %s (%u)\\r\\n", dbgLevelName(dbgLevelGet()), dbgLevelGet());')
    e.ln("}")
    e.blank()
    # --- yerlesik: help
    e.ln("static void shellCommandHelp(unsigned int uiArgc, const char* cpArrArgv[])")
    e.ln("{")
    e.ln("    unsigned int uiTable;")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln("    (void)uiArgc;")
    e.ln("    (void)cpArrArgv;")
    e.ln('    xil_printf("commands:\\r\\n");')
    e.ln("    for (uiTable = 0U; uiTable < S_uiTableCount; uiTable++)")
    e.ln("    {")
    e.ln("        for (uiIndex = 0U; uiIndex < S_uiArrTableCount[uiTable]; uiIndex++)")
    e.ln("        {")
    e.ln('            xil_printf("  %-12s %s\\r\\n", S_spArrTable[uiTable][uiIndex].cpName, S_spArrTable[uiTable][uiIndex].cpHelp);')
    e.ln("        }")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("/* Yerlesik komut tablosu. Yeni yerlesik komut = isleyici + bir satir. */")
    e.ln("static const SShellCommand S_sArrBuiltinCommands[] = {")
    e.ln('    {"cit", shellCommandCit, "read all devices, print the report"},')
    e.ln('    {"i2c_search", shellCommandI2cSearch, "scan I2C addresses 0x08..0x77"},')
    e.ln('    {"sdl", shellCommandSdl, "<level>  set debug level: error|warning|msg|info|trace (0..5)"},')
    e.ln('    {"help", shellCommandHelp, "list commands"},')
    e.ln("};")
    e.blank()
    # --- gecmis
    e.ln("/* --- komut gecmisi ---------------------------------------------------------------------- */")
    e.blank()
    e.ln("static void shellHistoryAdd(const char* cpLine)")
    e.ln("{")
    e.ln("    unsigned int uiLast;")
    e.blank()
    e.ln("    if (S_uiHistoryCount > 0U)")
    e.ln("    {")
    e.ln("        uiLast = (S_uiHistoryHead + SHELL_HISTORY_MAX - 1U) % SHELL_HISTORY_MAX;")
    e.ln("        if (strcmp(S_cArrHistory[uiLast], cpLine) == 0)")
    e.ln("        {")
    e.ln("            return; /* ayni komut arka arkaya: tek kayit */")
    e.ln("        }")
    e.ln("    }")
    e.ln("    (void)strncpy(S_cArrHistory[S_uiHistoryHead], cpLine, SHELL_LINE_MAX - 1U);")
    e.ln("    S_cArrHistory[S_uiHistoryHead][SHELL_LINE_MAX - 1U] = '\\0';")
    e.ln("    S_uiHistoryHead = (S_uiHistoryHead + 1U) % SHELL_HISTORY_MAX;")
    e.ln("    if (S_uiHistoryCount < SHELL_HISTORY_MAX)")
    e.ln("    {")
    e.ln("        S_uiHistoryCount++;")
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("/* Gezinti konumundaki kaydi (0 = en eski) satira yukler ve ekranda yeniden cizer. */")
    e.ln("static void shellHistoryLoad(unsigned int uiCursor)")
    e.ln("{")
    e.ln("    unsigned int uiIndex;")
    e.ln("    unsigned int uiSlot;")
    e.blank()
    e.ln("    for (uiIndex = 0U; uiIndex < S_uiLineLength; uiIndex++)")
    e.ln("    {")
    e.ln('        xil_printf("\\b \\b"); /* ekrandaki satiri sil */')
    e.ln("    }")
    e.ln("    S_uiLineLength = 0U;")
    e.ln("    S_cArrLine[0] = '\\0';")
    e.ln("    if (uiCursor < S_uiHistoryCount)")
    e.ln("    {")
    e.ln("        uiSlot = (S_uiHistoryHead + SHELL_HISTORY_MAX - S_uiHistoryCount + uiCursor) % SHELL_HISTORY_MAX;")
    e.ln("        (void)strncpy(S_cArrLine, S_cArrHistory[uiSlot], SHELL_LINE_MAX - 1U);")
    e.ln("        S_cArrLine[SHELL_LINE_MAX - 1U] = '\\0';")
    e.ln("        S_uiLineLength = (unsigned int)strlen(S_cArrLine);")
    e.ln('        xil_printf("%s", S_cArrLine);')
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("/* ESC [ A (yukari) / ESC [ B (asagi): 0 = tuketilmedi, 1 = kacis dizisinin parcasi. */")
    e.ln("static unsigned int shellEscapeHandle(unsigned char ucByte)")
    e.ln("{")
    e.ln("    if (S_uiEscapeState == 0U)")
    e.ln("    {")
    e.ln("        if (ucByte == 0x1BU)")
    e.ln("        {")
    e.ln("            S_uiEscapeState = 1U;")
    e.ln("            return TRUE;")
    e.ln("        }")
    e.ln("        return FALSE;")
    e.ln("    }")
    e.ln("    if (S_uiEscapeState == 1U)")
    e.ln("    {")
    e.ln("        S_uiEscapeState = (ucByte == (unsigned char)'[') ? 2U : 0U;")
    e.ln("        return TRUE;")
    e.ln("    }")
    e.ln("    S_uiEscapeState = 0U;")
    e.ln("    if (ucByte == (unsigned char)'A')")
    e.ln("    {")
    e.ln("        if (S_uiHistoryCursor > 0U)")
    e.ln("        {")
    e.ln("            S_uiHistoryCursor--;")
    e.ln("            shellHistoryLoad(S_uiHistoryCursor);")
    e.ln("        }")
    e.ln("    }")
    e.ln("    else if (ucByte == (unsigned char)'B')")
    e.ln("    {")
    e.ln("        if (S_uiHistoryCursor < S_uiHistoryCount)")
    e.ln("        {")
    e.ln("            S_uiHistoryCursor++;")
    e.ln("            shellHistoryLoad(S_uiHistoryCursor); /* count'a ulasinca bos satir */")
    e.ln("        }")
    e.ln("    }")
    e.ln("    else")
    e.ln("    {")
    e.ln("        /* sol/sag/diger CSI: yok sayilir */")
    e.ln("    }")
    e.ln("    return TRUE;")
    e.ln("}")
    e.blank()
    # --- tokenize + dagitim
    e.ln("/* --- tokenize + tablo dagitimi ---------------------------------------------------------- */")
    e.blank()
    e.ln("/* Satiri bosluklardan token'lara boler (yerinde, '\\0' ile). Donus: token sayisi. */")
    e.ln("static unsigned int shellTokenize(char* cpLine, const char* cpArrArgv[])")
    e.ln("{")
    e.ln("    unsigned int uiArgc = 0U;")
    e.blank()
    e.ln("    while ((*cpLine != '\\0') && (uiArgc < SHELL_ARG_MAX))")
    e.ln("    {")
    e.ln("        while (*cpLine == ' ')")
    e.ln("        {")
    e.ln("            cpLine++;")
    e.ln("        }")
    e.ln("        if (*cpLine == '\\0')")
    e.ln("        {")
    e.ln("            break;")
    e.ln("        }")
    e.ln("        cpArrArgv[uiArgc] = cpLine;")
    e.ln("        uiArgc++;")
    e.ln("        while ((*cpLine != '\\0') && (*cpLine != ' '))")
    e.ln("        {")
    e.ln("            cpLine++;")
    e.ln("        }")
    e.ln("        if (*cpLine == ' ')")
    e.ln("        {")
    e.ln("            *cpLine = '\\0';")
    e.ln("            cpLine++;")
    e.ln("        }")
    e.ln("    }")
    e.ln("    return uiArgc;")
    e.ln("}")
    e.blank()
    e.ln("static const SShellCommand* shellCommandFind(const char* cpName)")
    e.ln("{")
    e.ln("    unsigned int uiTable;")
    e.ln("    unsigned int uiIndex;")
    e.blank()
    e.ln("    for (uiTable = 0U; uiTable < S_uiTableCount; uiTable++)")
    e.ln("    {")
    e.ln("        for (uiIndex = 0U; uiIndex < S_uiArrTableCount[uiTable]; uiIndex++)")
    e.ln("        {")
    e.ln("            if (strcmp(S_spArrTable[uiTable][uiIndex].cpName, cpName) == 0)")
    e.ln("            {")
    e.ln("                return &S_spArrTable[uiTable][uiIndex];")
    e.ln("            }")
    e.ln("        }")
    e.ln("    }")
    e.ln("    return NULL;")
    e.ln("}")
    e.blank()
    e.ln("static void shellLineExecute(char* cpLine)")
    e.ln("{")
    e.ln("    const char* cpArrArgv[SHELL_ARG_MAX];")
    e.ln("    const SShellCommand* spCommand;")
    e.ln("    unsigned int uiArgc;")
    e.blank()
    e.ln("    uiArgc = shellTokenize(cpLine, cpArrArgv);")
    e.ln("    if (uiArgc == 0U)")
    e.ln("    {")
    e.ln("        return;")
    e.ln("    }")
    e.ln("    spCommand = shellCommandFind(cpArrArgv[0]);")
    e.ln("    if (spCommand == NULL)")
    e.ln("    {")
    e.ln('        xil_printf("unknown command: %s (type help)\\r\\n", cpArrArgv[0]);')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    spCommand->fpHandler(uiArgc, cpArrArgv);")
    e.ln("}")
    e.blank()
    # --- public API
    e.ln("/* --- genel API -------------------------------------------------------------------------- */")
    e.blank()
    e.ln("unsigned int shellCommandsRegister(const SShellCommand* spTable, unsigned int uiCount)")
    e.ln("{")
    e.ln("    if ((spTable == NULL) || (uiCount == 0U) || (S_uiTableCount >= SHELL_TABLE_MAX))")
    e.ln("    {")
    e.ln("        return FALSE;")
    e.ln("    }")
    e.ln("    S_spArrTable[S_uiTableCount] = spTable;")
    e.ln("    S_uiArrTableCount[S_uiTableCount] = uiCount;")
    e.ln("    S_uiTableCount++;")
    e.ln("    return TRUE;")
    e.ln("}")
    e.blank()
    e.ln("void shellInit(SSistemCitBus* spBus, const SSistemCitLimit* spLimit, SSistemCit* spCit)")
    e.ln("{")
    e.ln("    S_spBus = spBus;")
    e.ln("    S_spLimit = spLimit;")
    e.ln("    S_spCit = spCit;")
    e.ln("    S_uiLineLength = 0U;")
    e.ln("    S_cArrLine[0] = '\\0';")
    e.ln("    S_uiHistoryCount = 0U;")
    e.ln("    S_uiHistoryHead = 0U;")
    e.ln("    S_uiHistoryCursor = 0U;")
    e.ln("    S_uiEscapeState = 0U;")
    e.ln("    S_uiTableCount = 0U;")
    e.ln("    (void)shellCommandsRegister(S_sArrBuiltinCommands, sizeof(S_sArrBuiltinCommands) / sizeof(S_sArrBuiltinCommands[0]));")
    e.ln('    xil_printf("\\r\\nshell is initialized (type help)\\r\\n");')
    e.ln("    shellPromptWrite();")
    e.ln("}")
    e.blank()
    e.ln("void shellCheck(void)")
    e.ln("{")
    e.ln("    unsigned char ucByte;")
    e.blank()
    e.ln("    while (shellUartByteRead(&ucByte) == TRUE)")
    e.ln("    {")
    e.ln("        if (shellEscapeHandle(ucByte) == TRUE)")
    e.ln("        {")
    e.ln("            continue; /* ok tuslari: gecmis gezintisi */")
    e.ln("        }")
    e.ln("        if ((ucByte == (unsigned char)'\\r') || (ucByte == (unsigned char)'\\n'))")
    e.ln("        {")
    e.ln("            if (S_uiLineLength == 0U)")
    e.ln("            {")
    e.ln("                /* CR+LF ciftinin ikinci karakteri ya da bos satir: yalniz istem. */")
    e.ln('                xil_printf("\\r\\n");')
    e.ln("                shellPromptWrite();")
    e.ln("                continue;")
    e.ln("            }")
    e.ln('            xil_printf("\\r\\n");')
    e.ln("            S_cArrLine[S_uiLineLength] = '\\0';")
    e.ln("            shellHistoryAdd(S_cArrLine);")
    e.ln("            S_uiHistoryCursor = S_uiHistoryCount;")
    e.ln("            shellLineExecute(S_cArrLine); /* satir yerinde token'lanir (gecmis kopyasi zaten alindi) */")
    e.ln("            S_uiLineLength = 0U;")
    e.ln("            shellPromptWrite();")
    e.ln("        }")
    e.ln("        else if ((ucByte == 0x08U) || (ucByte == 0x7FU))")
    e.ln("        {")
    e.ln("            if (S_uiLineLength > 0U)")
    e.ln("            {")
    e.ln("                S_uiLineLength--;")
    e.ln('                xil_printf("\\b \\b");')
    e.ln("            }")
    e.ln("        }")
    e.ln("        else if ((ucByte >= 0x20U) && (ucByte < 0x7FU))")
    e.ln("        {")
    e.ln("            if (S_uiLineLength < (SHELL_LINE_MAX - 1U))")
    e.ln("            {")
    e.ln("                S_cArrLine[S_uiLineLength] = (char)ucByte;")
    e.ln("                S_uiLineLength++;")
    e.ln("                shellUartByteWrite(ucByte); /* yansi */")
    e.ln("            }")
    e.ln("        }")
    e.ln("        else")
    e.ln("        {")
    e.ln("            /* diger kontrol karakterleri yok sayilir */")
    e.ln("        }")
    e.ln("    }")
    e.ln("}")
    return e.text() + "\n"


# --- shell_user_commands -----------------------------------------------------------------

def user_commands_header() -> str:
    return (
        "/**\n"
        " * @file shell_user_commands.h\n"
        " * @brief KULLANICI komutlari: kendi komutlarini buraya eklersin (bkz. shell_user_commands.c).\n"
        " *\n"
        " * Yeni komut eklemek icin:\n"
        " *   1. shell_user_commands.c'de `static void shellUser<Ad>(unsigned int uiArgc, const char* cpArrArgv[])`\n"
        " *      isleyicisini yaz (cpArrArgv[1..] STRING; sayi gerekiyorsa atoi/strtol).\n"
        ' *   2. S_sArrUserCommands[] tablosuna `{"<konsol adi>", shellUser<Ad>, "<args>  aciklama"}` satiri ekle.\n'
        " *   Baska hicbir yere dokunma: main.c tabloyu shellCommandsRegister ile bir kez kaydeder,\n"
        " *   `help` yeni satiri kendiliginden listeler.\n"
        " *\n"
        " * Generated by Spec2Code (ornek icerik; kendi projende serbestce duzenle).\n"
        " */\n"
        "#ifndef SHELL_USER_COMMANDS_H\n"
        "#define SHELL_USER_COMMANDS_H\n\n"
        '#include "shell.h"\n\n'
        "/* Kullanici komut tablosu ve eleman sayisi (main.c: shellCommandsRegister(...)). */\n"
        "const SShellCommand* shellUserCommandTable(void);\n"
        "unsigned int shellUserCommandCount(void);\n\n"
        "#endif /* SHELL_USER_COMMANDS_H */\n"
    )


def user_commands_source() -> str:
    return (
        "/**\n"
        " * @file shell_user_commands.c\n"
        " * @brief Kullanici komutlari: ornek `mod <x> <y>` - custom IP register yazimi.\n"
        " *\n"
        " *   > mod 3 open     -> Xil_Out32(SHELL_USER_MOD_BASEADDR + 3*4, 0x03030303)\n"
        " *   > mod 3 close    -> Xil_Out32(SHELL_USER_MOD_BASEADDR + 3*4, 0)\n"
        ' *   x: 0..7 (register indeksi, 4 baytlik ofsetle), y: "open" | "close".\n'
        " *\n"
        " * Generated by Spec2Code (ornek icerik; kendi projende serbestce duzenle).\n"
        " */\n"
        '#include "shell_user_commands.h"\n'
        '#include "xil_io.h"\n'
        '#include "xil_printf.h"\n'
        "#include <stdlib.h>\n"
        "#include <string.h>\n\n"
        "/* TODO: custom IP taban adresi (xparameters.h'teki XPAR_<IP>_BASEADDR). 0 iken yazim yapilmaz. */\n"
        "#ifndef SHELL_USER_MOD_BASEADDR\n"
        "#define SHELL_USER_MOD_BASEADDR 0x00000000U\n"
        "#endif\n"
        "#define SHELL_USER_MOD_REG_COUNT 8U\n\n"
        '/* reg0..reg7\'ye "open" ile yazilacak desenler; "close" 0 yazar. */\n'
        "static const unsigned int S_uiArrModValue[SHELL_USER_MOD_REG_COUNT] = {\n"
        "    0x00000000U, 0x01010101U, 0x02020202U, 0x03030303U, 0x04040404U, 0x05050505U, 0x06060606U, 0x07070707U,\n"
        "};\n\n"
        "static void shellUserMod(unsigned int uiArgc, const char* cpArrArgv[])\n"
        "{\n"
        "    int iIndex;\n"
        "    unsigned int uiValue;\n"
        "    unsigned int uiAddress;\n\n"
        "    if (SHELL_USER_MOD_BASEADDR == 0U)\n"
        "    {\n"
        '        xil_printf("mod: SHELL_USER_MOD_BASEADDR is not set (edit shell_user_commands.c)\\r\\n");\n'
        "        return;\n"
        "    }\n"
        "    if (uiArgc != 3U)\n"
        "    {\n"
        '        xil_printf("usage: mod <0..7> <open|close>\\r\\n");\n'
        "        return;\n"
        "    }\n"
        "    iIndex = atoi(cpArrArgv[1]); /* string arguman -> sayi */\n"
        "    if ((cpArrArgv[1][0] < '0') || (cpArrArgv[1][0] > '9') || (iIndex < 0) || (iIndex >= (int)SHELL_USER_MOD_REG_COUNT))\n"
        "    {\n"
        '        xil_printf("mod: x must be 0..7 (got \'%s\')\\r\\n", cpArrArgv[1]);\n'
        "        return;\n"
        "    }\n"
        '    if (strcmp(cpArrArgv[2], "open") == 0)\n'
        "    {\n"
        "        uiValue = S_uiArrModValue[iIndex];\n"
        "    }\n"
        '    else if (strcmp(cpArrArgv[2], "close") == 0)\n'
        "    {\n"
        "        uiValue = 0U;\n"
        "    }\n"
        "    else\n"
        "    {\n"
        '        xil_printf("mod: y must be open or close (got \'%s\')\\r\\n", cpArrArgv[2]);\n'
        "        return;\n"
        "    }\n"
        "    uiAddress = SHELL_USER_MOD_BASEADDR + ((unsigned int)iIndex * 4U);\n"
        "    Xil_Out32(uiAddress, uiValue);\n"
        '    xil_printf("mod: reg%d @0x%08X <= 0x%08X (%s)\\r\\n", iIndex, uiAddress, uiValue, cpArrArgv[2]);\n'
        "}\n\n"
        "/* Kullanici komut tablosu: yeni komut = isleyici + bir satir. */\n"
        "static const SShellCommand S_sArrUserCommands[] = {\n"
        '    {"mod", shellUserMod, "<0..7> <open|close>  write custom IP register x (open: pattern, close: 0)"},\n'
        "};\n\n"
        "const SShellCommand* shellUserCommandTable(void)\n"
        "{\n"
        "    return S_sArrUserCommands;\n"
        "}\n\n"
        "unsigned int shellUserCommandCount(void)\n"
        "{\n"
        "    return (unsigned int)(sizeof(S_sArrUserCommands) / sizeof(S_sArrUserCommands[0]));\n"
        "}\n"
    )


# --- main ----------------------------------------------------------------------------------

def _c_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def banner_lines(spec: dict) -> list[str]:
    """Proje adi buyuk harf, FIGlet Colossal (acilista main.c basar)."""
    name = str(spec.get("project", {}).get("name", "kart"))
    return banner_font.render_banner(name)


def main_source(spec: dict) -> str:
    name = str(spec.get("project", {}).get("name", "kart"))
    banner = "".join(
        f'    xil_printf("{_c_string(line)}\\r\\n");\n' for line in banner_lines(spec)
    )
    return (
        "/**\n"
        " * @file main.c\n"
        f" * @brief {name}: ana program - CIT + konsol shell'i. Kendi projene kopyala ve uyarla.\n"
        " *\n"
        " * Derleme: drivers/ (kart alt klasorleri dahil), cit/ ve shell/ include yolunda; dbg_printf.c\n"
        " * dahil tum .c dosyalari projede. Test bench ajani (tests/) BU projeye alinmaz.\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        '#include "main.h"\n'
        '#include "dbg_printf.h"\n'
        '#include "sistem_cit.h"\n'
        '#include "shell.h"\n'
        '#include "shell_user_commands.h"\n'
        '#include "xil_printf.h"\n\n'
        "static SSistemCitBus S_sBus;\n"
        "static const SSistemCitLimit S_sLimit = SISTEM_CIT_LIMIT_VARSAYILAN;\n"
        "static SSistemCit S_sCit;\n\n"
        "/* Acilis banner'i: proje adi (FIGlet Colossal). */\n"
        "static void mainBannerWrite(void)\n"
        "{\n"
        '    xil_printf("\\r\\n");\n'
        + banner
        + '    xil_printf("\\r\\n");\n'
        "}\n\n"
        "int main(void)\n"
        "{\n"
        "    int iStatus;\n\n"
        "    mainBannerWrite();\n"
        "    (void)dbgLevelSet(DEBUG_LEVEL_ERROR); /* sdl komutuyla canli degisir */\n"
        "    sistemCitBusVarsayilan(&S_sBus); /* denetleyici ornekleri + I2C cihaz tablosu */\n"
        "    iStatus = sistemCitInit(&S_sBus); /* her entegrenin DeviceInit'i */\n"
        f"    if (iStatus != {cit_layer.STATUS_OK})\n"
        "    {\n"
        '        dbg_printf(DEBUG_LEVEL_ERROR, "sistemCitInit: %d", iStatus);\n'
        "    }\n"
        "    shellInit(&S_sBus, &S_sLimit, &S_sCit);\n"
        "    (void)shellCommandsRegister(shellUserCommandTable(), shellUserCommandCount()); /* mod ... */\n"
        "    while (1)\n"
        "    {\n"
        "        shellCheck(); /* konsolda komut varsa isler; bloklamaz */\n"
        "        /* kendi periyodik islerin buraya */\n"
        "    }\n"
        "    return 0;\n"
        "}\n"
    )


def main_header(spec: dict) -> str:
    name = str(spec.get("project", {}).get("name", "kart"))
    return (
        "/**\n"
        " * @file main.h\n"
        f" * @brief {name}: ana program bildirimi (main.c ile cift).\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        "#ifndef MAIN_H\n"
        "#define MAIN_H\n\n"
        "int main(void);\n\n"
        "#endif /* MAIN_H */\n"
    )


# --- README + yazma ---------------------------------------------------------------------

def readme_section(spec: dict, plans: list) -> str:
    i2c = _i2c_bus_entries(spec, plans)
    lines = [
        "",
        "## Konsol shell'i (`shell/`)",
        "",
        "Kendi main'inde derlenir; test bench ajaniyla ilgisi yoktur. Konsol UART'indan (BSP stdin,",
        f"`{console_uart_driver(spec)}`) satir okur, komut tablosundan dagitir. `main.c` kopyala-yapistir",
        "ana programdir (acilista Colossal banner). Vitis kurulumu bu kodu `<app>_shell` olarak ayrica derler.",
        "",
        "| Dosya | Icerik |",
        "|---|---|",
        "| `shell/shell_uart.h/.c` | `shellUartByteRead()` (bloklamaz) / `shellUartByteWrite()` |",
        "| `shell/shell.h/.c` | `SShellCommand` tablosu, `shellInit`, `shellCommandsRegister`, `shellCheck`; yerlesik `cit`, `i2c_search`, `sdl`, `help`; ok tusu gecmisi |",
        "| `shell/shell_user_commands.h/.c` | KULLANICI komutlari: `S_sArrUserCommands[]` + isleyiciler; ornek `mod <0..7> <open|close>` |",
        "| `shell/main.h/.c` | banner -> bus kur -> `sistemCitInit` -> `shellInit` -> kullanici tablosunu kaydet -> `while (1) shellCheck();` |",
        "",
        "Yeni komut: `shell_user_commands.c`'de `static void shellUser<Ad>(unsigned int uiArgc, const char* cpArrArgv[])`",
        "yaz, `S_sArrUserCommands[]`'a `{\"<ad>\", shellUser<Ad>, \"<args>  aciklama\"}` satiri ekle. Argumanlar string",
        "(`cpArrArgv[1..]`), sayi icin `atoi`. `help` tabloyu otomatik listeler.",
        "",
        "| Komut | Ne yapar |",
        "|---|---|",
        "| `cit` | `sistemCitRead()`; cerceveli/renkli rapor (INFO esigi gecici acilir) |",
        f"| `i2c_search` | {', '.join(c for c, _, _ in i2c) or 'I2C yok'}: 0x08..0x77 yazma probu, ACK listesi (switch adresleri atlanir) |",
        "| `sdl <level>` | set debug level: `error` `warning` `msg` `info` `trace` ya da 0..5 |",
        "| `help` | komut listesi (yerlesik + kullanici) |",
        "| `mod <x> <y>` | ornek kullanici komutu: custom IP reg x (0..7, 4 B ofset) <= desen (`open`) ya da 0 (`close`); `SHELL_USER_MOD_BASEADDR` ayarlanmali |",
        "",
    ]
    return "\n".join(lines)


def write_shell_layer(spec: dict, out_dir: Path, plans: list) -> tuple[list[str], str]:
    """shell/ agacini yazar; (yazilan yollar, README bolumu). CIT plani yoksa bos."""
    if not plans:
        return [], ""
    shell_dir = out_dir / SHELL_DIR
    written = [
        hio.write_output(shell_dir / "shell_uart.h", uart_header()),
        hio.write_output(shell_dir / "shell_uart.c", uart_source(spec)),
        hio.write_output(shell_dir / "shell.h", shell_header()),
        hio.write_output(shell_dir / "shell.c", shell_source(spec, plans)),
        hio.write_output(shell_dir / "shell_user_commands.h", user_commands_header()),
        hio.write_output(shell_dir / "shell_user_commands.c", user_commands_source()),
        hio.write_output(shell_dir / "main.h", main_header(spec)),
        hio.write_output(shell_dir / "main.c", main_source(spec)),
    ]
    return [str(p) for p in written], readme_section(spec, plans)
