"""Shell katmani (``outputs/<proje>/shell/``): konsol UART'indan komutla CIT / I2C tarama / log seviyesi.

Kullanicinin KENDI main'inde derlenir (test bench ajaniyla ilgisi yoktur; ajan bu klasoru
derlemez, Vitis sahnelemesi kopyalamaz). ``drivers/`` ve ``cit/`` gibi tasinabilirdir:
icinde urun adi gecmez.

Uretilen agac:
* ``shell/shell_uart.h/.c`` - BSP stdin/stdout cihazindan (``STDIN_BASEADDRESS``) bloklamadan
                             tek bayt oku/yaz; platforma gore XUartLite / XUartPs / XUartPsv.
* ``shell/shell.h/.c``      - ``shellInit(bus, limit, cit)``, ``shellCheck()`` (ana dongude,
                             bloklamaz) ve komutlar: ``cit``, ``i2c_search``, ``sdl <seviye>``, ``help``.
* ``shell/main_example.c``  - kopyala-yapistir ornek main: bus kur, ``sistemCitInit``,
                             ``shellInit``, ``for (;;) shellCheck();``.

Tasarim notlari:
* Cikti ``xil_printf`` ile konsola gider; ``cit`` komutu ``dbg_printf`` esigini gecici olarak
  INFO'ya cekip ``sistemCitRead``'in cerceveli/renkli raporunu bastirir, sonra geri alir.
* ``i2c_search`` spec'teki her I2C denetleyicisinde 0x08..0x77 tek-bayt yazma probu yapar
  (ajanin i2c_scan'iyle ayni yontem). I2C switch (TCA9548A) adresleri ATLANIR: aktif
  switch'e 0x00 yazmak secili kanali kapatirdi.
"""

from __future__ import annotations

from pathlib import Path
from typing import Callable

from hostplat import io as hio
from orchestrator import cit_layer, cmodel

SHELL_DIR = "shell"

_UART_BY_PLATFORM = {
    "microblaze_7series": "XUartLite",
    "zynq_7000": "XUartPs",
    "zynq_ultrascale": "XUartPs",
    "versal": "XUartPsv",
}

_UART_API = {
    "XUartLite": ("xuartlite_l.h", "XUartLite_IsReceiveEmpty(STDIN_BASEADDRESS) != 0U",
                  "XUartLite_RecvByte", "XUartLite_SendByte"),
    "XUartPs": ("xuartps_hw.h", "XUartPs_IsReceiveData(STDIN_BASEADDRESS) == 0U",
                "XUartPs_RecvByte", "XUartPs_SendByte"),
    "XUartPsv": ("xuartpsv_hw.h", "XUartPsv_IsReceiveData(STDIN_BASEADDRESS) == 0U",
                 "XUartPsv_RecvByte", "XUartPsv_SendByte"),
}


def console_uart_driver(spec: dict) -> str:
    """Konsol UART surucusu: spec'teki MDM olmayan ilk UART, yoksa platform varsayilani."""
    for controller in spec.get("controllers", []):
        if controller.get("type") == "uart" and controller.get("subtype") != "mdm":
            driver = str(controller.get("driver", ""))
            if driver in _UART_API:
                return driver
    platform = str(spec.get("project", {}).get("platform", ""))
    return _UART_BY_PLATFORM.get(platform, "XUartPs")


def uart_header() -> str:
    return (
        "/**\n"
        " * @file shell_uart.h\n"
        " * @brief Konsol UART'i (BSP stdin/stdout) uzerinden bloklamayan bayt okuma/yazma.\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        "#ifndef SHELL_UART_H\n"
        "#define SHELL_UART_H\n\n"
        '#include "xil_types.h"\n\n'
        "/* Konsolda bekleyen bir bayt varsa onu verir ve TRUE doner; yoksa hemen FALSE doner. */\n"
        "unsigned int shellUartByteRead(unsigned char* ucpByte);\n"
        "/* Bir bayti konsola yazar (gonderim FIFO'su doluysa bosalana kadar bekler). */\n"
        "void shellUartByteWrite(unsigned char ucByte);\n\n"
        "#endif /* SHELL_UART_H */\n"
    )


def uart_source(spec: dict) -> str:
    driver = console_uart_driver(spec)
    header, empty_expr, recv, send = _UART_API[driver]
    return (
        "/**\n"
        " * @file shell_uart.c\n"
        f" * @brief Konsol UART'i bayt erisimi ({driver}, BSP STDIN/STDOUT_BASEADDRESS).\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        '#include "shell_uart.h"\n'
        '#include "xparameters.h"\n'
        f'#include "{header}"\n'
        "#include <stddef.h>\n\n"
        "unsigned int shellUartByteRead(unsigned char* ucpByte)\n"
        "{\n"
        "#if defined(STDIN_BASEADDRESS)\n"
        "    if (ucpByte == NULL)\n"
        "    {\n"
        "        return FALSE;\n"
        "    }\n"
        f"    if ({empty_expr})\n"
        "    {\n"
        "        return FALSE;\n"
        "    }\n"
        f"    *ucpByte = (unsigned char){recv}(STDIN_BASEADDRESS);\n"
        "    return TRUE;\n"
        "#else\n"
        "    (void)ucpByte;\n"
        "    return FALSE; /* BSP'de stdin cihazi yok */\n"
        "#endif\n"
        "}\n\n"
        "void shellUartByteWrite(unsigned char ucByte)\n"
        "{\n"
        "#if defined(STDOUT_BASEADDRESS)\n"
        f"    {send}(STDOUT_BASEADDRESS, ucByte);\n"
        "#else\n"
        "    (void)ucByte;\n"
        "#endif\n"
        "}\n"
    )


def shell_header() -> str:
    return (
        "/**\n"
        " * @file shell.h\n"
        " * @brief Konsol komut kabugu: cit / i2c_search / sdl / help.\n"
        " *\n"
        " * Kullanim (kart yazilimi, bkz. main_example.c):\n"
        " *   sistemCitBusVarsayilan(&S_sBus); sistemCitInit(&S_sBus);   -- ana dongu oncesi\n"
        " *   shellInit(&S_sBus, &S_sLimit, &S_sCit);\n"
        " *   for (;;) { shellCheck(); }                                 -- bloklamaz\n"
        " *\n"
        " * Komutlar:\n"
        " *   cit               tum entegreleri oku, cerceveli/renkli raporu bas (sistemCitRead)\n"
        " *   i2c_search        her I2C denetleyicisinde 0x08..0x77 adres tarama (ACK listesi)\n"
        " *   sdl <seviye>      set debug level: error | warning | msg | info | trace (ya da 0..5)\n"
        " *   help              komut listesi\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        "#ifndef SHELL_H\n"
        "#define SHELL_H\n\n"
        '#include "sistem_cit.h"\n\n'
        "#define SHELL_LINE_MAX 48U\n"
        '#define SHELL_PROMPT "> "\n\n'
        "/* Kabugu CIT yapilariyla baglar ve istemi basar. Yapilar cagiranda kalici olmali. */\n"
        "void shellInit(SSistemCitBus* spBus, const SSistemCitLimit* spLimit, SSistemCit* spCit);\n"
        "/* Ana dongude cagrilir: konsolda bayt varsa isler, satir tamamlaninca komutu kosar; bloklamaz. */\n"
        "void shellCheck(void);\n\n"
        "#endif /* SHELL_H */\n"
    )


def _i2c_bus_entries(spec: dict, plans: list) -> list[tuple[str, str, str]]:
    """(denetleyici id, SSistemCitBus alani, surucu) - CIT bus'indaki I2C denetleyicileri."""
    out = []
    for controller in cit_layer.bus_controllers(plans):
        if controller.get("type") != "i2c":
            continue
        htype, _ = cmodel._handle_for(controller)
        out.append((str(controller.get("id")), cit_layer.controller_field(controller), htype))
    return out


def _mux_addresses(spec: dict) -> list[int]:
    addrs = []
    for mux in spec.get("muxes", []):
        try:
            addrs.append(int(str(mux.get("i2c_address", "0")), 0))
        except ValueError:
            continue
    return sorted(set(addrs))


def shell_source(spec: dict, plans: list) -> str:
    i2c = _i2c_bus_entries(spec, plans)
    htypes = sorted({h for _, _, h in i2c})
    mux_addrs = _mux_addresses(spec)
    e = cit_layer._E(0)
    e.ln("/**")
    e.ln(" * @file shell.c")
    e.ln(" * @brief Konsol komut kabugu gerceklemesi. Generated by Spec2Code. Do not edit by hand.")
    e.ln(" */")
    e.ln('#include "shell.h"')
    e.ln('#include "shell_uart.h"')
    e.ln('#include "dbg_printf.h"')
    e.ln('#include "xil_printf.h"')
    e.ln('#include "xstatus.h"')
    if "XIic" in htypes:
        e.ln('#include "xiic.h"')
        e.ln('#include "xiic_l.h"')
    if "XIicPs" in htypes:
        e.ln('#include "xiicps.h"')
    e.ln("#include <stddef.h>")
    e.ln("#include <string.h>")
    e.blank()
    e.ln("static SSistemCitBus* S_spBus = NULL;")
    e.ln("static const SSistemCitLimit* S_spLimit = NULL;")
    e.ln("static SSistemCit* S_spCit = NULL;")
    e.ln("static char S_cArrLine[SHELL_LINE_MAX];")
    e.ln("static unsigned int S_uiLineLength = 0U;")
    if mux_addrs:
        e.ln("/* I2C switch adresleri: taramada atlanir (0x00 yazmak secili kanali kapatirdi). */")
        e.ln("static const unsigned int S_uiArrSwitchAddress[] = {" + ", ".join(f"0x{a:02X}U" for a in mux_addrs) + "};")
    e.blank()
    e.ln("static void shellPromptWrite(void)")
    e.ln("{")
    e.ln('    xil_printf("%s", SHELL_PROMPT);')
    e.ln("}")
    e.blank()
    e.ln("static void shellHelpWrite(void)")
    e.ln("{")
    e.ln('    xil_printf("komutlar:\\r\\n");')
    e.ln('    xil_printf("  cit             tum entegreleri oku, raporu bas\\r\\n");')
    e.ln('    xil_printf("  i2c_search      I2C adres tarama (0x08..0x77)\\r\\n");')
    e.ln('    xil_printf("  sdl <seviye>    log seviyesi: error|warning|msg|info|trace (0..5)\\r\\n");')
    e.ln('    xil_printf("  help            bu liste\\r\\n");')
    e.ln("}")
    e.blank()
    # --- cit
    e.ln("static void shellCommandCit(void)")
    e.ln("{")
    e.ln("    unsigned int uiOldLevel;")
    e.ln("    int iResult;")
    e.blank()
    e.ln("    if ((S_spBus == NULL) || (S_spCit == NULL))")
    e.ln("    {")
    e.ln('        xil_printf("cit: shellInit cagrilmamis\\r\\n");')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    uiOldLevel = dbgLevelGet();")
    e.ln("    if (uiOldLevel < DEBUG_LEVEL_INFO)")
    e.ln("    {")
    e.ln("        (void)dbgLevelSet(DEBUG_LEVEL_INFO); /* rapor INFO seviyesinde basilir */")
    e.ln("    }")
    e.ln("    iResult = sistemCitRead(S_spBus, S_spLimit, S_spCit);")
    e.ln("    (void)dbgLevelSet(uiOldLevel);")
    e.ln(f'    xil_printf("cit: %s (kosu #%u)\\r\\n", (iResult == {cit_layer.STATUS_OK}) ? "OK" : ((iResult == {cit_layer.STATUS_NOK}) ? "NOK" : "HATA"), S_spCit->uiSayac);')
    e.ln("}")
    e.blank()
    # --- i2c_search
    if i2c:
        if mux_addrs:
            e.ln("static unsigned int shellI2cIsSwitchAddress(unsigned int uiAddress)")
            e.ln("{")
            e.ln("    unsigned int uiIndex;")
            e.blank()
            e.ln("    for (uiIndex = 0U; uiIndex < (sizeof(S_uiArrSwitchAddress) / sizeof(S_uiArrSwitchAddress[0])); uiIndex++)")
            e.ln("    {")
            e.ln("        if (S_uiArrSwitchAddress[uiIndex] == uiAddress)")
            e.ln("        {")
            e.ln("            return TRUE;")
            e.ln("        }")
            e.ln("    }")
            e.ln("    return FALSE;")
            e.ln("}")
            e.blank()
        for htype in htypes:
            e.ln(f"static unsigned int shellI2cProbe{htype}({htype}* spIic, unsigned int uiAddress)")
            e.ln("{")
            e.ln("    unsigned char ucProbe = 0x00U;")
            if htype == "XIic":
                e.blank()
                e.ln("    /* Dinamik mod: gonderilen bayt sayisi 1 ise ACK alindi. */")
                e.ln("    return ((unsigned int)XIic_DynSend(spIic->BaseAddress, (unsigned short)uiAddress, &ucProbe, 1U, XIIC_STOP) == 1U) ? TRUE : FALSE;")
            else:
                e.ln("    int iStatus;")
                e.blank()
                e.ln("    iStatus = XIicPs_MasterSendPolled(spIic, &ucProbe, 1, (unsigned short)uiAddress);")
                e.ln("    while (XIicPs_BusIsBusy(spIic) == TRUE)")
                e.ln("    {")
                e.ln("        /* bus bosalana kadar bekle */")
                e.ln("    }")
                e.ln("    return (iStatus == XST_SUCCESS) ? TRUE : FALSE;")
            e.ln("}")
            e.blank()
        e.ln("static void shellCommandI2cSearch(void)")
        e.ln("{")
        e.ln("    unsigned int uiAddress;")
        e.ln("    unsigned int uiFound;")
        e.blank()
        e.ln("    if (S_spBus == NULL)")
        e.ln("    {")
        e.ln('        xil_printf("i2c_search: shellInit cagrilmamis\\r\\n");')
        e.ln("        return;")
        e.ln("    }")
        for cid, fld, htype in i2c:
            e.ln(f'    xil_printf("{cid}: tarama 0x08..0x77\\r\\n");')
            e.ln("    uiFound = 0U;")
            e.ln("    for (uiAddress = 0x08U; uiAddress <= 0x77U; uiAddress++)")
            e.ln("    {")
            if mux_addrs:
                e.ln("        if (shellI2cIsSwitchAddress(uiAddress) == TRUE)")
                e.ln("        {")
                e.ln('            xil_printf("  0x%02X  (I2C switch, atlandi)\\r\\n", uiAddress);')
                e.ln("            continue;")
                e.ln("        }")
            e.ln(f"        if (shellI2cProbe{htype}(S_spBus->{fld}, uiAddress) == TRUE)")
            e.ln("        {")
            e.ln('            xil_printf("  0x%02X  ACK\\r\\n", uiAddress);')
            e.ln("            uiFound++;")
            e.ln("        }")
            e.ln("    }")
            e.ln(f'    xil_printf("{cid}: %u cihaz\\r\\n", uiFound);')
        e.ln("}")
    else:
        e.ln("static void shellCommandI2cSearch(void)")
        e.ln("{")
        e.ln('    xil_printf("i2c_search: bu projede I2C denetleyicisi yok\\r\\n");')
        e.ln("}")
    e.blank()
    # --- sdl
    e.ln("static void shellCommandSdl(const char* cpArgument)")
    e.ln("{")
    e.ln("    unsigned int uiLevel;")
    e.blank()
    e.ln("    if ((cpArgument == NULL) || (cpArgument[0] == '\\0'))")
    e.ln("    {")
    e.ln('        xil_printf("log seviyesi: %s (%u)\\r\\n", dbgLevelName(dbgLevelGet()), dbgLevelGet());')
    e.ln("        return;")
    e.ln("    }")
    e.ln('    if (strcmp(cpArgument, "error") == 0)')
    e.ln("    {")
    e.ln("        uiLevel = DEBUG_LEVEL_ERROR;")
    e.ln("    }")
    e.ln('    else if (strcmp(cpArgument, "warning") == 0)')
    e.ln("    {")
    e.ln("        uiLevel = DEBUG_LEVEL_WARNING;")
    e.ln("    }")
    e.ln('    else if (strcmp(cpArgument, "msg") == 0)')
    e.ln("    {")
    e.ln("        uiLevel = DEBUG_LEVEL_MSG;")
    e.ln("    }")
    e.ln('    else if (strcmp(cpArgument, "info") == 0)')
    e.ln("    {")
    e.ln("        uiLevel = DEBUG_LEVEL_INFO;")
    e.ln("    }")
    e.ln('    else if (strcmp(cpArgument, "trace") == 0)')
    e.ln("    {")
    e.ln("        uiLevel = DEBUG_LEVEL_TRACE;")
    e.ln("    }")
    e.ln("    else if ((cpArgument[0] >= '0') && (cpArgument[0] <= '5') && (cpArgument[1] == '\\0'))")
    e.ln("    {")
    e.ln("        uiLevel = (unsigned int)(cpArgument[0] - '0');")
    e.ln("    }")
    e.ln("    else")
    e.ln("    {")
    e.ln('        xil_printf("sdl: gecersiz seviye \'%s\' (error|warning|msg|info|trace|0..5)\\r\\n", cpArgument);')
    e.ln("        return;")
    e.ln("    }")
    e.ln("    (void)dbgLevelSet(uiLevel);")
    e.ln('    xil_printf("log seviyesi: %s (%u)\\r\\n", dbgLevelName(dbgLevelGet()), dbgLevelGet());')
    e.ln("}")
    e.blank()
    # --- dispatch
    e.ln("static void shellLineExecute(char* cpLine)")
    e.ln("{")
    e.ln("    char* cpArgument;")
    e.blank()
    e.ln("    while (*cpLine == ' ')")
    e.ln("    {")
    e.ln("        cpLine++;")
    e.ln("    }")
    e.ln("    if (*cpLine == '\\0')")
    e.ln("    {")
    e.ln("        return;")
    e.ln("    }")
    e.ln("    cpArgument = strchr(cpLine, ' ');")
    e.ln("    if (cpArgument != NULL)")
    e.ln("    {")
    e.ln("        *cpArgument = '\\0';")
    e.ln("        cpArgument++;")
    e.ln("        while (*cpArgument == ' ')")
    e.ln("        {")
    e.ln("            cpArgument++;")
    e.ln("        }")
    e.ln("    }")
    e.ln('    if (strcmp(cpLine, "cit") == 0)')
    e.ln("    {")
    e.ln("        shellCommandCit();")
    e.ln("    }")
    e.ln('    else if (strcmp(cpLine, "i2c_search") == 0)')
    e.ln("    {")
    e.ln("        shellCommandI2cSearch();")
    e.ln("    }")
    e.ln('    else if (strcmp(cpLine, "sdl") == 0)')
    e.ln("    {")
    e.ln("        shellCommandSdl(cpArgument);")
    e.ln("    }")
    e.ln('    else if (strcmp(cpLine, "help") == 0)')
    e.ln("    {")
    e.ln("        shellHelpWrite();")
    e.ln("    }")
    e.ln("    else")
    e.ln("    {")
    e.ln('        xil_printf("bilinmeyen komut: %s (help)\\r\\n", cpLine);')
    e.ln("    }")
    e.ln("}")
    e.blank()
    e.ln("void shellInit(SSistemCitBus* spBus, const SSistemCitLimit* spLimit, SSistemCit* spCit)")
    e.ln("{")
    e.ln("    S_spBus = spBus;")
    e.ln("    S_spLimit = spLimit;")
    e.ln("    S_spCit = spCit;")
    e.ln("    S_uiLineLength = 0U;")
    e.ln("    S_cArrLine[0] = '\\0';")
    e.ln('    xil_printf("\\r\\nkomut kabugu hazir (help)\\r\\n");')
    e.ln("    shellPromptWrite();")
    e.ln("}")
    e.blank()
    e.ln("void shellCheck(void)")
    e.ln("{")
    e.ln("    unsigned char ucByte;")
    e.blank()
    e.ln("    while (shellUartByteRead(&ucByte) == TRUE)")
    e.ln("    {")
    e.ln("        if ((ucByte == (unsigned char)'\\r') || (ucByte == (unsigned char)'\\n'))")
    e.ln("        {")
    e.ln("            if (S_uiLineLength == 0U)")
    e.ln("            {")
    e.ln("                /* CR+LF ciftinin ikinci karakteri ya da bos satir: yalniz istem. */")
    e.ln('                xil_printf("\\r\\n");')
    e.ln("                shellPromptWrite();")
    e.ln("                continue;")
    e.ln("            }")
    e.ln('            xil_printf("\\r\\n");')
    e.ln("            S_cArrLine[S_uiLineLength] = '\\0';")
    e.ln("            shellLineExecute(S_cArrLine);")
    e.ln("            S_uiLineLength = 0U;")
    e.ln("            shellPromptWrite();")
    e.ln("        }")
    e.ln("        else if ((ucByte == 0x08U) || (ucByte == 0x7FU))")
    e.ln("        {")
    e.ln("            if (S_uiLineLength > 0U)")
    e.ln("            {")
    e.ln("                S_uiLineLength--;")
    e.ln('                xil_printf("\\b \\b");')
    e.ln("            }")
    e.ln("        }")
    e.ln("        else if ((ucByte >= 0x20U) && (ucByte < 0x7FU))")
    e.ln("        {")
    e.ln("            if (S_uiLineLength < (SHELL_LINE_MAX - 1U))")
    e.ln("            {")
    e.ln("                S_cArrLine[S_uiLineLength] = (char)ucByte;")
    e.ln("                S_uiLineLength++;")
    e.ln("                shellUartByteWrite(ucByte); /* yansi */")
    e.ln("            }")
    e.ln("        }")
    e.ln("        else")
    e.ln("        {")
    e.ln("            /* diger kontrol karakterleri yok sayilir */")
    e.ln("        }")
    e.ln("    }")
    e.ln("}")
    return e.text() + "\n"


def main_example_source(spec: dict) -> str:
    name = str(spec.get("project", {}).get("name", "kart"))
    return (
        "/**\n"
        " * @file main_example.c\n"
        f" * @brief {name}: ornek ana program - CIT + konsol kabugu. Kendi projene kopyala ve uyarla.\n"
        " *\n"
        " * Derleme: drivers/ (kart alt klasorleri dahil), cit/ ve shell/ include yolunda; dbg_printf.c\n"
        " * dahil tum .c dosyalari projede. Test bench ajani (tests/) BU projeye alinmaz.\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        '#include "main_example.h"\n'
        '#include "dbg_printf.h"\n'
        '#include "sistem_cit.h"\n'
        '#include "shell.h"\n\n'
        "static SSistemCitBus S_sBus;\n"
        "static const SSistemCitLimit S_sLimit = SISTEM_CIT_LIMIT_VARSAYILAN;\n"
        "static SSistemCit S_sCit;\n\n"
        "int main(void)\n"
        "{\n"
        "    int iStatus;\n\n"
        "    (void)dbgLevelSet(DEBUG_LEVEL_ERROR); /* sdl komutuyla canli degisir */\n"
        "    sistemCitBusVarsayilan(&S_sBus); /* denetleyici ornekleri + I2C cihaz tablosu */\n"
        "    iStatus = sistemCitInit(&S_sBus); /* her entegrenin DeviceInit'i */\n"
        f"    if (iStatus != {cit_layer.STATUS_OK})\n"
        "    {\n"
        '        dbg_printf(DEBUG_LEVEL_ERROR, "sistemCitInit: %d", iStatus);\n'
        "    }\n"
        "    shellInit(&S_sBus, &S_sLimit, &S_sCit);\n"
        "    for (;;)\n"
        "    {\n"
        "        shellCheck(); /* konsolda komut varsa isler; bloklamaz */\n"
        "        /* kendi periyodik islerin buraya */\n"
        "    }\n"
        "    return 0;\n"
        "}\n"
    )


def main_example_header(spec: dict) -> str:
    name = str(spec.get("project", {}).get("name", "kart"))
    return (
        "/**\n"
        " * @file main_example.h\n"
        f" * @brief {name}: ornek ana program bildirimi (main_example.c ile cift).\n"
        " *\n"
        " * Generated by Spec2Code. Do not edit by hand.\n"
        " */\n"
        "#ifndef MAIN_EXAMPLE_H\n"
        "#define MAIN_EXAMPLE_H\n\n"
        "int main(void);\n\n"
        "#endif /* MAIN_EXAMPLE_H */\n"
    )


def readme_section(spec: dict, plans: list) -> str:
    i2c = _i2c_bus_entries(spec, plans)
    lines = [
        "",
        "## Konsol kabugu (`shell/`)",
        "",
        "Kendi main'inde derlenir; test bench ajaniyla ilgisi yoktur. Konsol UART'indan (BSP stdin,",
        f"`{console_uart_driver(spec)}`) satir okur, komutu kosar. `main_example.c` kopyala-yapistir ornektir.",
        "",
        "| Dosya | Icerik |",
        "|---|---|",
        "| `shell/shell_uart.h/.c` | `shellUartByteRead()` (bloklamaz) / `shellUartByteWrite()` |",
        "| `shell/shell.h/.c` | `shellInit(bus, limit, cit)`, `shellCheck()`; komutlar `cit`, `i2c_search`, `sdl`, `help` |",
        "| `shell/main_example.h/.c` | bus kur -> `sistemCitInit` -> `shellInit` -> `for (;;) shellCheck();` |",
        "",
        "| Komut | Ne yapar |",
        "|---|---|",
        "| `cit` | `sistemCitRead()`; cerceveli/renkli rapor (INFO esigi gecici acilir) |",
        f"| `i2c_search` | {', '.join(c for c, _, _ in i2c) or 'I2C yok'}: 0x08..0x77 yazma probu, ACK listesi (switch adresleri atlanir) |",
        "| `sdl <seviye>` | set debug level: `error` `warning` `msg` `info` `trace` ya da 0..5 |",
        "| `help` | komut listesi |",
        "",
    ]
    return "\n".join(lines)


def write_shell_layer(spec: dict, out_dir: Path, plans: list) -> tuple[list[str], str]:
    """shell/ agacini yazar; (yazilan yollar, README bolumu). CIT plani yoksa bos."""
    if not plans:
        return [], ""
    shell_dir = out_dir / SHELL_DIR
    written = [
        hio.write_output(shell_dir / "shell_uart.h", uart_header()),
        hio.write_output(shell_dir / "shell_uart.c", uart_source(spec)),
        hio.write_output(shell_dir / "shell.h", shell_header()),
        hio.write_output(shell_dir / "shell.c", shell_source(spec, plans)),
        hio.write_output(shell_dir / "main_example.h", main_example_header(spec)),
        hio.write_output(shell_dir / "main_example.c", main_example_source(spec)),
    ]
    return [str(p) for p in written], readme_section(spec, plans)
