"""Sanal cihaz altyapisi (``tests/sim/``): Xilinx API seviyesinde araya girme.

Tasarim: docs/superpowers/specs/2026-09-06-driver-struct-api-design.md

Suruculer Xilinx API'sini DOGRUDAN cagirir (kullaniciya giden katman saf kalir).
Test bench derlemesinde ``spec2code_sim_xilinx.h`` ``-include`` ile her ceviri
birimine girer ve ``XIic_DynSend`` gibi veri-yolu fonksiyonlarini makroyla
``spec2codeSim*`` sarmalayicilarina yonlendirir. Sarmalayici, adres (I2C) ya da
chip-select (SPI) sanal cihaz zincirinde kayitliysa simulatoru kosturur; degilse
GERCEK Xilinx fonksiyonunu cagirir (karisik mod: ayni hatta gercek + sanal).

Uretilen dosyalar:
* ``tests/sim/spec2code_sim.h/.c``       - cihaz kaydi, sanal TCA9548A switch, sarmalayicilar.
* ``tests/sim/spec2code_sim_xilinx.h``   - ``-include`` basligi (yalniz makrolar).
* ``tests/sim/<mod>_sim.h/.c``           - register-dosyasi simulatorleri (cit_sim).
"""

from __future__ import annotations

from pathlib import Path

from hostplat import io as hio

SIM_DIR = "sim"
INTERPOSE_HEADER = "spec2code_sim_xilinx.h"

#: (makro, sarmalayici) - Xilinx veri-yolu fonksiyonlari.
_INTERPOSED = [
    ("XIic_DynSend", "spec2codeSimXIicDynSend"),
    ("XIic_DynRecv", "spec2codeSimXIicDynRecv"),
    ("XIic_Send", "spec2codeSimXIicSend"),
    ("XIic_Recv", "spec2codeSimXIicRecv"),
    ("XIicPs_MasterSendPolled", "spec2codeSimXIicPsMasterSendPolled"),
    ("XIicPs_MasterRecvPolled", "spec2codeSimXIicPsMasterRecvPolled"),
    ("XSpi_SetSlaveSelect", "spec2codeSimXSpiSetSlaveSelect"),
    ("XSpi_Transfer", "spec2codeSimXSpiTransfer"),
    ("XSpiPs_SetSlaveSelect", "spec2codeSimXSpiPsSetSlaveSelect"),
    ("XSpiPs_PolledTransfer", "spec2codeSimXSpiPsPolledTransfer"),
]


def interpose_header() -> str:
    lines = [
        "/**",
        f" * @file {INTERPOSE_HEADER}",
        " * @brief Test bench derlemesinde `-include` ile her ceviri birimine giren araya-girme",
        " *        basligi: Xilinx veri-yolu fonksiyonlari spec2codeSim* sarmalayicilarina",
        " *        yonlendirilir (sanal cihaz varsa simulator, yoksa gercek fonksiyon).",
        " *",
        " * Suruculer (drivers/) bu dosyayi BILMEZ; kullanici firmware'inde derlemeye girmez.",
        " * spec2code_sim.c kendi icinde bu makrolari #undef edip gercek fonksiyonlari cagirir.",
        " * Generated by Spec2Code. Do not edit by hand.",
        " */",
        "#ifndef SPEC2CODE_SIM_XILINX_H",
        "#define SPEC2CODE_SIM_XILINX_H",
        "",
    ]
    for real, wrapper in _INTERPOSED:
        lines.append(f"#define {real} {wrapper}")
    lines.extend(["", "#endif /* SPEC2CODE_SIM_XILINX_H */", ""])
    return "\n".join(lines)


def sim_header() -> str:
    return """/**
 * @file spec2code_sim.h
 * @brief Sanal cihaz altyapisi: cihaz kaydi (I2C adres / SPI chip-select), sanal TCA9548A
 *        switch, hata enjeksiyon kodlari ve Xilinx sarmalayici prototipleri.
 *
 * Karisik mod: yalniz kayitli adres/CS sanal cevap verir; digerleri gercek donanima gider.
 * Generated by Spec2Code. Do not edit by hand.
 */
#ifndef SPEC2CODE_SIM_H
#define SPEC2CODE_SIM_H

#define SPEC2CODE_CIT_SIM 1

/* Hata enjeksiyon modlari (<mod>SimHataAyarla). */
#define SPEC2CODE_SIM_HATA_YOK 0U
#define SPEC2CODE_SIM_HATA_NACK 1U     /* her transfer basarisiz (cihaz yok gibi) */
#define SPEC2CODE_SIM_HATA_HAZIR_YOK 2U /* hazir/veri-gecerli bitleri hic kurulmaz */

/**
 * @brief Sanal I2C cihazi zincir dugumu. Simulator struct'i bunu ILK alani olarak tasir;
 *        pfYaz/pfOku o cihazin register modelini kosturur (0 basari, sifir disi NACK).
 */
typedef struct SSpec2codeI2cSimCihaz
{
    unsigned char ucAdres; /* 7-bit adres (eslestirme anahtari) */
    void* vpDurum;         /* cihaz modeli (sahibi simulator) */
    int (*pfYaz)(void* vpDurum, const unsigned char* ucpVeri, unsigned int uiBoy);
    int (*pfOku)(void* vpDurum, unsigned char* ucpVeri, unsigned int uiBoy);
    struct SSpec2codeI2cSimCihaz* spSonraki;
} SSpec2codeI2cSimCihaz;

/**
 * @brief Sanal SPI cihazi zincir dugumu (chip-select indeksiyle eslesir).
 */
typedef struct SSpec2codeSpiSimCihaz
{
    unsigned char ucSelect; /* chip-select indeksi (eslestirme anahtari) */
    void* vpDurum;
    int (*pfTransfer)(void* vpDurum, const unsigned char* ucpTx, unsigned char* ucpRx,
                      unsigned int uiBoy);
    struct SSpec2codeSpiSimCihaz* spSonraki;
} SSpec2codeSpiSimCihaz;

/**
 * @brief Sanal I2C switch (TCA9548A): kontrol bayti yazilir/okunur, kanal kaydedilir.
 *        Gercek switch takili degilken (arkasindaki HER cihaz sanalken) kaydedilir.
 */
typedef struct
{
    SSpec2codeI2cSimCihaz sCihaz; /* zincir dugumu (ILK alan) */
    unsigned char ucKontrol;      /* son yazilan kanal maskesi */
    unsigned int uiSecimSayac;    /* kac kez kanal secildi */
} SSpec2codeI2cSimSwitch;

void spec2codeSimSwitchKur(SSpec2codeI2cSimSwitch* spSwitch, unsigned char ucAdres);

/* --- kayit --- */
int spec2codeSimI2cEkle(SSpec2codeI2cSimCihaz* spCihaz);
int spec2codeSimI2cKaldir(SSpec2codeI2cSimCihaz* spCihaz);
SSpec2codeI2cSimCihaz* spec2codeSimI2cBul(unsigned char ucAdres);
int spec2codeSimSpiEkle(SSpec2codeSpiSimCihaz* spCihaz);
int spec2codeSimSpiKaldir(SSpec2codeSpiSimCihaz* spCihaz);
SSpec2codeSpiSimCihaz* spec2codeSimSpiBul(unsigned char ucSelect);
unsigned int spec2codeSimCihazSayisi(void);

#endif /* SPEC2CODE_SIM_H */
"""


def sim_source() -> str:
    undefs = "\n".join(f"#undef {real}" for real, _w in _INTERPOSED)
    return f"""/**
 * @file spec2code_sim.c
 * @brief Sanal cihaz kaydi + Xilinx veri-yolu sarmalayicilari (karisik mod).
 *
 * Bu dosya -include basligiyla derlense de asagida makrolar #undef edilir ve
 * GERCEK Xilinx fonksiyonlari elle bildirilip cagirilir. Hangi Xilinx surucusunun
 * BSP'de bulundugu xparameters.h'teki XPAR_*_NUM_INSTANCES ile anlasilir.
 * Generated by Spec2Code. Do not edit by hand.
 */
#include "spec2code_sim.h"
#include "xparameters.h"
#include "xil_types.h"
#include "xstatus.h"
#include <stddef.h>

{undefs}

/* --- kayit zincirleri (adres / chip-select anahtarli, denetleyiciden bagimsiz) --- */
static SSpec2codeI2cSimCihaz* S_spI2cZincir = NULL;
static SSpec2codeSpiSimCihaz* S_spSpiZincir = NULL;
static unsigned int S_uiCihazSayisi = 0U;
static unsigned char S_ucSpiSonSelect = 0xFFU; /* son SetSlaveSelect (AXI one-hot -> indeks) */

int spec2codeSimI2cEkle(SSpec2codeI2cSimCihaz* spCihaz)
{{
    if (spCihaz == NULL)
    {{
        return 1;
    }}
    (void)spec2codeSimI2cKaldir(spCihaz);
    spCihaz->spSonraki = S_spI2cZincir;
    S_spI2cZincir = spCihaz;
    S_uiCihazSayisi++;
    return 0;
}}

int spec2codeSimI2cKaldir(SSpec2codeI2cSimCihaz* spCihaz)
{{
    SSpec2codeI2cSimCihaz** sppNode = &S_spI2cZincir;

    while (*sppNode != NULL)
    {{
        if (*sppNode == spCihaz)
        {{
            *sppNode = spCihaz->spSonraki;
            spCihaz->spSonraki = NULL;
            S_uiCihazSayisi--;
            return 0;
        }}
        sppNode = &(*sppNode)->spSonraki;
    }}
    return 1;
}}

SSpec2codeI2cSimCihaz* spec2codeSimI2cBul(unsigned char ucAdres)
{{
    SSpec2codeI2cSimCihaz* spNode = S_spI2cZincir;

    while (spNode != NULL)
    {{
        if (spNode->ucAdres == ucAdres)
        {{
            return spNode;
        }}
        spNode = spNode->spSonraki;
    }}
    return NULL;
}}

int spec2codeSimSpiEkle(SSpec2codeSpiSimCihaz* spCihaz)
{{
    if (spCihaz == NULL)
    {{
        return 1;
    }}
    (void)spec2codeSimSpiKaldir(spCihaz);
    spCihaz->spSonraki = S_spSpiZincir;
    S_spSpiZincir = spCihaz;
    S_uiCihazSayisi++;
    return 0;
}}

int spec2codeSimSpiKaldir(SSpec2codeSpiSimCihaz* spCihaz)
{{
    SSpec2codeSpiSimCihaz** sppNode = &S_spSpiZincir;

    while (*sppNode != NULL)
    {{
        if (*sppNode == spCihaz)
        {{
            *sppNode = spCihaz->spSonraki;
            spCihaz->spSonraki = NULL;
            S_uiCihazSayisi--;
            return 0;
        }}
        sppNode = &(*sppNode)->spSonraki;
    }}
    return 1;
}}

SSpec2codeSpiSimCihaz* spec2codeSimSpiBul(unsigned char ucSelect)
{{
    SSpec2codeSpiSimCihaz* spNode = S_spSpiZincir;

    while (spNode != NULL)
    {{
        if (spNode->ucSelect == ucSelect)
        {{
            return spNode;
        }}
        spNode = spNode->spSonraki;
    }}
    return NULL;
}}

unsigned int spec2codeSimCihazSayisi(void)
{{
    return S_uiCihazSayisi;
}}

/* --- sanal TCA9548A --- */
static int spec2codeSimSwitchYaz(void* vpDurum, const unsigned char* ucpVeri, unsigned int uiBoy)
{{
    SSpec2codeI2cSimSwitch* spSwitch = (SSpec2codeI2cSimSwitch*)vpDurum;

    if (uiBoy == 0U)
    {{
        return 0;
    }}
    spSwitch->ucKontrol = ucpVeri[0];
    spSwitch->uiSecimSayac++;
    return 0;
}}

static int spec2codeSimSwitchOku(void* vpDurum, unsigned char* ucpVeri, unsigned int uiBoy)
{{
    SSpec2codeI2cSimSwitch* spSwitch = (SSpec2codeI2cSimSwitch*)vpDurum;
    unsigned int uiIndex;

    for (uiIndex = 0U; uiIndex < uiBoy; uiIndex++)
    {{
        ucpVeri[uiIndex] = spSwitch->ucKontrol;
    }}
    return 0;
}}

void spec2codeSimSwitchKur(SSpec2codeI2cSimSwitch* spSwitch, unsigned char ucAdres)
{{
    if (spSwitch == NULL)
    {{
        return;
    }}
    spSwitch->sCihaz.ucAdres = ucAdres;
    spSwitch->sCihaz.vpDurum = spSwitch;
    spSwitch->sCihaz.pfYaz = spec2codeSimSwitchYaz;
    spSwitch->sCihaz.pfOku = spec2codeSimSwitchOku;
    spSwitch->sCihaz.spSonraki = NULL;
    spSwitch->ucKontrol = 0U;
    spSwitch->uiSecimSayac = 0U;
}}

/* --- AXI IIC (xiic_l.h) --- */
#if defined(XPAR_XIIC_NUM_INSTANCES) && (XPAR_XIIC_NUM_INSTANCES > 0)
#include "xiic_l.h"
/* Gercek fonksiyonlar (baslik makroyla sarmalayiciyi bildirdi; gercekleri elle bildiririz). */
unsigned XIic_DynSend(UINTPTR BaseAddress, u16 Address, u8* BufferPtr, u8 ByteCount, u8 Option);
unsigned XIic_DynRecv(UINTPTR BaseAddress, u8 Address, u8* BufferPtr, u8 ByteCount);
unsigned XIic_Send(UINTPTR BaseAddress, u8 Address, u8* BufferPtr, unsigned ByteCount, u8 Option);
unsigned XIic_Recv(UINTPTR BaseAddress, u8 Address, u8* BufferPtr, unsigned ByteCount, u8 Option);

unsigned spec2codeSimXIicDynSend(UINTPTR BaseAddress, u16 Address, u8* BufferPtr, u8 ByteCount,
                                 u8 Option)
{{
    SSpec2codeI2cSimCihaz* spCihaz = spec2codeSimI2cBul((unsigned char)(Address & 0x7FU));

    if (spCihaz != NULL)
    {{
        return (spCihaz->pfYaz(spCihaz->vpDurum, BufferPtr, (unsigned int)ByteCount) == 0)
                   ? (unsigned)ByteCount
                   : 0U;
    }}
    return XIic_DynSend(BaseAddress, Address, BufferPtr, ByteCount, Option);
}}

unsigned spec2codeSimXIicDynRecv(UINTPTR BaseAddress, u8 Address, u8* BufferPtr, u8 ByteCount)
{{
    SSpec2codeI2cSimCihaz* spCihaz = spec2codeSimI2cBul((unsigned char)(Address & 0x7FU));

    if (spCihaz != NULL)
    {{
        return (spCihaz->pfOku(spCihaz->vpDurum, BufferPtr, (unsigned int)ByteCount) == 0)
                   ? (unsigned)ByteCount
                   : 0U;
    }}
    return XIic_DynRecv(BaseAddress, Address, BufferPtr, ByteCount);
}}

unsigned spec2codeSimXIicSend(UINTPTR BaseAddress, u8 Address, u8* BufferPtr, unsigned ByteCount,
                              u8 Option)
{{
    SSpec2codeI2cSimCihaz* spCihaz = spec2codeSimI2cBul((unsigned char)(Address & 0x7FU));

    if (spCihaz != NULL)
    {{
        return (spCihaz->pfYaz(spCihaz->vpDurum, BufferPtr, ByteCount) == 0) ? ByteCount : 0U;
    }}
    return XIic_Send(BaseAddress, Address, BufferPtr, ByteCount, Option);
}}

unsigned spec2codeSimXIicRecv(UINTPTR BaseAddress, u8 Address, u8* BufferPtr, unsigned ByteCount,
                              u8 Option)
{{
    SSpec2codeI2cSimCihaz* spCihaz = spec2codeSimI2cBul((unsigned char)(Address & 0x7FU));

    if (spCihaz != NULL)
    {{
        return (spCihaz->pfOku(spCihaz->vpDurum, BufferPtr, ByteCount) == 0) ? ByteCount : 0U;
    }}
    return XIic_Recv(BaseAddress, Address, BufferPtr, ByteCount, Option);
}}
#endif /* XPAR_XIIC_NUM_INSTANCES */

/* --- PS I2C (xiicps.h) --- */
#if defined(XPAR_XIICPS_NUM_INSTANCES) && (XPAR_XIICPS_NUM_INSTANCES > 0)
#include "xiicps.h"
s32 XIicPs_MasterSendPolled(XIicPs* InstancePtr, u8* MsgPtr, s32 ByteCount, u16 SlaveAddr);
s32 XIicPs_MasterRecvPolled(XIicPs* InstancePtr, u8* MsgPtr, s32 ByteCount, u16 SlaveAddr);

s32 spec2codeSimXIicPsMasterSendPolled(XIicPs* InstancePtr, u8* MsgPtr, s32 ByteCount, u16 SlaveAddr)
{{
    SSpec2codeI2cSimCihaz* spCihaz = spec2codeSimI2cBul((unsigned char)(SlaveAddr & 0x7FU));

    if (spCihaz != NULL)
    {{
        return (spCihaz->pfYaz(spCihaz->vpDurum, MsgPtr, (unsigned int)ByteCount) == 0)
                   ? XST_SUCCESS
                   : XST_FAILURE;
    }}
    return XIicPs_MasterSendPolled(InstancePtr, MsgPtr, ByteCount, SlaveAddr);
}}

s32 spec2codeSimXIicPsMasterRecvPolled(XIicPs* InstancePtr, u8* MsgPtr, s32 ByteCount, u16 SlaveAddr)
{{
    SSpec2codeI2cSimCihaz* spCihaz = spec2codeSimI2cBul((unsigned char)(SlaveAddr & 0x7FU));

    if (spCihaz != NULL)
    {{
        return (spCihaz->pfOku(spCihaz->vpDurum, MsgPtr, (unsigned int)ByteCount) == 0)
                   ? XST_SUCCESS
                   : XST_FAILURE;
    }}
    return XIicPs_MasterRecvPolled(InstancePtr, MsgPtr, ByteCount, SlaveAddr);
}}
#endif /* XPAR_XIICPS_NUM_INSTANCES */

/* --- AXI SPI (xspi.h): SetSlaveSelect one-hot maskesi -> indeks; Transfer CS ile eslenir --- */
#if defined(XPAR_XSPI_NUM_INSTANCES) && (XPAR_XSPI_NUM_INSTANCES > 0)
#include "xspi.h"
int XSpi_SetSlaveSelect(XSpi* InstancePtr, u32 SlaveMask);
int XSpi_Transfer(XSpi* InstancePtr, u8* SendBufPtr, u8* RecvBufPtr, unsigned int ByteCount);

int spec2codeSimXSpiSetSlaveSelect(XSpi* InstancePtr, u32 SlaveMask)
{{
    unsigned char ucIndex = 0U;
    u32 uiMask = SlaveMask;

    S_ucSpiSonSelect = 0xFFU;
    while ((uiMask != 0U) && (ucIndex < 32U))
    {{
        if ((uiMask & 0x1U) != 0U)
        {{
            S_ucSpiSonSelect = ucIndex;
            break;
        }}
        uiMask >>= 1U;
        ucIndex++;
    }}
    if ((S_ucSpiSonSelect != 0xFFU) && (spec2codeSimSpiBul(S_ucSpiSonSelect) != NULL))
    {{
        return XST_SUCCESS; /* sanal CS: donanima dokunma */
    }}
    return XSpi_SetSlaveSelect(InstancePtr, SlaveMask);
}}

int spec2codeSimXSpiTransfer(XSpi* InstancePtr, u8* SendBufPtr, u8* RecvBufPtr, unsigned int ByteCount)
{{
    SSpec2codeSpiSimCihaz* spCihaz =
        (S_ucSpiSonSelect != 0xFFU) ? spec2codeSimSpiBul(S_ucSpiSonSelect) : NULL;

    if (spCihaz != NULL)
    {{
        return (spCihaz->pfTransfer(spCihaz->vpDurum, SendBufPtr, RecvBufPtr, ByteCount) == 0)
                   ? XST_SUCCESS
                   : XST_FAILURE;
    }}
    return XSpi_Transfer(InstancePtr, SendBufPtr, RecvBufPtr, ByteCount);
}}
#endif /* XPAR_XSPI_NUM_INSTANCES */

/* --- PS SPI (xspips.h) --- */
#if defined(XPAR_XSPIPS_NUM_INSTANCES) && (XPAR_XSPIPS_NUM_INSTANCES > 0)
#include "xspips.h"
s32 XSpiPs_SetSlaveSelect(XSpiPs* InstancePtr, u8 SlaveSel);
s32 XSpiPs_PolledTransfer(XSpiPs* InstancePtr, u8* SendBufPtr, u8* RecvBufPtr, u32 ByteCount);

s32 spec2codeSimXSpiPsSetSlaveSelect(XSpiPs* InstancePtr, u8 SlaveSel)
{{
    S_ucSpiSonSelect = SlaveSel;
    if (spec2codeSimSpiBul(SlaveSel) != NULL)
    {{
        return XST_SUCCESS;
    }}
    return XSpiPs_SetSlaveSelect(InstancePtr, SlaveSel);
}}

s32 spec2codeSimXSpiPsPolledTransfer(XSpiPs* InstancePtr, u8* SendBufPtr, u8* RecvBufPtr, u32 ByteCount)
{{
    SSpec2codeSpiSimCihaz* spCihaz =
        (S_ucSpiSonSelect != 0xFFU) ? spec2codeSimSpiBul(S_ucSpiSonSelect) : NULL;

    if (spCihaz != NULL)
    {{
        return (spCihaz->pfTransfer(spCihaz->vpDurum, SendBufPtr, RecvBufPtr, (unsigned int)ByteCount) == 0)
                   ? XST_SUCCESS
                   : XST_FAILURE;
    }}
    return XSpiPs_PolledTransfer(InstancePtr, SendBufPtr, RecvBufPtr, ByteCount);
}}
#endif /* XPAR_XSPIPS_NUM_INSTANCES */
"""


def write_sim_infra(out_dir: Path) -> list[str]:
    """tests/sim/ altyapi dosyalarini yazar (register-dosyasi simulatorleri cit_sim'den gelir)."""
    sim_dir = Path(out_dir) / "tests" / SIM_DIR
    written = [
        hio.write_output(sim_dir / "spec2code_sim.h", sim_header()),
        hio.write_output(sim_dir / "spec2code_sim.c", sim_source()),
        hio.write_output(sim_dir / INTERPOSE_HEADER, interpose_header()),
    ]
    return [str(p) for p in written]
